/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2026-01-22
 *
 * Passkey (WebAuthn) SDK Module
 *
 * This module provides a complete solution for passkey (WebAuthn) authentication:
 *
 * ## High-Level API (Recommended)
 *
 * These functions handle the complete WebAuthn ceremony automatically:
 *
 * - `checkPasskeySupport()` - Check browser capabilities
 * - `signupWithPasskey()` - Register new user with passkey (no password) - Added 2026-01-22
 * - `registerPasskey()` - Register a new passkey (for existing users)
 * - `authenticateWithPasskey()` - Authenticate with passkey
 * - `startConditionalAuthentication()` - Enable autofill passkey login
 * - `listUserPasskeys()` - List user's passkeys
 * - `deleteUserPasskey()` - Delete a passkey
 *
 * ## Low-Level API (Advanced)
 *
 * For custom WebAuthn implementations, import directly from auth/user modules:
 *
 * ```typescript
 * // Auth ceremony functions
 * import {
 *   startPasskeyRegistration,
 *   finishPasskeyRegistration,
 *   startPasskeyAuthentication,
 *   finishPasskeyAuthentication,
 * } from '@/api/auth/client';
 *
 * // Passkey management functions
 * import { listPasskeys, deletePasskey } from '@/api/user/client';
 * ```
 *
 * ## Utilities
 *
 * - `arrayBufferToBase64URL()` / `base64URLToArrayBuffer()` - Encoding helpers
 * - `isWebAuthnSupported()` - Browser support check
 * - `isPlatformAuthenticatorAvailable()` - Biometric support check
 * - `isConditionalUISupported()` - Autofill support check
 * - `parsePasskeyError()` - Error handling helper
 *
 * @example
 * ```typescript
 * import {
 *   checkPasskeySupport,
 *   registerPasskey,
 *   authenticateWithPasskey,
 *   parsePasskeyError,
 * } from '@/api/passkey';
 *
 * // Check if passkeys are supported
 * const capabilities = await checkPasskeySupport();
 * if (!capabilities.isSupported) {
 *   console.log('Passkeys not supported');
 *   return;
 * }
 *
 * // Register a new passkey
 * try {
 *   const { passkey } = await registerPasskey({
 *     deviceName: 'My Device',
 *   });
 *   console.log('Registered:', passkey.id);
 * } catch (error) {
 *   const { type, message } = parsePasskeyError(error);
 *   if (type !== 'user_cancelled') {
 *     console.error(message);
 *   }
 * }
 *
 * // Login with passkey
 * try {
 *   const { user } = await authenticateWithPasskey();
 *   console.log('Welcome,', user.name);
 * } catch (error) {
 *   // Handle error
 * }
 * ```
 */

// Export all types
export * from './types';

// Export utility functions
export * from './utils';

// Export high-level client functions
export {
  checkPasskeySupport,
  signupWithPasskey,
  registerPasskey,
  authenticateWithPasskey,
  startConditionalAuthentication,
  listUserPasskeys,
  deleteUserPasskey,
} from './client';
