/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2026-01-22
 *
 * Passkey (WebAuthn) Type Definitions
 * Re-exports types from auth module and adds passkey-specific types.
 */

// Re-export all passkey-related types from auth module
// These are the canonical type definitions shared across the SDK
export type {
  StartPasskeyRegistrationRequest,
  StartPasskeyAuthenticationRequest,
  AuthenticatorAttestationResponse,
  FinishPasskeyRegistrationRequest,
  AuthenticatorAssertionResponse,
  FinishPasskeyAuthenticationRequest,
  PasskeyCredential,
  PasskeyRegistrationResponse,
  PasskeyLoginResponse,
  ListPasskeysResponse,
  // Passkey Signup types - Added 2026-01-22
  StartPasskeySignupRequest,
  StartPasskeySignupResponse,
  FinishPasskeySignupRequest,
  PasskeySignupResponse,
} from '../auth/types';

// Re-export user display info for login response
export type { UserDisplayInfo } from '../auth/types';

// Re-export error type from utils
export type { PasskeyErrorType } from './utils';

// ============================================================================
// Additional Passkey-specific Types
// ============================================================================

/**
 * Options for the high-level registerPasskey function
 */
export interface RegisterPasskeyOptions {
  /** Optional friendly name for the passkey (e.g., "MacBook Pro", "iPhone 15") */
  deviceName?: string;

  /**
   * Preferred authenticator attachment
   * - 'platform': Built-in authenticator (Touch ID, Face ID, Windows Hello)
   * - 'cross-platform': External authenticator (USB key, phone via QR)
   * If not specified, the browser will prompt for all available options
   */
  authenticatorAttachment?: 'platform' | 'cross-platform';

  /**
   * AbortController signal for cancelling the operation
   * Useful for implementing timeout or cancel buttons
   */
  signal?: AbortSignal;
}

/**
 * Options for the high-level authenticateWithPasskey function
 */
export interface AuthenticateWithPasskeyOptions {
  /**
   * User's email address for non-discoverable credential flow
   * If provided, only passkeys registered to this email will be allowed
   * If omitted, uses discoverable credential flow (passwordless)
   */
  email?: string;

  /**
   * AbortController signal for cancelling the operation
   */
  signal?: AbortSignal;

  /**
   * Enable conditional UI mode (autofill)
   * When true, the credential picker appears in password autofill dropdown
   * Requires an input with autocomplete="username webauthn"
   */
  conditional?: boolean;
}

/**
 * Result of a successful passkey registration
 */
export interface PasskeyRegistrationResult {
  /** The newly registered passkey credential info */
  passkey: import('../auth/types').PasskeyCredential;
}

/**
 * Result of a successful passkey authentication
 */
export interface PasskeyAuthenticationResult {
  /** The authenticated user's display information */
  user: import('../auth/types').UserDisplayInfo;
  /** Token expiration time in seconds */
  expiresIn: number;
}

/**
 * Passkey capability information
 * Returned by checkPasskeySupport()
 */
export interface PasskeyCapabilities {
  /** Whether WebAuthn is supported in this browser */
  isSupported: boolean;

  /** Whether platform authenticator (Touch ID, Face ID, Windows Hello) is available */
  hasPlatformAuthenticator: boolean;

  /** Whether conditional UI (autofill) is supported */
  hasConditionalUI: boolean;
}

// ============================================================================
// Passkey Signup Types - Added 2026-01-22
// ============================================================================

/**
 * Options for the high-level signupWithPasskey function
 */
export interface SignupWithPasskeyOptions {
  /** User's email address */
  email: string;

  /** User's display name */
  name: string;

  /** Optional friendly name for the passkey (e.g., "MacBook Pro", "iPhone 15") */
  deviceName?: string;

  /**
   * Preferred authenticator attachment
   * - 'platform': Built-in authenticator (Touch ID, Face ID, Windows Hello)
   * - 'cross-platform': External authenticator (USB key, phone via QR)
   */
  authenticatorAttachment?: 'platform' | 'cross-platform';

  /**
   * AbortController signal for cancelling the operation
   */
  signal?: AbortSignal;
}

/**
 * Result of a successful passkey signup
 */
export interface PasskeySignupResult {
  /** The newly created user's display information */
  user: import('../auth/types').UserDisplayInfo;
  /** The registered passkey credential info */
  passkey: import('../auth/types').PasskeyCredential;
  /** Token expiration time in seconds */
  expiresIn: number;
}
