/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2026-01-22
 *
 * Passkey (WebAuthn) Utility Functions
 * Provides encoding/decoding utilities and browser compatibility checks.
 */

// ============================================================================
// Base64URL Encoding/Decoding Utilities
// WebAuthn uses ArrayBuffer/Uint8Array but network transmission requires Base64URL
// ============================================================================

/**
 * Convert an ArrayBuffer to a Base64URL-encoded string
 * Used when sending WebAuthn credential response to the server
 *
 * @param buffer - ArrayBuffer from WebAuthn API
 * @returns Base64URL-encoded string (URL-safe, no padding)
 *
 * @example
 * ```typescript
 * const credential = await navigator.credentials.create(options);
 * const rawIdBase64 = arrayBufferToBase64URL(credential.rawId);
 * ```
 */
export function arrayBufferToBase64URL(buffer: ArrayBuffer): string {
  const bytes = new Uint8Array(buffer);
  let binary = '';
  for (let i = 0; i < bytes.byteLength; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  // Convert to Base64 then make URL-safe
  return btoa(binary)
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');
}

/**
 * Convert a Base64URL-encoded string to an ArrayBuffer
 * Used when receiving WebAuthn options from the server
 *
 * @param base64url - Base64URL-encoded string
 * @returns ArrayBuffer suitable for WebAuthn API
 *
 * @example
 * ```typescript
 * const options = await startPasskeyRegistration();
 * options.challenge = base64URLToArrayBuffer(options.challenge as unknown as string);
 * ```
 */
export function base64URLToArrayBuffer(base64url: string): ArrayBuffer {
  // Add padding if needed
  let base64 = base64url.replace(/-/g, '+').replace(/_/g, '/');
  while (base64.length % 4) {
    base64 += '=';
  }

  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes.buffer;
}

// ============================================================================
// Browser Compatibility Detection
// ============================================================================

/**
 * Check if the browser supports WebAuthn (Passkey)
 *
 * @returns true if WebAuthn is available in the current browser
 *
 * @example
 * ```typescript
 * if (!isWebAuthnSupported()) {
 *   showMessage('Your browser does not support passkeys');
 *   return;
 * }
 * ```
 */
export function isWebAuthnSupported(): boolean {
  return (
    typeof window !== 'undefined' &&
    typeof window.PublicKeyCredential !== 'undefined' &&
    typeof navigator.credentials !== 'undefined'
  );
}

/**
 * Check if the browser supports platform authenticators (Touch ID, Face ID, Windows Hello)
 *
 * @returns Promise resolving to true if platform authenticator is available
 *
 * @example
 * ```typescript
 * const hasBiometric = await isPlatformAuthenticatorAvailable();
 * if (hasBiometric) {
 *   showOption('Use Touch ID / Face ID');
 * }
 * ```
 */
export async function isPlatformAuthenticatorAvailable(): Promise<boolean> {
  if (!isWebAuthnSupported()) {
    return false;
  }

  try {
    return await PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable();
  } catch {
    return false;
  }
}

/**
 * Check if the browser supports conditional UI (autofill passkey)
 * This allows passkeys to appear in the password autofill dropdown
 *
 * @returns Promise resolving to true if conditional UI is supported
 *
 * @example
 * ```typescript
 * const hasConditionalUI = await isConditionalUISupported();
 * if (hasConditionalUI) {
 *   // Enable webauthn attribute on input field
 *   input.autocomplete = 'username webauthn';
 * }
 * ```
 */
export async function isConditionalUISupported(): Promise<boolean> {
  if (!isWebAuthnSupported()) {
    return false;
  }

  try {
    if (typeof PublicKeyCredential.isConditionalMediationAvailable === 'function') {
      return await PublicKeyCredential.isConditionalMediationAvailable();
    }
    return false;
  } catch {
    return false;
  }
}

// ============================================================================
// Credential Parsing Utilities
// ============================================================================

/**
 * Parse the authenticator attachment type from a credential
 * Helps determine if the passkey is platform-bound (Touch ID, etc.) or cross-platform (USB key)
 *
 * @param credential - The PublicKeyCredential from navigator.credentials.create/get
 * @returns 'platform' | 'cross-platform' | undefined
 */
export function getAuthenticatorAttachment(
  credential: PublicKeyCredential
): 'platform' | 'cross-platform' | undefined {
  return credential.authenticatorAttachment as 'platform' | 'cross-platform' | undefined;
}

/**
 * Get available transports from a credential response
 * Used to store transport hints for future authentication
 *
 * @param response - The AuthenticatorAttestationResponse from registration
 * @returns Array of transport strings or empty array
 */
export function getTransports(
  response: AuthenticatorAttestationResponse
): AuthenticatorTransport[] {
  if (typeof response.getTransports === 'function') {
    return response.getTransports() as AuthenticatorTransport[];
  }
  return [];
}

// ============================================================================
// Error Handling
// ============================================================================

/**
 * Passkey operation error types
 */
export type PasskeyErrorType =
  | 'not_supported'
  | 'user_cancelled'
  | 'timeout'
  | 'invalid_state'
  | 'not_allowed'
  | 'security_error'
  | 'unknown';

/**
 * Parse WebAuthn errors into user-friendly error types
 *
 * @param error - The error thrown by navigator.credentials
 * @returns Structured error information
 *
 * @example
 * ```typescript
 * try {
 *   await registerPasskey();
 * } catch (error) {
 *   const { type, message } = parsePasskeyError(error);
 *   if (type === 'user_cancelled') {
 *     // User closed the dialog, no action needed
 *     return;
 *   }
 *   showError(message);
 * }
 * ```
 */
export function parsePasskeyError(error: unknown): {
  type: PasskeyErrorType;
  message: string;
  originalError: unknown;
} {
  if (error instanceof DOMException) {
    switch (error.name) {
      case 'NotSupportedError':
        return {
          type: 'not_supported',
          message: 'This browser or device does not support passkeys',
          originalError: error,
        };
      case 'NotAllowedError':
        // User cancelled or denied the operation
        return {
          type: 'user_cancelled',
          message: 'The operation was cancelled',
          originalError: error,
        };
      case 'AbortError':
        return {
          type: 'timeout',
          message: 'The operation timed out',
          originalError: error,
        };
      case 'InvalidStateError':
        return {
          type: 'invalid_state',
          message: 'This passkey is already registered on this device',
          originalError: error,
        };
      case 'SecurityError':
        return {
          type: 'security_error',
          message: 'The operation was blocked for security reasons',
          originalError: error,
        };
      default:
        return {
          type: 'unknown',
          message: error.message || 'An unknown error occurred',
          originalError: error,
        };
    }
  }

  return {
    type: 'unknown',
    message: error instanceof Error ? error.message : 'An unknown error occurred',
    originalError: error,
  };
}
