/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend - internal/interfaces/http/handlers/profilehandler.go
 * Last updated: 2026-01-22
 *
 * Note: Passkey management APIs are in user/client.ts (listPasskeys, deletePasskey)
 * Import from '@/api/passkey' for high-level passkey API.
 */

import { apiClient } from '@/shared/lib/axios';
import type { APIResponse } from '@/shared/types/api.types';
import type { UpdateProfileRequest, ChangePasswordRequest, ProfileResponse } from './types';

/**
 * Update current user profile
 * PATCH /users/me
 */
export const updateProfile = async (data: UpdateProfileRequest): Promise<ProfileResponse> => {
  const response = await apiClient.patch<APIResponse<ProfileResponse>>('/users/me', data);
  return response.data.data;
};

/**
 * Change password for current user
 * PUT /users/me/password
 */
export const changePassword = async (data: ChangePasswordRequest): Promise<void> => {
  await apiClient.put('/users/me/password', data);
};
