/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend - internal/application/user/dto/dto.go
 */

import type { UserResponse } from '../user/types';

/**
 * Update profile request
 * PATCH /users/me
 */
export interface UpdateProfileRequest {
  name?: string;
  email?: string;
}

/**
 * Change password request
 * PUT /users/me/password
 */
export interface ChangePasswordRequest {
  oldPassword: string;
  newPassword: string;
  logoutAllDevices?: boolean;
}

/** Profile response is the same as UserResponse */
export type ProfileResponse = UserResponse;
