/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2025-12-19
 */

import { apiClient } from '@/shared/lib/axios';
import type { APIResponse } from '@/shared/types/api.types';
import type {
  RegisterRequest,
  RegisterResponse,
  LoginRequest,
  LoginResponse,
  VerifyEmailRequest,
  ForgotPasswordRequest,
  ResetPasswordRequest,
  RefreshTokenResponse,
  UserDisplayInfo,
} from './types';

/**
 * Register a new user account
 * POST /auth/register
 */
export async function register(data: RegisterRequest): Promise<RegisterResponse> {
  const response = await apiClient.post<APIResponse<RegisterResponse>>('/auth/register', data);
  return response.data.data;
}

/**
 * Login with email and password
 * POST /auth/login
 */
export async function login(data: LoginRequest): Promise<LoginResponse> {
  const response = await apiClient.post<APIResponse<LoginResponse>>('/auth/login', data);
  return response.data.data;
}

/**
 * Verify email address with token
 * POST /auth/verify-email
 */
export async function verifyEmail(data: VerifyEmailRequest): Promise<void> {
  await apiClient.post<APIResponse<null>>('/auth/verify-email', data);
}

/**
 * Request password reset email
 * POST /auth/forgot-password
 */
export async function forgotPassword(data: ForgotPasswordRequest): Promise<void> {
  await apiClient.post<APIResponse<null>>('/auth/forgot-password', data);
}

/**
 * Reset password with token
 * POST /auth/reset-password
 */
export async function resetPassword(data: ResetPasswordRequest): Promise<void> {
  await apiClient.post<APIResponse<null>>('/auth/reset-password', data);
}

/**
 * Initiate OAuth login flow
 * GET /auth/oauth/:provider
 */
export function getOAuthUrl(provider: 'google' | 'github'): string {
  return `/auth/oauth/${provider}`;
}

/**
 * Refresh access token using refresh token cookie
 * POST /auth/refresh
 */
export async function refreshToken(): Promise<RefreshTokenResponse> {
  const response = await apiClient.post<APIResponse<RefreshTokenResponse>>('/auth/refresh');
  return response.data.data;
}

/**
 * Logout current user session
 * POST /auth/logout
 */
export async function logout(): Promise<void> {
  await apiClient.post<APIResponse<null>>('/auth/logout');
}

/**
 * Get current authenticated user info
 * GET /auth/me
 */
export async function getCurrentUser(): Promise<UserDisplayInfo> {
  const response = await apiClient.get<APIResponse<UserDisplayInfo>>('/auth/me');
  return response.data.data;
}
