/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2026-01-30
 */

import { apiClient } from '@/shared/lib/axios';
import type { APIResponse } from '@/shared/types/api.types';
import type {
  RegisterRequest,
  RegisterResponse,
  LoginRequest,
  LoginResponse,
  VerifyEmailRequest,
  ForgotPasswordRequest,
  ResetPasswordRequest,
  RefreshTokenResponse,
  UserDisplayInfo,
  VersionResponse,
  StartPasskeyRegistrationRequest,
  StartPasskeyAuthenticationRequest,
  FinishPasskeyRegistrationRequest,
  FinishPasskeyAuthenticationRequest,
  PasskeyRegistrationResponse,
  PasskeyLoginResponse,
  StartPasskeySignupRequest,
  StartPasskeySignupResponse,
  FinishPasskeySignupRequest,
  PasskeySignupResponse,
} from './types';

/**
 * Register a new user account
 * POST /auth/register
 *
 * Updated 2026-01-30: Response now includes requiresEmailVerification field
 * to indicate whether email verification is required (SMTP configured)
 */
export async function register(data: RegisterRequest): Promise<RegisterResponse> {
  const response = await apiClient.post<APIResponse<RegisterResponse>>('/auth/register', data);
  return response.data.data;
}

/**
 * Login with email and password
 * POST /auth/login
 */
export async function login(data: LoginRequest): Promise<LoginResponse> {
  const response = await apiClient.post<APIResponse<LoginResponse>>('/auth/login', data);
  return response.data.data;
}

/**
 * Verify email address with token
 * POST /auth/verify-email
 */
export async function verifyEmail(data: VerifyEmailRequest): Promise<void> {
  await apiClient.post<APIResponse<null>>('/auth/verify-email', data);
}

/**
 * Request password reset email
 * POST /auth/forgot-password
 */
export async function forgotPassword(data: ForgotPasswordRequest): Promise<void> {
  await apiClient.post<APIResponse<null>>('/auth/forgot-password', data);
}

/**
 * Reset password with token
 * POST /auth/reset-password
 */
export async function resetPassword(data: ResetPasswordRequest): Promise<void> {
  await apiClient.post<APIResponse<null>>('/auth/reset-password', data);
}

/**
 * Initiate OAuth login flow
 * GET /auth/oauth/:provider
 */
export function getOAuthUrl(provider: 'google' | 'github'): string {
  return `/auth/oauth/${provider}`;
}

/**
 * Refresh access token using refresh token cookie
 * POST /auth/refresh
 */
export async function refreshToken(): Promise<RefreshTokenResponse> {
  const response = await apiClient.post<APIResponse<RefreshTokenResponse>>('/auth/refresh');
  return response.data.data;
}

/**
 * Logout current user session
 * POST /auth/logout
 */
export async function logout(): Promise<void> {
  await apiClient.post<APIResponse<null>>('/auth/logout');
}

/**
 * Get current authenticated user info
 * GET /auth/me
 * Updated 2025-01-14: serverVersion moved to GET /version
 */
export async function getCurrentUser(): Promise<UserDisplayInfo> {
  const response = await apiClient.get<APIResponse<UserDisplayInfo>>('/auth/me');
  return response.data.data;
}

/**
 * Get server version
 * GET /version
 * Added 2025-01-14: Public endpoint, no authentication required
 */
export async function getVersion(): Promise<VersionResponse> {
  const response = await apiClient.get<VersionResponse>('/version');
  return response.data;
}

// ============================================================================
// Passkey (WebAuthn) Authentication - Added 2025-01-22
// ============================================================================

/**
 * Start passkey registration ceremony
 * POST /auth/passkey/register/start
 * @requires Authentication
 *
 * Returns WebAuthn CredentialCreationOptions to be passed to navigator.credentials.create()
 *
 * @param data - Optional registration data (device name)
 */
export async function startPasskeyRegistration(
  data?: StartPasskeyRegistrationRequest
): Promise<PublicKeyCredentialCreationOptions> {
  const response = await apiClient.post<{ publicKey: PublicKeyCredentialCreationOptions }>(
    '/auth/passkey/register/start',
    data
  );
  return response.data.publicKey;
}

/**
 * Finish passkey registration ceremony
 * POST /auth/passkey/register/finish
 * @requires Authentication
 *
 * Completes registration and stores the credential
 */
export async function finishPasskeyRegistration(
  data: FinishPasskeyRegistrationRequest
): Promise<PasskeyRegistrationResponse> {
  const response = await apiClient.post<APIResponse<PasskeyRegistrationResponse>>(
    '/auth/passkey/register/finish',
    data
  );
  return response.data.data;
}

/**
 * Start passkey authentication ceremony
 * POST /auth/passkey/login/start
 *
 * Returns WebAuthn CredentialRequestOptions to be passed to navigator.credentials.get()
 * If email is provided, only credentials for that user will be allowed.
 * If email is empty, discoverable credential flow (passwordless) will be used.
 */
export async function startPasskeyAuthentication(
  data?: StartPasskeyAuthenticationRequest
): Promise<PublicKeyCredentialRequestOptions> {
  const response = await apiClient.post<{ publicKey: PublicKeyCredentialRequestOptions }>(
    '/auth/passkey/login/start',
    data
  );
  return response.data.publicKey;
}

/**
 * Finish passkey authentication ceremony
 * POST /auth/passkey/login/finish
 *
 * Completes authentication and creates a session
 */
export async function finishPasskeyAuthentication(
  data: FinishPasskeyAuthenticationRequest
): Promise<PasskeyLoginResponse> {
  const response = await apiClient.post<APIResponse<PasskeyLoginResponse>>(
    '/auth/passkey/login/finish',
    data
  );
  return response.data.data;
}

// ============================================================================
// Passkey Signup (New User Registration) - Added 2026-01-22
// ============================================================================

/**
 * Start passkey signup ceremony for new user registration
 * POST /auth/passkey/signup/start
 *
 * Initiates passwordless registration flow using passkey.
 * Returns WebAuthn CredentialCreationOptions and a session token.
 *
 * Note: This function extracts publicKey from the raw response for consistency
 * with startPasskeyRegistration, which also returns PublicKeyCredentialCreationOptions directly.
 *
 * @param data - User's email and name
 */
export async function startPasskeySignup(
  data: StartPasskeySignupRequest
): Promise<StartPasskeySignupResponse> {
  // Raw response format: { options: { publicKey: {...} }, session_token: "..." }
  const response = await apiClient.post<{
    options: { publicKey: PublicKeyCredentialCreationOptions };
    sessionToken: string;
  }>('/auth/passkey/signup/start', data);

  // Transform to match StartPasskeySignupResponse interface
  // Extract publicKey for consistency with startPasskeyRegistration
  return {
    options: response.data.options.publicKey,
    sessionToken: response.data.sessionToken,
  };
}

/**
 * Finish passkey signup ceremony
 * POST /auth/passkey/signup/finish
 *
 * Completes registration, creates user account and session.
 * User is immediately logged in after successful registration.
 */
export async function finishPasskeySignup(
  data: FinishPasskeySignupRequest
): Promise<PasskeySignupResponse> {
  const response = await apiClient.post<APIResponse<PasskeySignupResponse>>(
    '/auth/passkey/signup/finish',
    data
  );
  return response.data.data;
}
