/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2026-01-30
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 */

/** Request to register a new user */
export interface RegisterRequest {
  email: string;
  name: string;
  password: string;
}

/** Request to login with email and password */
export interface LoginRequest {
  email: string;
  password: string;
  rememberMe?: boolean;
}

/** Request to verify email with token */
export interface VerifyEmailRequest {
  token: string;
}

/** Request to initiate password reset */
export interface ForgotPasswordRequest {
  email: string;
}

/** Request to reset password with token */
export interface ResetPasswordRequest {
  token: string;
  password: string;
}

/** Request to refresh access token */
export interface RefreshTokenRequest {
  refreshToken?: string;
}

/** Response after successful login */
export interface LoginResponse {
  user: UserDisplayInfo;
  expiresIn: number;
}

/**
 * Response after successful registration
 * Updated 2026-01-30: Added requiresEmailVerification field
 */
export interface RegisterResponse {
  // Updated 2025-12-19: Changed from number to string (Stripe-style ID: usr_xxx)
  userId: string;
  email: string;
  /**
   * Whether email verification is required
   * When true: SMTP is configured, user should be redirected to verification pending page
   * When false: SMTP is not configured, user can proceed to login directly
   * Added 2026-01-30
   */
  requiresEmailVerification: boolean;
}

/** Response after token refresh */
export interface RefreshTokenResponse {
  expiresIn: number;
}

/** User display information */
export interface UserDisplayInfo {
  // Updated 2025-12-19: Changed from number to string (Stripe-style ID: usr_xxx)
  id: string;
  email: string;
  name: string;
  displayName: string;
  initials: string;
  role: string;
  status: string;
  // Updated 2025-01-14: Removed serverVersion field - now available via GET /version
}

/** Response from GET /version endpoint - Added 2025-01-14 */
export interface VersionResponse {
  version: string;
}

// ============================================================================
// Passkey (WebAuthn) Types - Added 2025-01-22
// These types are the single source of truth for passkey-related operations.
// The user module imports these types for passkey management endpoints.
// ============================================================================

/**
 * Request to start passkey registration
 * POST /auth/passkey/register/start
 */
export interface StartPasskeyRegistrationRequest {
  /** Optional friendly name for the passkey */
  deviceName?: string;
}

/**
 * Request to start passkey authentication
 * POST /auth/passkey/login/start
 */
export interface StartPasskeyAuthenticationRequest {
  /** Email is optional - if provided, only credentials for that user will be allowed. If empty, discoverable credential flow will be used */
  email?: string;
}

/**
 * Authenticator attestation response from browser (for registration)
 */
export interface AuthenticatorAttestationResponse {
  clientDataJSON: string;
  attestationObject: string;
  transports?: string[];
}

/**
 * Request to finish passkey registration
 * POST /auth/passkey/register/finish
 */
export interface FinishPasskeyRegistrationRequest {
  id: string;
  rawId: string;
  type: string;
  response: AuthenticatorAttestationResponse;
  authenticatorAttachment?: string;
  clientExtensionResults?: Record<string, unknown>;
  /** Optional friendly name for the passkey */
  deviceName?: string;
}

/**
 * Authenticator assertion response from browser (for authentication)
 */
export interface AuthenticatorAssertionResponse {
  clientDataJSON: string;
  authenticatorData: string;
  signature: string;
  userHandle?: string;
}

/**
 * Request to finish passkey authentication
 * POST /auth/passkey/login/finish
 */
export interface FinishPasskeyAuthenticationRequest {
  id: string;
  rawId: string;
  type: string;
  response: AuthenticatorAssertionResponse;
  authenticatorAttachment?: string;
  clientExtensionResults?: Record<string, unknown>;
}

/**
 * Passkey credential display information
 * Returned by list and registration endpoints
 */
export interface PasskeyCredential {
  /** Passkey ID (pk_xxx format) */
  id: string;
  /** Friendly name for the passkey */
  deviceName: string;
  /** Transport methods supported (usb, nfc, ble, internal, etc.) */
  transports: string[];
  /** Last time this passkey was used */
  lastUsedAt: string | null;
  /** When the passkey was registered */
  createdAt: string;
}

/**
 * Response after successful passkey registration
 * POST /auth/passkey/register/finish
 */
export interface PasskeyRegistrationResponse {
  passkey: PasskeyCredential;
}

/**
 * Response after successful passkey login
 * POST /auth/passkey/login/finish
 */
export interface PasskeyLoginResponse {
  user: UserDisplayInfo;
  expiresIn: number;
}

/**
 * Response listing user's passkeys
 * GET /users/me/passkeys
 */
export interface ListPasskeysResponse {
  passkeys: PasskeyCredential[];
}

// ============================================================================
// Passkey Signup Types - Added 2026-01-22
// These types support passkey-based user registration without password.
// ============================================================================

/**
 * Request to start passkey signup (new user registration)
 * POST /auth/passkey/signup/start
 */
export interface StartPasskeySignupRequest {
  /** User's email address */
  email: string;
  /** User's display name */
  name: string;
}

/**
 * Response from starting passkey signup
 * POST /auth/passkey/signup/start
 *
 * Note: This is the transformed response - the client function extracts
 * publicKey from the raw API response for consistency with other passkey APIs.
 */
export interface StartPasskeySignupResponse {
  /** WebAuthn credential creation options (extracted from response.options.publicKey) */
  options: PublicKeyCredentialCreationOptions;
  /** Session token to be used in finish request */
  sessionToken: string;
}

/**
 * Request to finish passkey signup
 * POST /auth/passkey/signup/finish
 */
export interface FinishPasskeySignupRequest {
  /** Session token from start signup response */
  sessionToken: string;
  /** Credential ID */
  id: string;
  /** Raw credential ID (base64url encoded) */
  rawId: string;
  /** Credential type (always "public-key") */
  type: string;
  /** Authenticator attestation response */
  response: AuthenticatorAttestationResponse;
  /** Authenticator attachment type */
  authenticatorAttachment?: string;
  /** Client extension results */
  clientExtensionResults?: Record<string, unknown>;
  /** Optional friendly name for the passkey */
  deviceName?: string;
}

/**
 * Response after successful passkey signup
 * POST /auth/passkey/signup/finish
 */
export interface PasskeySignupResponse {
  /** The newly created user's display information */
  user: UserDisplayInfo;
  /** The registered passkey credential info */
  passkey: PasskeyCredential;
  /** Token expiration time in seconds */
  expiresIn: number;
}
