/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2025-12-19
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 */

/** Request to register a new user */
export interface RegisterRequest {
  email: string;
  name: string;
  password: string;
}

/** Request to login with email and password */
export interface LoginRequest {
  email: string;
  password: string;
  rememberMe?: boolean;
}

/** Request to verify email with token */
export interface VerifyEmailRequest {
  token: string;
}

/** Request to initiate password reset */
export interface ForgotPasswordRequest {
  email: string;
}

/** Request to reset password with token */
export interface ResetPasswordRequest {
  token: string;
  password: string;
}

/** Request to refresh access token */
export interface RefreshTokenRequest {
  refreshToken?: string;
}

/** Response after successful login */
export interface LoginResponse {
  user: UserDisplayInfo;
  expiresIn: number;
}

/** Response after successful registration */
export interface RegisterResponse {
  // Updated 2025-12-19: Changed from number to string (Stripe-style ID: usr_xxx)
  userId: string;
  email: string;
}

/** Response after token refresh */
export interface RefreshTokenResponse {
  expiresIn: number;
}

/** User display information */
export interface UserDisplayInfo {
  // Updated 2025-12-19: Changed from number to string (Stripe-style ID: usr_xxx)
  id: string;
  email: string;
  name: string;
  displayName: string;
  initials: string;
  role: string;
  status: string;
}
