/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 */

/** Request to register a new user */
export interface RegisterRequest {
  email: string;
  name: string;
  password: string;
}

/** Request to login with email and password */
export interface LoginRequest {
  email: string;
  password: string;
  rememberMe?: boolean;
}

/** Request to verify email with token */
export interface VerifyEmailRequest {
  token: string;
}

/** Request to initiate password reset */
export interface ForgotPasswordRequest {
  email: string;
}

/** Request to reset password with token */
export interface ResetPasswordRequest {
  token: string;
  password: string;
}

/** Request to refresh access token */
export interface RefreshTokenRequest {
  refreshToken?: string;
}

/** Response after successful login */
export interface LoginResponse {
  user: UserDisplayInfo;
  expiresIn: number;
}

/** Response after successful registration */
export interface RegisterResponse {
  userId: number;
  email: string;
}

/** Response after token refresh */
export interface RefreshTokenResponse {
  expiresIn: number;
}

/** User display information */
export interface UserDisplayInfo {
  id: number;
  email: string;
  name: string;
  displayName: string;
  initials: string;
  role: string;
  status: string;
  avatar?: string;
  emailVerified?: boolean;
  oauthProvider?: string;
  createdAt?: string;
  updatedAt?: string;
}

/** User type alias for compatibility */
export type User = UserDisplayInfo;

/** OAuth provider type */
export type OAuthProvider = 'google' | 'github';

/** OAuth callback message from popup */
export interface OAuthCallbackMessage {
  type: 'oauth-success' | 'oauth-error';
  user?: User;
  error?: string;
}
