/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2025-01-20
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 */

/**
 * Status types for external forward rules
 */
export type ExternalForwardStatus = 'enabled' | 'disabled';

/**
 * External forward rule entity
 * Updated 2025-01-20: Added nodeProtocol field for node protocol information
 */
export interface ExternalForwardRule {
  /** Rule ID (efr_xxx format) */
  id: string;
  /** Subscription ID (sub_xxx format) */
  subscriptionId: string;
  /** Node ID for direct routing (node_xxx format) */
  nodeId?: string;
  /** Rule name */
  name: string;
  /** Server address (IP or domain) */
  serverAddress: string;
  /** Listen port */
  listenPort: number;
  /** External source identifier */
  externalSource: string;
  /** External rule ID from the source */
  externalRuleId?: string;
  /** Rule status */
  status: ExternalForwardStatus;
  /** Sort order for display */
  sortOrder: number;
  /** Optional remark */
  remark?: string;
  /** Resource group SIDs (for subscription distribution) */
  groupIds?: string[];
  /** Node server address (populated when node is assigned) */
  nodeServerAddress?: string;
  /** Node public IPv4 address (populated when node is assigned) */
  nodePublicIpv4?: string;
  /** Node public IPv6 address (populated when node is assigned) */
  nodePublicIpv6?: string;
  /** Node protocol (populated when node is assigned) - Added 2025-01-20 */
  nodeProtocol?: string;
  /** Creation timestamp (ISO 8601) */
  createdAt: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
}

/**
 * Request to create an external forward rule
 * Updated 2025-01-19: Removed protocol fields
 */
export interface CreateExternalForwardRuleRequest {
  /** Rule name */
  name: string;
  /** Server address (IP or domain) */
  serverAddress: string;
  /** Listen port (1-65535) */
  listenPort: number;
  /** External source identifier */
  externalSource: string;
  /** External rule ID from the source */
  externalRuleId?: string;
  /** Node ID for direct routing (node_xxx format) */
  nodeId?: string;
  /** Optional remark */
  remark?: string;
  /** Sort order for display */
  sortOrder?: number;
}

/**
 * Request to update an external forward rule
 * Updated 2025-01-19: Removed protocol fields
 */
export interface UpdateExternalForwardRuleRequest {
  /** Rule name */
  name?: string;
  /** Server address (IP or domain) */
  serverAddress?: string;
  /** Listen port (1-65535) */
  listenPort?: number;
  /** Node ID for direct routing (node_xxx format), empty string to clear */
  nodeId?: string;
  /** Optional remark */
  remark?: string;
  /** Sort order for display */
  sortOrder?: number;
}

/**
 * Query parameters for listing external forward rules
 */
export interface ListExternalForwardRulesParams {
  /** Page number (default: 1) */
  page?: number;
  /** Page size (default: 20, max: 100) */
  pageSize?: number;
  /** Filter by status */
  status?: ExternalForwardStatus;
  /** Order by field */
  orderBy?: 'sort_order' | 'created_at' | 'updated_at' | 'name' | 'status';
  /** Sort order */
  order?: 'ASC' | 'DESC';
}
