/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2025-12-22
 *
 * Admin Traffic Statistics API Client
 * All endpoints require admin authentication.
 */

import { apiClient } from '@/shared/lib/axios';
import type { APIResponse, ListResponse } from '@/shared/types/api.types';
import type {
  TrafficStatsQueryParams,
  TrafficRankingParams,
  TrafficTrendParams,
  TrafficOverview,
  UserTrafficStatsItem,
  SubscriptionTrafficStatsItem,
  NodeTrafficStatsItem,
  TrafficRanking,
  TrafficTrend,
} from './types';

// ========== Traffic Statistics APIs (Admin only) ==========

/**
 * Get global traffic overview
 * GET /admin/traffic-stats/overview
 * @requires Authentication, Admin
 *
 * Returns platform-wide traffic statistics including total traffic,
 * active subscriptions, users, nodes, and forward rules count.
 *
 * @param params - Query parameters with time range
 * @returns Traffic overview statistics
 *
 * @example
 * ```typescript
 * const overview = await getTrafficOverview({
 *   from: '2025-01-01T00:00:00Z',
 *   to: '2025-01-31T23:59:59Z',
 * });
 * console.log(formatTrafficBytes(overview.totalTraffic));
 * ```
 */
export const getTrafficOverview = async (
  params: TrafficStatsQueryParams
): Promise<TrafficOverview> => {
  const response = await apiClient.get<APIResponse<TrafficOverview>>(
    '/admin/traffic-stats/overview',
    { params }
  );
  return response.data.data;
};

/**
 * Get traffic statistics by user
 * GET /admin/traffic-stats/users
 * @requires Authentication, Admin
 *
 * Returns paginated traffic statistics grouped by user.
 *
 * @param params - Query parameters with time range and pagination
 * @returns Paginated list of user traffic statistics
 *
 * @example
 * ```typescript
 * const userStats = await getUserTrafficStats({
 *   from: '2025-01-01T00:00:00Z',
 *   to: '2025-01-31T23:59:59Z',
 *   page: 1,
 *   pageSize: 20,
 * });
 * userStats.items.forEach(user => {
 *   console.log(`${user.userEmail}: ${formatTrafficBytes(user.total)}`);
 * });
 * ```
 */
export const getUserTrafficStats = async (
  params: TrafficStatsQueryParams
): Promise<ListResponse<UserTrafficStatsItem>> => {
  const response = await apiClient.get<APIResponse<ListResponse<UserTrafficStatsItem>>>(
    '/admin/traffic-stats/users',
    { params }
  );
  return response.data.data;
};

/**
 * Get traffic statistics by subscription
 * GET /admin/traffic-stats/subscriptions
 * @requires Authentication, Admin
 *
 * Returns paginated traffic statistics grouped by subscription.
 *
 * @param params - Query parameters with time range and pagination
 * @returns Paginated list of subscription traffic statistics
 *
 * @example
 * ```typescript
 * const subStats = await getSubscriptionTrafficStats({
 *   from: '2025-01-01T00:00:00Z',
 *   to: '2025-01-31T23:59:59Z',
 *   page: 1,
 *   pageSize: 20,
 * });
 * ```
 */
export const getSubscriptionTrafficStats = async (
  params: TrafficStatsQueryParams
): Promise<ListResponse<SubscriptionTrafficStatsItem>> => {
  const response = await apiClient.get<APIResponse<ListResponse<SubscriptionTrafficStatsItem>>>(
    '/admin/traffic-stats/subscriptions',
    { params }
  );
  return response.data.data;
};

/**
 * Get traffic statistics by node
 * GET /admin/traffic-stats/nodes
 * @requires Authentication, Admin
 *
 * Returns paginated traffic statistics grouped by node.
 *
 * @param params - Query parameters with time range and pagination
 * @returns Paginated list of node traffic statistics
 *
 * @example
 * ```typescript
 * const nodeStats = await getNodeTrafficStats({
 *   from: '2025-01-01T00:00:00Z',
 *   to: '2025-01-31T23:59:59Z',
 *   page: 1,
 *   pageSize: 20,
 * });
 * ```
 */
export const getNodeTrafficStats = async (
  params: TrafficStatsQueryParams
): Promise<ListResponse<NodeTrafficStatsItem>> => {
  const response = await apiClient.get<APIResponse<ListResponse<NodeTrafficStatsItem>>>(
    '/admin/traffic-stats/nodes',
    { params }
  );
  return response.data.data;
};

/**
 * Get user traffic ranking
 * GET /admin/traffic-stats/ranking/users
 * @requires Authentication, Admin
 *
 * Returns top N users by total traffic usage.
 *
 * @param params - Query parameters with time range and limit
 * @returns Traffic ranking response
 *
 * @example
 * ```typescript
 * const ranking = await getUserTrafficRanking({
 *   from: '2025-01-01T00:00:00Z',
 *   to: '2025-01-31T23:59:59Z',
 *   limit: 10,
 * });
 * ranking.items.forEach(item => {
 *   console.log(`#${item.rank} ${item.name}: ${formatTrafficBytes(item.total)}`);
 * });
 * ```
 */
export const getUserTrafficRanking = async (
  params: TrafficRankingParams
): Promise<TrafficRanking> => {
  const response = await apiClient.get<APIResponse<TrafficRanking>>(
    '/admin/traffic-stats/ranking/users',
    { params }
  );
  return response.data.data;
};

/**
 * Get subscription traffic ranking
 * GET /admin/traffic-stats/ranking/subscriptions
 * @requires Authentication, Admin
 *
 * Returns top N subscriptions by total traffic usage.
 *
 * @param params - Query parameters with time range and limit
 * @returns Traffic ranking response
 *
 * @example
 * ```typescript
 * const ranking = await getSubscriptionTrafficRanking({
 *   from: '2025-01-01T00:00:00Z',
 *   to: '2025-01-31T23:59:59Z',
 *   limit: 10,
 * });
 * ```
 */
export const getSubscriptionTrafficRanking = async (
  params: TrafficRankingParams
): Promise<TrafficRanking> => {
  const response = await apiClient.get<APIResponse<TrafficRanking>>(
    '/admin/traffic-stats/ranking/subscriptions',
    { params }
  );
  return response.data.data;
};

/**
 * Get traffic trend over time
 * GET /admin/traffic-stats/trend
 * @requires Authentication, Admin
 *
 * Returns traffic data grouped by time period (hour, day, or month).
 *
 * @param params - Query parameters with time range and granularity
 * @returns Traffic trend with time series data
 *
 * @example
 * ```typescript
 * const trend = await getTrafficTrend({
 *   from: '2025-01-01T00:00:00Z',
 *   to: '2025-01-31T23:59:59Z',
 *   granularity: 'day',
 * });
 * // Use with charting library
 * const chartData = trend.points.map(p => ({
 *   date: p.period,
 *   upload: p.upload,
 *   download: p.download,
 * }));
 * ```
 */
export const getTrafficTrend = async (
  params: TrafficTrendParams
): Promise<TrafficTrend> => {
  const response = await apiClient.get<APIResponse<TrafficTrend>>(
    '/admin/traffic-stats/trend',
    { params }
  );
  return response.data.data;
};
