/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2025-01-20
 *
 * Admin API - Traffic Statistics & Telegram Binding
 */

// Types - Traffic Statistics
export type {
  TrafficStatsQueryParams,
  TrafficRankingParams,
  TrafficTrendParams,
  TrafficOverview,
  UserTrafficStatsItem,
  SubscriptionTrafficStatsItem,
  NodeTrafficStatsItem,
  TrafficRankingItem,
  TrafficRanking,
  TrafficTrendPoint,
  TrafficTrend,
} from './types';

// Types - Admin Telegram Binding
export type {
  AdminTelegramBindingResponse,
  AdminBindingStatusResponse,
  UpdateAdminPreferencesRequest,
} from './types';

// Types - System Settings (Added 2025-01-06)
export type {
  SystemSettingResponse,
  CategorySettingsResponse,
  UpdateCategorySettingsRequest,
  TelegramConfigResponse,
  UpdateTelegramConfigRequest,
  TelegramTestResult,
} from './types';

// Utility functions
export { formatTrafficBytes, calculateTrafficRatio } from './types';

// API functions - Traffic Statistics
export {
  getTrafficOverview,
  getUserTrafficStats,
  getSubscriptionTrafficStats,
  getNodeTrafficStats,
  getUserTrafficRanking,
  getSubscriptionTrafficRanking,
  getTrafficTrend,
} from './client';

// API functions - Admin Telegram Binding
export {
  getAdminTelegramBindingStatus,
  unbindAdminTelegram,
  updateAdminTelegramPreferences,
} from './client';

// API functions - System Settings (Added 2025-01-06)
export {
  getCategorySettings,
  updateCategorySettings,
  getTelegramConfig,
  updateTelegramConfig,
  testTelegramConnection,
} from './client';

// Types - Admin Subscription Management (Added 2025-01-14)
export type { SuspendSubscriptionRequest } from './types';

// API functions - Admin Subscription Management (Added 2025-01-14)
export {
  suspendSubscription,
  unsuspendSubscription,
  resetSubscriptionUsage,
} from './client';

// Note: Admin External Forward Rules have been removed (2026-01-20)
// External forward rules are now part of the unified ForwardRule model with rule_type='external'
// Use the forward module's Admin APIs with ruleType='external' filter instead
