/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2025-12-22
 *
 * Admin API - Traffic Statistics
 */

// Types
export type {
  TrafficStatsQueryParams,
  TrafficRankingParams,
  TrafficTrendParams,
  TrafficOverview,
  UserTrafficStatsItem,
  SubscriptionTrafficStatsItem,
  NodeTrafficStatsItem,
  TrafficRankingItem,
  TrafficRanking,
  TrafficTrendPoint,
  TrafficTrend,
} from './types';

// Utility functions
export { formatTrafficBytes, calculateTrafficRatio } from './types';

// API functions
export {
  getTrafficOverview,
  getUserTrafficStats,
  getSubscriptionTrafficStats,
  getNodeTrafficStats,
  getUserTrafficRanking,
  getSubscriptionTrafficRanking,
  getTrafficTrend,
} from './client';
