/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2026-02-28
 *
 * Admin API - Traffic Statistics, Telegram Binding & System Settings
 */

// Types - Admin Dashboard (Added 2026-02-11)
export type {
  AdminDashboardResponse,
  DashboardUsersSection,
  DashboardSubscriptionsSection,
  DashboardNodesSection,
  DashboardForwardSection,
  DashboardTrafficSection,
} from './types';

// Types - Traffic Statistics
export type {
  TrafficStatsQueryParams,
  TrafficRankingParams,
  TrafficTrendParams,
  TrafficOverview,
  UserTrafficStatsItem,
  SubscriptionTrafficStatsItem,
  NodeTrafficStatsItem,
  TrafficRankingItem,
  TrafficRanking,
  TrafficTrendPoint,
  TrafficTrend,
} from './types';

// Types - Admin Telegram Binding
export type {
  AdminTelegramBindingResponse,
  AdminBindingStatusResponse,
  UpdateAdminPreferencesRequest,
} from './types';

// Types - System Settings (Added 2025-01-06)
export type {
  SystemSettingResponse,
  CategorySettingsResponse,
  UpdateCategorySettingsRequest,
  TelegramConfigResponse,
  UpdateTelegramConfigRequest,
  TelegramTestResult,
} from './types';

// Types - Config Source & System Settings (Added 2026-01-23)
export type {
  ConfigSource,
  SettingWithSource,
  SystemSettingsResponse,
  UpdateSystemSettingsRequest,
} from './types';

// Types - OAuth Settings (Added 2026-01-23)
export type {
  OAuthProviderSettings,
  OAuthSettingsResponse,
  UpdateOAuthProviderRequest,
  UpdateOAuthSettingsRequest,
} from './types';

// Types - Email Settings (Added 2026-01-23)
export type {
  EmailSettingsResponse,
  UpdateEmailSettingsRequest,
  EmailTestRequest,
  EmailTestResponse,
} from './types';

// Types - Setup Status (Added 2026-01-23)
export type { SetupStatusResponse } from './types';

// Utility functions
export { formatTrafficBytes, calculateTrafficRatio } from './types';

// API functions - Admin Dashboard (Added 2026-02-11)
export { getAdminDashboard } from './client';

// API functions - Traffic Statistics
export {
  getTrafficOverview,
  getUserTrafficStats,
  getSubscriptionTrafficStats,
  getNodeTrafficStats,
  getUserTrafficRanking,
  getSubscriptionTrafficRanking,
  getTrafficTrend,
} from './client';

// API functions - Admin Telegram Binding
export {
  getAdminTelegramBindingStatus,
  unbindAdminTelegram,
  updateAdminTelegramPreferences,
} from './client';

// API functions - System Settings (Added 2025-01-06)
export {
  getCategorySettings,
  updateCategorySettings,
  getTelegramConfig,
  updateTelegramConfig,
  testTelegramConnection,
} from './client';

// API functions - System/OAuth/Email Settings (Added 2026-01-23)
export {
  getSystemSettings,
  updateSystemSettings,
  getOAuthSettings,
  updateOAuthSettings,
  getEmailSettings,
  updateEmailSettings,
  testEmailConnection,
  getSetupStatus,
} from './client';

// Types - Admin Subscription Management (Added 2025-01-14, Updated 2026-02-28)
export type {
  SubscriptionStatus,
  BillingCycle,
  AdminSubscriptionListParams,
  SubscriptionUser,
  PricingOption,
  SubscriptionPlanDTO,
  AdminSubscriptionDTO,
  SubscriptionTokenDTO,
  AdminCreateSubscriptionRequest,
  AdminCreateSubscriptionResponse,
  AdminUpdateSubscriptionRequest,
  SuspendSubscriptionRequest,
  RenewSubscriptionRequest,
  ChangePlanRequest,
} from './types';

// API functions - Admin Subscription Management (Added 2025-01-14, Updated 2026-02-28)
export {
  listAdminSubscriptions,
  getAdminSubscription,
  createAdminSubscription,
  updateAdminSubscription,
  deleteAdminSubscription,
  suspendSubscription,
  unsuspendSubscription,
  resetSubscriptionUsage,
  renewSubscription,
  changeSubscriptionPlan,
} from './client';

// Note: Admin External Forward Rules have been removed (2026-01-20)
// External forward rules are now part of the unified ForwardRule model with rule_type='external'
// Use the forward module's Admin APIs with ruleType='external' filter instead
