/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2026-03-10
 *
 * Recent changes:
 * - 2026-03-10: Added SubscriptionStatusCounts, AdminSubscriptionListResponse, includeCounts param
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 *
 * Admin Traffic Statistics API Types
 * These endpoints require admin authentication.
 */

// ========== Request Types ==========

/**
 * Common query parameters for traffic statistics endpoints
 */
export interface TrafficStatsQueryParams {
  /** Start date in YYYY-MM-DD format (e.g., "2025-01-01") */
  from: string;
  /** End date in YYYY-MM-DD format (e.g., "2025-01-31") */
  to: string;
  /** Optional: Filter by resource type ("node" or "forward_rule") */
  resourceType?: string;
  /** Page number (default: 1) */
  page?: number;
  /** Page size (default: 20, max: 100) */
  pageSize?: number;
}

/**
 * Query parameters for traffic ranking endpoints
 */
export interface TrafficRankingParams {
  /** Start date in YYYY-MM-DD format (e.g., "2025-01-01") */
  from: string;
  /** End date in YYYY-MM-DD format (e.g., "2025-01-31") */
  to: string;
  /** Optional: Filter by resource type ("node" or "forward_rule") */
  resourceType?: string;
  /** Number of top items to return (default: 10, max: 100) */
  limit?: number;
}

/**
 * Query parameters for traffic trend endpoint
 */
export interface TrafficTrendParams {
  /** Start date in YYYY-MM-DD format (e.g., "2025-01-01") */
  from: string;
  /** End date in YYYY-MM-DD format (e.g., "2025-01-31") */
  to: string;
  /** Optional: Filter by resource type ("node" or "forward_rule") */
  resourceType?: string;
  /** Time granularity: "hour", "day", or "month" */
  granularity: 'hour' | 'day' | 'month';
}

// ========== Response Types ==========

/**
 * Global traffic overview response
 * Provides platform-wide statistics for the specified time range
 */
export interface TrafficOverview {
  /** Total upload traffic in bytes */
  totalUpload: number;
  /** Total download traffic in bytes */
  totalDownload: number;
  /** Total traffic (upload + download) in bytes */
  totalTraffic: number;
}

/**
 * Traffic statistics for a single user
 */
export interface UserTrafficStatsItem {
  /** User Stripe-style ID (e.g., "usr_xK9mP2vL3nQ") */
  userId: string;
  /** User email address */
  userEmail: string;
  /** User display name */
  userName: string;
  /** Upload traffic in bytes */
  upload: number;
  /** Download traffic in bytes */
  download: number;
  /** Total traffic in bytes */
  total: number;
  /** Number of subscriptions this user has */
  subscriptionsCount: number;
}

/**
 * Traffic statistics for a single subscription
 */
export interface SubscriptionTrafficStatsItem {
  /** Subscription Stripe-style ID (e.g., "sub_xK9mP2vL3nQ") */
  subscriptionId: string;
  /** User Stripe-style ID (e.g., "usr_xK9mP2vL3nQ") */
  userId: string;
  /** User email address */
  userEmail: string;
  /** Subscription plan name */
  planName: string;
  /** Subscription status */
  status: string;
  /** Upload traffic in bytes */
  upload: number;
  /** Download traffic in bytes */
  download: number;
  /** Total traffic in bytes */
  total: number;
}

/**
 * Traffic statistics for a single node
 */
export interface NodeTrafficStatsItem {
  /** Node Stripe-style ID (e.g., "node_xK9mP2vL3nQ") */
  nodeId: string;
  /** Node name */
  nodeName: string;
  /** Node status */
  status: string;
  /** Upload traffic in bytes */
  upload: number;
  /** Download traffic in bytes */
  download: number;
  /** Total traffic in bytes */
  total: number;
  /** Number of online subscriptions on this node - Added 2026-02-26 */
  onlineSubscriptionCount: number;
}

/**
 * Single item in traffic ranking
 */
export interface TrafficRankingItem {
  /** Ranking position (1-based) */
  rank: number;
  /** Entity Stripe-style ID (user or subscription) */
  id: string;
  /** Entity name (user email or subscription name) */
  name: string;
  /** Upload traffic in bytes */
  upload: number;
  /** Download traffic in bytes */
  download: number;
  /** Total traffic in bytes */
  total: number;
}

/**
 * Traffic ranking response
 */
export interface TrafficRanking {
  /** List of ranked items */
  items: TrafficRankingItem[];
}

/**
 * Single data point in traffic trend
 */
export interface TrafficTrendPoint {
  /** Time period in ISO8601 format */
  period: string;
  /** Upload traffic in bytes for this period */
  upload: number;
  /** Download traffic in bytes for this period */
  download: number;
  /** Total traffic in bytes for this period */
  total: number;
}

/**
 * Traffic trend response
 */
export interface TrafficTrend {
  /** Time series data points */
  points: TrafficTrendPoint[];
  /** Time granularity used */
  granularity: 'hour' | 'day' | 'month';
}

// ========== Utility Functions ==========

/**
 * Format bytes to human readable string
 * @param bytes - Number of bytes
 * @returns Formatted string (e.g., "1.5 GB")
 */
export const formatTrafficBytes = (bytes: number): string => {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB', 'PB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(2))} ${sizes[i]}`;
};

/**
 * Calculate upload/download ratio
 * @param upload - Upload bytes
 * @param download - Download bytes
 * @returns Ratio string (e.g., "1:2.5")
 */
export const calculateTrafficRatio = (upload: number, download: number): string => {
  if (upload === 0 && download === 0) return '0:0';
  if (upload === 0) return '0:1';
  if (download === 0) return '1:0';
  const ratio = download / upload;
  return `1:${ratio.toFixed(1)}`;
};

// ========== Admin Dashboard Types (Added 2026-02-11) ==========

/**
 * Admin dashboard snapshot response
 * GET /admin/dashboard
 * Provides high-level operational metrics for the admin dashboard.
 */
export interface AdminDashboardResponse {
  /** User metrics */
  users: DashboardUsersSection;
  /** Subscription metrics */
  subscriptions: DashboardSubscriptionsSection;
  /** Node metrics */
  nodes: DashboardNodesSection;
  /** Forward metrics */
  forward: DashboardForwardSection;
  /** Today's traffic metrics */
  trafficToday: DashboardTrafficSection;
}

/**
 * User-related dashboard metrics
 */
export interface DashboardUsersSection {
  /** Total registered users */
  total: number;
  /** Users registered today */
  newToday: number;
  /** Users registered this week */
  newThisWeek: number;
}

/**
 * Subscription-related dashboard metrics
 */
export interface DashboardSubscriptionsSection {
  /** Active subscriptions count */
  active: number;
  /** Expired subscriptions count */
  expired: number;
  /** Suspended subscriptions count */
  suspended: number;
  /** Pending payment subscriptions count */
  pendingPayment: number;
  /** Subscriptions expiring within 7 days */
  expiringIn7Days: number;
}

/**
 * Node-related dashboard metrics
 */
export interface DashboardNodesSection {
  /** Total nodes count */
  total: number;
  /** Online nodes count */
  online: number;
  /** Offline nodes count */
  offline: number;
  /** Total online subscriptions across all nodes - Added 2026-02-26 */
  totalOnlineSubscriptions: number;
}

/**
 * Forward-related dashboard metrics
 */
export interface DashboardForwardSection {
  /** Total forward rules count */
  totalRules: number;
  /** Total forward agents count */
  totalAgents: number;
  /** Online forward agents count */
  onlineAgents: number;
}

/**
 * Today's traffic metrics
 */
export interface DashboardTrafficSection {
  /** Upload traffic in bytes */
  upload: number;
  /** Download traffic in bytes */
  download: number;
  /** Total traffic in bytes */
  total: number;
}

// ========== Admin Telegram Binding Types (Added 2025-01-06, Updated 2026-02-03) ==========

/**
 * Admin Telegram binding response
 * Represents an admin's Telegram notification binding
 * Updated: 2025-01-13 - Added schedule configuration fields
 * Updated: 2026-02-03 - Added resource expiring notification fields
 */
export interface AdminTelegramBindingResponse {
  /** Binding Stripe-style ID */
  sid: string;
  /** Telegram user ID */
  telegramUserId: number;
  /** Telegram username (optional) */
  telegramUsername?: string;
  /** Notify when nodes go offline */
  notifyNodeOffline: boolean;
  /** Notify when agents go offline */
  notifyAgentOffline: boolean;
  /** Notify when new users register */
  notifyNewUser: boolean;
  /** Notify on successful payments */
  notifyPaymentSuccess: boolean;
  /** Send daily business summary */
  notifyDailySummary: boolean;
  /** Send weekly business summary */
  notifyWeeklySummary: boolean;
  /** Offline detection threshold in minutes */
  offlineThresholdMinutes: number;
  /** Notify when resources are about to expire - Added 2026-02-03 */
  notifyResourceExpiring: boolean;
  /** Days before expiration to start notifying (1-30) - Added 2026-02-03 */
  resourceExpiringDays: number;
  /** Hour for daily summary (0-23 in business timezone) - Added 2025-01-13 */
  dailySummaryHour: number;
  /** Hour for weekly summary (0-23 in business timezone) - Added 2025-01-13 */
  weeklySummaryHour: number;
  /** Day for weekly summary (0=Sunday, 1=Monday...6=Saturday) - Added 2025-01-13 */
  weeklySummaryWeekday: number;
  /** Interval for offline checks in minutes (1-30) - Added 2025-01-13 */
  offlineCheckIntervalMinutes: number;
  /** Binding creation time */
  createdAt: string;
}

/**
 * Admin binding status response
 * Returns current binding status and verification info if not bound
 * Updated: 2026-02-05 - Added deepBindLink for Telegram deep linking
 */
export interface AdminBindingStatusResponse {
  /** Whether the admin has a Telegram binding */
  isBound: boolean;
  /** Binding details (present when isBound is true) */
  binding?: AdminTelegramBindingResponse;
  /** Verification code (present when isBound is false) */
  verifyCode?: string;
  /** Telegram bot link (e.g., https://t.me/botname) */
  botLink?: string;
  /** Deep link for one-click binding (e.g., https://t.me/botname?start=adminbind_CODE) - Added 2026-02-05 */
  deepBindLink?: string;
  /** Verification code expiration time (present when isBound is false) */
  expiresAt?: string;
}

/**
 * Request to update admin notification preferences
 * All fields are optional - only specified fields will be updated
 * Updated: 2025-01-13 - Added schedule configuration fields
 * Updated: 2026-02-03 - Added resource expiring notification fields
 */
export interface UpdateAdminPreferencesRequest {
  /** Notify when nodes go offline */
  notifyNodeOffline?: boolean;
  /** Notify when agents go offline */
  notifyAgentOffline?: boolean;
  /** Notify when new users register */
  notifyNewUser?: boolean;
  /** Notify on successful payments */
  notifyPaymentSuccess?: boolean;
  /** Send daily business summary */
  notifyDailySummary?: boolean;
  /** Send weekly business summary */
  notifyWeeklySummary?: boolean;
  /** Offline detection threshold in minutes (3-30) */
  offlineThresholdMinutes?: number;
  /** Notify when resources are about to expire - Added 2026-02-03 */
  notifyResourceExpiring?: boolean;
  /** Days before expiration to start notifying (1-30) - Added 2026-02-03 */
  resourceExpiringDays?: number;
  /** Hour for daily summary (0-23 in business timezone) - Added 2025-01-13 */
  dailySummaryHour?: number;
  /** Hour for weekly summary (0-23 in business timezone) - Added 2025-01-13 */
  weeklySummaryHour?: number;
  /** Day for weekly summary (0=Sunday, 1=Monday...6=Saturday) - Added 2025-01-13 */
  weeklySummaryWeekday?: number;
  /** Interval for offline checks in minutes (1-30) - Added 2025-01-13 */
  offlineCheckIntervalMinutes?: number;
}

// ========== Config Source Types (Added 2026-01-23) ==========

/**
 * Configuration source type
 * Indicates where a configuration value comes from
 */
export type ConfigSource = 'database' | 'environment' | 'default';

/**
 * Setting value with source information
 * Used to show where configuration values come from
 */
export interface SettingWithSource {
  /** Setting value */
  value: unknown;
  /** Where this value comes from */
  source: ConfigSource;
  /** Whether this value is sensitive (should be masked) */
  isSensitive: boolean;
  /** Whether this setting is read-only (e.g., from environment) */
  isReadOnly?: boolean;
}

// ========== System Settings Types (Added 2025-01-06, Updated 2026-01-23) ==========

/**
 * Single system setting response
 * Represents a configuration setting in the system
 */
export interface SystemSettingResponse {
  /** Setting Stripe-style ID */
  sid: string;
  /** Setting category (e.g., "telegram", "system") */
  category: string;
  /** Setting key within the category */
  key: string;
  /** Setting value (type varies based on valueType) */
  value: unknown;
  /** Value type: "string", "int", "bool", "json" */
  valueType: string;
  /** Setting description */
  description: string;
  /** Whether the value is sensitive (should be masked) */
  isSensitive: boolean;
  /** Last update time */
  updatedAt: string;
}

/**
 * System settings response (Added 2026-01-23)
 * Contains core system configuration values with source info
 */
export interface SystemSettingsResponse {
  /** API base URL setting */
  apiBaseUrl: SettingWithSource;
  /** Subscription base URL setting */
  subscriptionBaseUrl: SettingWithSource;
  /** Frontend URL setting */
  frontendUrl: SettingWithSource;
  /** Business timezone setting */
  timezone: SettingWithSource;
}

/**
 * Request to update system settings (Added 2026-01-23)
 * Note: apiBaseUrl is read-only and can only be configured via environment variable
 */
export interface UpdateSystemSettingsRequest {
  /** New subscription base URL */
  subscriptionBaseUrl?: string;
  /** New frontend URL */
  frontendUrl?: string;
}

/**
 * Category settings response
 * Contains all settings within a category
 */
export interface CategorySettingsResponse {
  /** Setting category */
  category: string;
  /** List of settings in this category */
  settings: SystemSettingResponse[];
}

/**
 * Request to batch update settings in a category
 */
export interface UpdateCategorySettingsRequest {
  /** Map of setting key to new value */
  settings: Record<string, unknown>;
}

/**
 * Telegram configuration response
 * Contains current Telegram bot configuration (with sensitive values masked)
 */
export interface TelegramConfigResponse {
  /** Whether Telegram notifications are enabled */
  enabled: boolean;
  /** Bot token (masked for display) */
  botToken: string;
  /** Webhook URL for receiving updates */
  webhookUrl: string;
  /** Webhook secret (masked for display) */
  webhookSecret: string;
  /** Telegram bot link (e.g., https://t.me/botname) */
  botLink?: string;
  /** Current mode: "webhook" or "polling" */
  mode: string;
}

/**
 * Request to update Telegram configuration
 * All fields are optional - only specified fields will be updated
 */
export interface UpdateTelegramConfigRequest {
  /** Enable/disable Telegram notifications */
  enabled?: boolean;
  /** New bot token */
  botToken?: string;
  /** New webhook URL */
  webhookUrl?: string;
  /** New webhook secret */
  webhookSecret?: string;
}

/**
 * Telegram connection test result
 */
export interface TelegramTestResult {
  /** Whether the connection test succeeded */
  success: boolean;
  /** Bot username (on success) */
  botUsername?: string;
  /** Error message (on failure) */
  error?: string;
}

// ========== OAuth Settings Types (Added 2026-01-23) ==========

/**
 * OAuth provider settings
 * Configuration for a single OAuth provider (Google, GitHub, etc.)
 */
export interface OAuthProviderSettings {
  /** Whether this OAuth provider is enabled */
  enabled: boolean;
  /** OAuth client ID */
  clientId: SettingWithSource;
  /** OAuth client secret (masked) */
  clientSecret: SettingWithSource;
  /** OAuth redirect URL */
  redirectUrl: SettingWithSource;
}

/**
 * OAuth settings response
 * Contains OAuth configuration for all providers
 */
export interface OAuthSettingsResponse {
  /** Google OAuth settings */
  google: OAuthProviderSettings;
  /** GitHub OAuth settings */
  github: OAuthProviderSettings;
}

/**
 * Request to update a single OAuth provider
 */
export interface UpdateOAuthProviderRequest {
  /** New client ID */
  clientId?: string;
  /** New client secret */
  clientSecret?: string;
  /** New redirect URL */
  redirectUrl?: string;
}

/**
 * Request to update OAuth settings
 * Update configuration for one or more OAuth providers
 */
export interface UpdateOAuthSettingsRequest {
  /** Google OAuth settings to update */
  google?: UpdateOAuthProviderRequest;
  /** GitHub OAuth settings to update */
  github?: UpdateOAuthProviderRequest;
}

// ========== Email Settings Types (Added 2026-01-23) ==========

/**
 * Email settings response
 * Contains SMTP configuration for sending emails
 */
export interface EmailSettingsResponse {
  /** SMTP server hostname */
  smtpHost: SettingWithSource;
  /** SMTP server port */
  smtpPort: SettingWithSource;
  /** SMTP username for authentication */
  smtpUser: SettingWithSource;
  /** SMTP password (masked) */
  smtpPassword: SettingWithSource;
  /** Email sender address */
  fromAddress: SettingWithSource;
  /** Email sender display name */
  fromName: SettingWithSource;
}

/**
 * Request to update email settings
 * All fields are optional - only provided fields will be updated
 */
export interface UpdateEmailSettingsRequest {
  /** New SMTP hostname */
  smtpHost?: string;
  /** New SMTP port */
  smtpPort?: number;
  /** New SMTP username */
  smtpUser?: string;
  /** New SMTP password */
  smtpPassword?: string;
  /** New from address */
  fromAddress?: string;
  /** New from name */
  fromName?: string;
}

/**
 * Request to test email connection
 * Sends a test email to verify SMTP configuration
 */
export interface EmailTestRequest {
  /** Email address to send test email to */
  recipientEmail: string;
}

/**
 * Email test result
 * Response from testing email connection
 */
export interface EmailTestResponse {
  /** Whether the test email was sent successfully */
  success: boolean;
  /** Error message if failed */
  error?: string;
}

// ========== Setup Status Types (Added 2026-01-23) ==========

/**
 * Setup status response
 * Used to check if first-time configuration is needed
 */
export interface SetupStatusResponse {
  /** Whether the system is configured */
  isConfigured: boolean;
  /** Whether setup wizard should be shown */
  requiresSetup: boolean;
  /** List of missing required settings */
  missingSettings: string[];
}

// ========== Admin Subscription Management Types (Added 2025-01-14, Updated 2026-04-29) ==========
// 2026-04-29: Added currentTrafficCycleStart/End and currentCycleUpload/DownloadBytes to AdminSubscriptionDTO
// 2026-02-28: Added dataUsedBytes, dataLimitBytes to AdminSubscriptionDTO; Added AdminUpdateSubscriptionRequest
// 2026-01-29: Removed apiRateLimit, maxUsers, maxProjects from SubscriptionPlanDTO

/**
 * Subscription status enum
 */
export type SubscriptionStatus =
  | 'inactive'
  | 'pending_payment'
  | 'trialing'
  | 'active'
  | 'past_due'
  | 'suspended'
  | 'cancelled'
  | 'expired';

/**
 * Billing cycle enum
 */
export type BillingCycle =
  | 'weekly'
  | 'monthly'
  | 'quarterly'
  | 'semi_annual'
  | 'yearly'
  | 'lifetime';

/**
 * Query parameters for listing admin subscriptions
 * GET /admin/subscriptions
 */
export interface AdminSubscriptionListParams {
  /** Page number (default: 1) */
  page?: number;
  /** Page size (default: 20, max: 100) */
  pageSize?: number;
  /** Filter by subscription status */
  status?: SubscriptionStatus;
  /** Filter by user ID (internal numeric ID) */
  userId?: number;
  /** Filter by plan ID (internal numeric ID) */
  planId?: number;
  /** Filter by billing cycle */
  billingCycle?: BillingCycle;
  /** Filter subscriptions created after this date (RFC3339 format) */
  createdFrom?: string;
  /** Filter subscriptions created before this date (RFC3339 format) */
  createdTo?: string;
  /** Filter subscriptions expiring before this date (RFC3339 format) */
  expiresBefore?: string;
  /** Sort by field: id, sid, user_id, plan_id, status, billing_cycle, start_date, end_date, created_at, updated_at */
  sortBy?: 'id' | 'sid' | 'user_id' | 'plan_id' | 'status' | 'billing_cycle' | 'start_date' | 'end_date' | 'created_at' | 'updated_at';
  /** Sort order */
  sortOrder?: 'asc' | 'desc';
  /**
   * Include subscription status counts in response.
   * When true, the response includes a `statusCounts` field with aggregated counts
   * by status (active, expired, suspended, pendingPayment, expiringIn7Days).
   * This eliminates the need for a separate dashboard API call.
   * Added: 2026-03-10
   */
  includeCounts?: boolean;
}

/**
 * Embedded user information in subscription responses
 */
export interface SubscriptionUser {
  /** User Stripe-style ID (usr_xxx) */
  id: string;
  /** User email address */
  email: string;
  /** User display name */
  name: string;
}

/**
 * Pricing option for a plan
 */
export interface PricingOption {
  /** Billing cycle */
  billingCycle: BillingCycle;
  /** Price in smallest currency unit (cents) */
  price: number;
  /** Currency code: CNY, USD, EUR, GBP, JPY */
  currency: string;
  /** Whether this pricing option is currently available */
  isActive: boolean;
}

/**
 * Subscription plan DTO
 * Updated: 2026-01-29 - Removed apiRateLimit, maxUsers, maxProjects fields
 */
export interface SubscriptionPlanDTO {
  /** Plan Stripe-style ID (plan_xxx) */
  id: string;
  /** Plan name */
  name: string;
  /** Plan slug for URL */
  slug: string;
  /** Plan description */
  description: string;
  /** Plan status */
  status: string;
  /** Plan type: node or forward */
  planType: string;
  /** Plan limits/features */
  limits: Record<string, unknown>;
  /** Whether plan is publicly visible */
  isPublic: boolean;
  /** Sort order for display */
  sortOrder: number;
  /** Pricing options for different billing cycles */
  pricings: PricingOption[];
  /** Plan creation time */
  createdAt: string;
  /** Plan last update time */
  updatedAt: string;
}

/**
 * Subscription DTO for admin responses
 */
export interface AdminSubscriptionDTO {
  /** Subscription Stripe-style ID (sub_xxx) */
  id: string;
  /** User Stripe-style ID (usr_xxx) */
  userId: string;
  /** Embedded user information */
  user?: SubscriptionUser;
  /** Subscription UUID (for backward compatibility) */
  uuid: string;
  /** Link token for subscription URL */
  linkToken: string;
  /** Full subscribe URL */
  subscribeUrl: string;
  /** Embedded plan information */
  plan?: SubscriptionPlanDTO;
  /** Subscription status */
  status: SubscriptionStatus;
  /** Subscription start date */
  startDate: string;
  /** Subscription end date */
  endDate: string;
  /** Whether auto-renewal is enabled */
  autoRenew: boolean;
  /** Current billing period start (used by billing/renewal flows) */
  currentPeriodStart: string;
  /** Current billing period end */
  currentPeriodEnd: string;
  /**
   * Current traffic cycle start (calendar_month or billing_cycle, depending on plan).
   * Pair with dataUsedBytes and currentCycleUpload/DownloadBytes; differs from
   * currentPeriodStart for calendar_month plans. Added: 2026-04-29.
   */
  currentTrafficCycleStart: string;
  /** Current traffic cycle end. See currentTrafficCycleStart. Added: 2026-04-29. */
  currentTrafficCycleEnd: string;
  /** Whether subscription is expired */
  isExpired: boolean;
  /** Whether subscription is active and can be used */
  isActive: boolean;
  /** Total traffic used in current cycle (= upload + download, plus admin adjustment) */
  dataUsedBytes: number;
  /** Traffic limit in bytes (0=unlimited) */
  dataLimitBytes: number;
  /** Upload traffic in current cycle (raw, no adjustment). Added: 2026-04-29. */
  currentCycleUploadBytes: number;
  /** Download traffic in current cycle (raw, no adjustment). Added: 2026-04-29. */
  currentCycleDownloadBytes: number;
  /** Current online device count */
  onlineDeviceCount: number;
  /** Max concurrent devices (0=unlimited) */
  deviceLimit: number;
  /** When subscription was cancelled */
  cancelledAt?: string;
  /** Reason for cancellation */
  cancelReason?: string;
  /** Subscription creation time */
  createdAt: string;
  /** Subscription last update time */
  updatedAt: string;
}

/**
 * Subscription token DTO
 */
export interface SubscriptionTokenDTO {
  /** Token Stripe-style ID (stoken_xxx) */
  id: string;
  /** Subscription Stripe-style ID */
  subscriptionId: string;
  /** Token name */
  name: string;
  /** Plain token value (only available at creation time) */
  token?: string;
  /** Token prefix for identification */
  prefix: string;
  /** Token scope */
  scope: string;
  /** Token expiration time */
  expiresAt?: string;
  /** Last time token was used */
  lastUsedAt?: string;
  /** Number of times token has been used */
  usageCount: number;
  /** Whether token is active */
  isActive: boolean;
  /** Token creation time */
  createdAt: string;
}

/**
 * Request to create a subscription (Admin)
 * POST /admin/subscriptions
 */
export interface AdminCreateSubscriptionRequest {
  /** User Stripe-style ID (usr_xxx) */
  userId: string;
  /** Plan Stripe-style ID (plan_xxx) */
  planId: string;
  /** Billing cycle for the subscription */
  billingCycle: BillingCycle;
  /** Subscription start date (defaults to now) */
  startDate?: string;
  /** Whether to enable auto-renewal (defaults to true) */
  autoRenew?: boolean;
  /** Payment information metadata */
  paymentInfo?: Record<string, unknown>;
  /** Whether to activate immediately (defaults to true for admin) */
  activate?: boolean;
}

/**
 * Response for creating a subscription (Admin)
 */
export interface AdminCreateSubscriptionResponse {
  /** Created subscription */
  subscription: AdminSubscriptionDTO;
  /** Generated subscription token */
  token: SubscriptionTokenDTO;
}

/**
 * Request to suspend a subscription
 * Used by POST /admin/subscriptions/:id/suspend
 */
export interface SuspendSubscriptionRequest {
  /** Reason for suspension (required) */
  reason: string;
}

/**
 * Request to renew a subscription
 * Used by POST /admin/subscriptions/:id/renew
 * Added: 2026-01-29
 *
 * **Allowed subscription statuses for renewal:**
 * - `active` - Extend subscription before expiration
 * - `past_due` - Renew overdue subscription
 * - `expired` - Reactivate expired subscription
 *
 * **NOT allowed statuses:**
 * - `suspended` - Must unsuspend first
 * - `cancelled` - Cannot renew cancelled subscriptions
 * - `inactive` - Not yet activated
 * - `pending_payment` - Payment pending
 * - `trialing` - In trial period
 *
 * **Note:** Lifetime subscriptions cannot be renewed.
 */
export interface RenewSubscriptionRequest {
  /**
   * Billing cycle for the renewal period.
   * Optional - if not provided, uses subscription's current billing cycle.
   * Valid values: "weekly", "monthly", "quarterly", "semi_annual", "yearly"
   */
  billingCycle?: 'weekly' | 'monthly' | 'quarterly' | 'semi_annual' | 'yearly';
}

/**
 * Request to change subscription plan
 * Used by PATCH /admin/subscriptions/:id/plan
 * Added: 2026-01-29
 *
 * **Allowed subscription status for plan change:**
 * - `active` - Only active subscriptions can change plans
 *
 * **NOT allowed statuses:**
 * - All other statuses (expired, cancelled, suspended, etc.)
 */
export interface ChangePlanRequest {
  /** New plan ID (Stripe-style SID like "plan_xxx") */
  newPlanId: string;
  /** Change type: upgrade or downgrade */
  changeType: 'upgrade' | 'downgrade';
  /** When the change takes effect */
  effectiveDate: 'immediate' | 'period_end';
}

/**
 * Request to update a subscription (Admin)
 * PATCH /admin/subscriptions/:id
 * Added: 2026-02-28
 *
 * All fields are optional. Use `null` for `dataLimitBytes` to clear the override.
 */
export interface AdminUpdateSubscriptionRequest {
  /** New subscription start date */
  startDate?: string;
  /** New subscription end date */
  endDate?: string;
  /** Traffic limit override in bytes (null to clear override, use plan default) */
  dataLimitBytes?: number | null;
  /** Reset traffic used to this value in bytes */
  dataUsedBytes?: number;
}

// Note: ResetSubscriptionUsage endpoint returns void (success message only)
// The operation resets billing period start to current time and auto-unsuspends if suspended

// ========== Cross-Module Query Types (Added 2026-03-10) ==========

/**
 * Subscription status aggregation counts
 * Returned by listAdminSubscriptions when includeCounts=true
 * Eliminates the need for a separate GET /admin/dashboard call
 * for subscription status statistics.
 */
export interface SubscriptionStatusCounts {
  /** Active subscriptions count */
  active: number;
  /** Expired subscriptions count */
  expired: number;
  /** Suspended subscriptions count */
  suspended: number;
  /** Pending payment subscriptions count */
  pendingPayment: number;
  /** Subscriptions expiring within 7 days */
  expiringIn7Days: number;
}

/**
 * Enhanced list response with optional status counts
 * Returned by listAdminSubscriptions when includeCounts=true.
 * Extends the standard ListResponse with status counts to enable
 * single-request page data loading.
 */
export interface AdminSubscriptionListResponse {
  /** List of subscriptions */
  items: AdminSubscriptionDTO[];
  /** Total number of matching subscriptions */
  total: number;
  /** Current page number */
  page: number;
  /** Page size */
  pageSize: number;
  /** Total number of pages */
  totalPages: number;
  /** Subscription status counts (present when includeCounts=true) */
  statusCounts?: SubscriptionStatusCounts;
}

// Note: Admin External Forward Rules have been removed (2026-01-20)
// External forward rules are now part of the unified ForwardRule model with rule_type='external'
// Use the forward module's Admin APIs with ruleType='external' filter instead
