/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2025-12-22
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 *
 * Admin Traffic Statistics API Types
 * These endpoints require admin authentication.
 */

// ========== Request Types ==========

/**
 * Common query parameters for traffic statistics endpoints
 */
export interface TrafficStatsQueryParams {
  /** Start date in YYYY-MM-DD format (e.g., "2025-01-01") */
  from: string;
  /** End date in YYYY-MM-DD format (e.g., "2025-01-31") */
  to: string;
  /** Optional: Filter by resource type ("node" or "forward_rule") */
  resourceType?: string;
  /** Page number (default: 1) */
  page?: number;
  /** Page size (default: 20, max: 100) */
  pageSize?: number;
}

/**
 * Query parameters for traffic ranking endpoints
 */
export interface TrafficRankingParams {
  /** Start date in YYYY-MM-DD format (e.g., "2025-01-01") */
  from: string;
  /** End date in YYYY-MM-DD format (e.g., "2025-01-31") */
  to: string;
  /** Optional: Filter by resource type ("node" or "forward_rule") */
  resourceType?: string;
  /** Number of top items to return (default: 10, max: 100) */
  limit?: number;
}

/**
 * Query parameters for traffic trend endpoint
 */
export interface TrafficTrendParams {
  /** Start date in YYYY-MM-DD format (e.g., "2025-01-01") */
  from: string;
  /** End date in YYYY-MM-DD format (e.g., "2025-01-31") */
  to: string;
  /** Optional: Filter by resource type ("node" or "forward_rule") */
  resourceType?: string;
  /** Time granularity: "hour", "day", or "month" */
  granularity: 'hour' | 'day' | 'month';
}

// ========== Response Types ==========

/**
 * Global traffic overview response
 * Provides platform-wide statistics for the specified time range
 */
export interface TrafficOverview {
  /** Total upload traffic in bytes */
  totalUpload: number;
  /** Total download traffic in bytes */
  totalDownload: number;
  /** Total traffic (upload + download) in bytes */
  totalTraffic: number;
  /** Number of active subscriptions */
  activeSubscriptions: number;
  /** Number of active users */
  activeUsers: number;
  /** Total number of nodes */
  totalNodes: number;
  /** Total number of forward rules */
  totalForwardRules: number;
}

/**
 * Traffic statistics for a single user
 */
export interface UserTrafficStatsItem {
  /** User Stripe-style ID (e.g., "usr_xK9mP2vL3nQ") */
  userId: string;
  /** User email address */
  userEmail: string;
  /** User display name */
  userName: string;
  /** Upload traffic in bytes */
  upload: number;
  /** Download traffic in bytes */
  download: number;
  /** Total traffic in bytes */
  total: number;
  /** Number of subscriptions this user has */
  subscriptionsCount: number;
}

/**
 * Traffic statistics for a single subscription
 */
export interface SubscriptionTrafficStatsItem {
  /** Subscription Stripe-style ID (e.g., "sub_xK9mP2vL3nQ") */
  subscriptionId: string;
  /** User Stripe-style ID (e.g., "usr_xK9mP2vL3nQ") */
  userId: string;
  /** User email address */
  userEmail: string;
  /** Subscription plan name */
  planName: string;
  /** Subscription status */
  status: string;
  /** Upload traffic in bytes */
  upload: number;
  /** Download traffic in bytes */
  download: number;
  /** Total traffic in bytes */
  total: number;
}

/**
 * Traffic statistics for a single node
 */
export interface NodeTrafficStatsItem {
  /** Node Stripe-style ID (e.g., "node_xK9mP2vL3nQ") */
  nodeId: string;
  /** Node name */
  nodeName: string;
  /** Node status */
  status: string;
  /** Upload traffic in bytes */
  upload: number;
  /** Download traffic in bytes */
  download: number;
  /** Total traffic in bytes */
  total: number;
}

/**
 * Single item in traffic ranking
 */
export interface TrafficRankingItem {
  /** Ranking position (1-based) */
  rank: number;
  /** Entity Stripe-style ID (user or subscription) */
  id: string;
  /** Entity name (user email or subscription name) */
  name: string;
  /** Upload traffic in bytes */
  upload: number;
  /** Download traffic in bytes */
  download: number;
  /** Total traffic in bytes */
  total: number;
}

/**
 * Traffic ranking response
 */
export interface TrafficRanking {
  /** List of ranked items */
  items: TrafficRankingItem[];
}

/**
 * Single data point in traffic trend
 */
export interface TrafficTrendPoint {
  /** Time period in ISO8601 format */
  period: string;
  /** Upload traffic in bytes for this period */
  upload: number;
  /** Download traffic in bytes for this period */
  download: number;
  /** Total traffic in bytes for this period */
  total: number;
}

/**
 * Traffic trend response
 */
export interface TrafficTrend {
  /** Time series data points */
  points: TrafficTrendPoint[];
  /** Time granularity used */
  granularity: 'hour' | 'day' | 'month';
}

// ========== Utility Functions ==========

/**
 * Format bytes to human readable string
 * @param bytes - Number of bytes
 * @returns Formatted string (e.g., "1.5 GB")
 */
export const formatTrafficBytes = (bytes: number): string => {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB', 'PB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(2))} ${sizes[i]}`;
};

/**
 * Calculate upload/download ratio
 * @param upload - Upload bytes
 * @param download - Download bytes
 * @returns Ratio string (e.g., "1:2.5")
 */
export const calculateTrafficRatio = (upload: number, download: number): string => {
  if (upload === 0 && download === 0) return '0:0';
  if (upload === 0) return `0:1`;
  if (download === 0) return `1:0`;
  const ratio = download / upload;
  return `1:${ratio.toFixed(1)}`;
};
