/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend - internal/interfaces/http/handlers/userhandler.go
 */

import { apiClient } from '@/shared/lib/axios';
import type { APIResponse, ListResponse } from '@/shared/types/api.types';
import type {
  UserResponse,
  CreateUserRequest,
  UpdateUserRequest,
  ListUsersParams,
} from './types';

/**
 * Create a new user (Admin only)
 * POST /users
 */
export const createUser = async (data: CreateUserRequest): Promise<UserResponse> => {
  const response = await apiClient.post<APIResponse<UserResponse>>('/users', data);
  return response.data.data;
};

/**
 * Get user by ID (Admin only)
 * GET /users/:id
 */
export const getUserById = async (id: number | string): Promise<UserResponse> => {
  const response = await apiClient.get<APIResponse<UserResponse>>(`/users/${id}`);
  return response.data.data;
};

/**
 * Get user by email (Admin only)
 * GET /users/email/:email
 */
export const getUserByEmail = async (email: string): Promise<UserResponse> => {
  const response = await apiClient.get<APIResponse<UserResponse>>(`/users/email/${email}`);
  return response.data.data;
};

/**
 * Update user (Admin only, partial update)
 * PATCH /users/:id
 */
export const updateUser = async (
  id: number | string,
  data: UpdateUserRequest
): Promise<UserResponse> => {
  const response = await apiClient.patch<APIResponse<UserResponse>>(`/users/${id}`, data);
  return response.data.data;
};

/**
 * Delete user (Admin only)
 * DELETE /users/:id
 */
export const deleteUser = async (id: number | string): Promise<void> => {
  await apiClient.delete(`/users/${id}`);
};

/**
 * List users with pagination and filters (Admin only)
 * GET /users
 */
export const listUsers = async (params?: ListUsersParams): Promise<ListResponse<UserResponse>> => {
  const response = await apiClient.get<APIResponse<ListResponse<UserResponse>>>('/users', { params });
  return response.data.data;
};
