/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend - internal/interfaces/http/handlers/userhandler.go
 * Last updated: 2026-01-08
 *
 * User Management API Client
 * Provides functions for admin user management and user self-service operations.
 */

import { apiClient } from '@/shared/lib/axios';
import type { APIResponse, ListResponse } from '@/shared/types/api.types';
import type {
  UserResponse,
  CreateUserRequest,
  UpdateUserRequest,
  ListUsersParams,
  AdminResetPasswordRequest,
  DashboardResponse,
} from './types';

// ============================================================================
// Admin User Management APIs
// These endpoints require admin role
// ============================================================================

/**
 * Create a new user (Admin only)
 * POST /users
 *
 * Creates a new user account with the specified email, name, and password.
 * The user will be created with 'user' role and 'active' status by default.
 *
 * Password requirements: 8-72 characters, must contain at least one letter and one number.
 *
 * @param data - User creation data including email, name, and password
 * @returns Created user object
 * @throws {401} Unauthorized - Not authenticated
 * @throws {403} Forbidden - Not admin
 * @throws {409} Conflict - Email already exists
 * @throws {422} Validation Error - Invalid email/name/password format
 *
 * @example
 * ```typescript
 * const newUser = await createUser({
 *   email: 'user@example.com',
 *   name: 'John Doe',
 *   password: 'secure123'
 * });
 * console.log(`Created user: ${newUser.id}`);
 * ```
 */
export const createUser = async (data: CreateUserRequest): Promise<UserResponse> => {
  const response = await apiClient.post<APIResponse<UserResponse>>('/users', data);
  return response.data.data;
};

/**
 * Get user by ID (Admin only)
 * GET /users/:id
 *
 * Retrieves detailed information about a specific user.
 *
 * @param id - Stripe-style user ID (e.g., "usr_xK9mP2vL3nQ")
 * @returns User object with full details
 * @throws {401} Unauthorized - Not authenticated
 * @throws {403} Forbidden - Not admin
 * @throws {404} Not Found - User does not exist
 *
 * @example
 * ```typescript
 * const user = await getUserById('usr_xK9mP2vL3nQ');
 * console.log(`User email: ${user.email}`);
 * ```
 */
export const getUserById = async (id: string): Promise<UserResponse> => {
  const response = await apiClient.get<APIResponse<UserResponse>>(`/users/${id}`);
  return response.data.data;
};

/**
 * Get user by email (Admin only)
 * GET /users/email/:email
 *
 * Looks up a user by their email address.
 * Useful for checking if a user exists before creating a new one.
 *
 * @param email - User's email address
 * @returns User object if found
 * @throws {401} Unauthorized - Not authenticated
 * @throws {403} Forbidden - Not admin
 * @throws {404} Not Found - No user with this email
 *
 * @example
 * ```typescript
 * try {
 *   const user = await getUserByEmail('user@example.com');
 *   console.log(`Found user: ${user.id}`);
 * } catch (error) {
 *   console.log('User not found');
 * }
 * ```
 */
export const getUserByEmail = async (email: string): Promise<UserResponse> => {
  const response = await apiClient.get<APIResponse<UserResponse>>(`/users/email/${email}`);
  return response.data.data;
};

/**
 * Update user (Admin only, partial update)
 * PATCH /users/:id
 *
 * Updates user information. Only provided fields will be modified.
 * Can update email, name, status, and role.
 *
 * @param id - Stripe-style user ID (e.g., "usr_xK9mP2vL3nQ")
 * @param data - Fields to update (all optional)
 * @returns Updated user object
 * @throws {401} Unauthorized - Not authenticated
 * @throws {403} Forbidden - Not admin
 * @throws {404} Not Found - User does not exist
 * @throws {409} Conflict - Email already in use by another user
 *
 * @example
 * ```typescript
 * // Promote user to admin
 * await updateUser('usr_xK9mP2vL3nQ', { role: 'admin' });
 *
 * // Suspend a user
 * await updateUser('usr_xK9mP2vL3nQ', { status: 'suspended' });
 *
 * // Update multiple fields
 * await updateUser('usr_xK9mP2vL3nQ', {
 *   name: 'New Name',
 *   email: 'new@example.com'
 * });
 * ```
 */
export const updateUser = async (
  id: string,
  data: UpdateUserRequest
): Promise<UserResponse> => {
  const response = await apiClient.patch<APIResponse<UserResponse>>(`/users/${id}`, data);
  return response.data.data;
};

/**
 * Delete user (Admin only)
 * DELETE /users/:id
 *
 * Permanently deletes a user account and all associated data.
 * This action cannot be undone.
 *
 * @param id - Stripe-style user ID (e.g., "usr_xK9mP2vL3nQ")
 * @throws {401} Unauthorized - Not authenticated
 * @throws {403} Forbidden - Not admin or trying to delete self
 * @throws {404} Not Found - User does not exist
 *
 * @example
 * ```typescript
 * await deleteUser('usr_xK9mP2vL3nQ');
 * console.log('User deleted successfully');
 * ```
 */
export const deleteUser = async (id: string): Promise<void> => {
  await apiClient.delete(`/users/${id}`);
};

/**
 * List users with pagination and filters (Admin only)
 * GET /users
 *
 * Retrieves a paginated list of users with optional filtering and sorting.
 *
 * @param params - Query parameters for filtering, sorting, and pagination
 * @returns Paginated list of users
 * @throws {401} Unauthorized - Not authenticated
 * @throws {403} Forbidden - Not admin
 *
 * @example
 * ```typescript
 * // List all active users
 * const result = await listUsers({ status: 'active' });
 *
 * // List admin users with pagination
 * const admins = await listUsers({
 *   role: 'admin',
 *   page: 1,
 *   pageSize: 20,
 *   orderBy: 'created_at',
 *   order: 'desc'
 * });
 *
 * console.log(`Found ${result.pagination.total} users`);
 * result.items.forEach(user => console.log(user.email));
 * ```
 */
export const listUsers = async (params?: ListUsersParams): Promise<ListResponse<UserResponse>> => {
  const response = await apiClient.get<APIResponse<ListResponse<UserResponse>>>('/users', { params });
  return response.data.data;
};

/**
 * Reset user password (Admin only)
 * PATCH /users/:id/password
 *
 * Allows admin to set a new password for a user.
 * Use when a user has forgotten their password and cannot reset it themselves.
 * This will NOT invalidate existing sessions - use updateUser to suspend if needed.
 *
 * Password requirements: 8-72 characters, must contain at least one letter and one number.
 *
 * @param id - Stripe-style user ID (e.g., "usr_xK9mP2vL3nQ")
 * @param data - New password data
 * @throws {401} Unauthorized - Not authenticated
 * @throws {403} Forbidden - Not admin
 * @throws {404} Not Found - User does not exist
 * @throws {422} Validation Error - Password too weak
 *
 * @example
 * ```typescript
 * await adminResetPassword('usr_xK9mP2vL3nQ', {
 *   password: 'newPass123'
 * });
 * console.log('Password reset successfully');
 * ```
 */
export const adminResetPassword = async (
  id: string,
  data: AdminResetPasswordRequest
): Promise<void> => {
  await apiClient.patch(`/users/${id}/password`, data);
};

// ============================================================================
// User Self-service APIs
// These endpoints are for authenticated users to manage their own account
// ============================================================================

/**
 * Get current user's dashboard with subscription and usage info
 * GET /users/me/dashboard
 *
 * Retrieves an overview of the current user's subscriptions and traffic usage.
 * Useful for displaying a dashboard or summary page.
 *
 * @returns Dashboard data with subscriptions and total usage
 * @throws {401} Unauthorized - Not authenticated
 *
 * @example
 * ```typescript
 * const dashboard = await getDashboard();
 *
 * // Display subscription count
 * console.log(`You have ${dashboard.subscriptions.length} subscription(s)`);
 *
 * // Display total usage
 * const { upload, download, total } = dashboard.totalUsage;
 * console.log(`Total traffic: ${formatBytes(total)}`);
 *
 * // Check active subscriptions
 * const activeCount = dashboard.subscriptions.filter(s => s.isActive).length;
 * console.log(`Active subscriptions: ${activeCount}`);
 * ```
 */
export const getDashboard = async (): Promise<DashboardResponse> => {
  const response = await apiClient.get<APIResponse<DashboardResponse>>('/users/me/dashboard');
  return response.data.data;
};
