/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend - internal/interfaces/http/handlers/userhandler.go
 * Last updated: 2025-12-19
 */

import { apiClient } from '@/shared/lib/axios';
import type { APIResponse, ListResponse } from '@/shared/types/api.types';
import type {
  UserResponse,
  CreateUserRequest,
  UpdateUserRequest,
  ListUsersParams,
  AdminResetPasswordRequest,
  DashboardResponse,
} from './types';

/**
 * Create a new user (Admin only)
 * POST /users
 */
export const createUser = async (data: CreateUserRequest): Promise<UserResponse> => {
  const response = await apiClient.post<APIResponse<UserResponse>>('/users', data);
  return response.data.data;
};

/**
 * Get user by ID (Admin only)
 * GET /users/:id
 * Updated 2025-12-19: ID parameter changed to string (Stripe-style ID: usr_xxx)
 */
export const getUserById = async (id: string): Promise<UserResponse> => {
  const response = await apiClient.get<APIResponse<UserResponse>>(`/users/${id}`);
  return response.data.data;
};

/**
 * Get user by email (Admin only)
 * GET /users/email/:email
 */
export const getUserByEmail = async (email: string): Promise<UserResponse> => {
  const response = await apiClient.get<APIResponse<UserResponse>>(`/users/email/${email}`);
  return response.data.data;
};

/**
 * Update user (Admin only, partial update)
 * PATCH /users/:id
 * Updated 2025-12-19: ID parameter changed to string (Stripe-style ID: usr_xxx)
 */
export const updateUser = async (
  id: string,
  data: UpdateUserRequest
): Promise<UserResponse> => {
  const response = await apiClient.patch<APIResponse<UserResponse>>(`/users/${id}`, data);
  return response.data.data;
};

/**
 * Delete user (Admin only)
 * DELETE /users/:id
 * Updated 2025-12-19: ID parameter changed to string (Stripe-style ID: usr_xxx)
 */
export const deleteUser = async (id: string): Promise<void> => {
  await apiClient.delete(`/users/${id}`);
};

/**
 * List users with pagination and filters (Admin only)
 * GET /users
 */
export const listUsers = async (params?: ListUsersParams): Promise<ListResponse<UserResponse>> => {
  const response = await apiClient.get<APIResponse<ListResponse<UserResponse>>>('/users', { params });
  return response.data.data;
};

/**
 * Reset user password (Admin only)
 * PATCH /users/:id/password
 * Updated 2025-12-19: ID parameter changed to string (Stripe-style ID: usr_xxx)
 */
export const adminResetPassword = async (
  id: string,
  data: AdminResetPasswordRequest
): Promise<void> => {
  await apiClient.patch(`/users/${id}/password`, data);
};

/**
 * Get current user's dashboard with subscription and usage info
 * GET /users/me/dashboard
 * @requires Authentication
 * Added: 2025-12-23
 */
export const getDashboard = async (): Promise<DashboardResponse> => {
  const response = await apiClient.get<APIResponse<DashboardResponse>>('/users/me/dashboard');
  return response.data.data;
};
