/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend - internal/application/user/dto/dto.go
 * Last updated: 2025-12-19
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 */

/** Request to create a new user (admin only) */
export interface CreateUserRequest {
  email: string;
  name: string;
}

/** Request to update user information (admin only) */
export interface UpdateUserRequest {
  email?: string;
  name?: string;
  status?: 'active' | 'inactive' | 'pending' | 'suspended';
  role?: 'user' | 'admin';
}

/** Request to list users with pagination and filters */
export interface ListUsersParams {
  page?: number;
  pageSize?: number;
  email?: string;
  name?: string;
  status?: string;
  role?: string;
  orderBy?: string;
  order?: 'asc' | 'desc';
}

/** User response data */
export interface UserResponse {
  // Updated 2025-12-19: Changed from number to string (Stripe-style ID: usr_xxx)
  id: string;
  email: string;
  name: string;
  displayName: string;
  initials: string;
  role: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  metadata?: UserMetadata;
}

/** Additional user metadata */
export interface UserMetadata {
  isBusinessEmail: boolean;
  canPerformActions: boolean;
  requiresVerification: boolean;
  emailDomain: string;
}

/** Pagination response metadata */
export interface PaginationResponse {
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
}

/** List users response with pagination */
export interface ListUsersResponse {
  users: UserResponse[];
  pagination: PaginationResponse;
}

/** Request for admin to reset user password */
export interface AdminResetPasswordRequest {
  password: string;
}

// Added 2025-12-19
/** Request to update user profile (current user) */
export interface UpdateProfileRequest {
  name?: string;
  email?: string;
}

// Added 2025-12-19
/** Request to change password */
export interface ChangePasswordRequest {
  oldPassword: string;
  newPassword: string;
  logoutAllDevices?: boolean;
}
