/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend - internal/application/user/dto/dto.go
 */

/** Request to create a new user (admin only) */
export interface CreateUserRequest {
  email: string;
  name: string;
}

/** Request to update user information (admin only) */
export interface UpdateUserRequest {
  email?: string;
  name?: string;
  status?: 'active' | 'inactive' | 'suspended' | 'deleted';
  role?: 'user' | 'admin';
}

/** Request to list users with pagination and filters */
export interface ListUsersParams {
  page?: number;
  pageSize?: number;
  email?: string;
  name?: string;
  status?: string;
  role?: string;
  orderBy?: string;
  order?: 'asc' | 'desc';
}

/** User response data */
export interface UserResponse {
  id: number;
  email: string;
  name: string;
  displayName: string;
  initials: string;
  role: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  metadata?: UserMetadata;
}

/** User type alias for compatibility */
export type User = UserResponse;

/** Additional user metadata */
export interface UserMetadata {
  isBusinessEmail: boolean;
  canPerformActions: boolean;
  requiresVerification: boolean;
  emailDomain: string;
}

/** Pagination response metadata */
export interface PaginationResponse {
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
}

/** List users response with pagination */
export interface ListUsersResponse {
  users: UserResponse[];
  pagination: PaginationResponse;
}
