/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend setting module
 * Last updated: 2026-01-06
 *
 * Note: All API endpoints require admin authentication.
 *
 * API Routes:
 * - GET /admin/settings/:category - Get all settings in a category
 * - PUT /admin/settings/:category - Update settings in a category
 * - GET /admin/settings/telegram/config - Get Telegram configuration
 * - PUT /admin/settings/telegram/config - Update Telegram configuration
 * - POST /admin/settings/telegram/test - Test Telegram connection
 */

import { apiClient } from '@/shared/lib/axios';
import type { APIResponse } from '@/shared/types/api.types';
import type {
  CategorySettingsResponse,
  UpdateCategorySettingsRequest,
  TelegramConfigResponse,
  UpdateTelegramConfigRequest,
  TestTelegramConnectionRequest,
  TelegramTestResult,
} from './types';

// ============================================================================
// Category Settings APIs
// ============================================================================

/**
 * Get all settings in a category
 * GET /admin/settings/:category
 * @requires Admin role
 *
 * @param category - Category name (e.g., 'telegram', 'notification')
 * @returns List of settings in the category
 *
 * @example
 * ```typescript
 * const result = await getCategorySettings('notification');
 * result.settings.forEach(s => console.log(s.key, s.value));
 * ```
 */
export async function getCategorySettings(
  category: string
): Promise<CategorySettingsResponse> {
  const response = await apiClient.get<APIResponse<CategorySettingsResponse>>(
    `/admin/settings/${category}`
  );
  return response.data.data;
}

/**
 * Update multiple settings in a category
 * PUT /admin/settings/:category
 * @requires Admin role
 *
 * @param category - Category name
 * @param data - Map of setting key to new value
 *
 * @example
 * ```typescript
 * await updateCategorySettings('notification', {
 *   settings: {
 *     'email_enabled': true,
 *     'email_from': 'noreply@example.com'
 *   }
 * });
 * ```
 */
export async function updateCategorySettings(
  category: string,
  data: UpdateCategorySettingsRequest
): Promise<void> {
  await apiClient.put(`/admin/settings/${category}`, data);
}

// ============================================================================
// Telegram Configuration APIs
// ============================================================================

/**
 * Get Telegram bot configuration
 * GET /admin/settings/telegram/config
 * @requires Admin role
 *
 * Note: Sensitive fields (botToken, webhookSecret) are masked in the response.
 *
 * @returns Telegram configuration with masked sensitive values
 *
 * @example
 * ```typescript
 * const config = await getTelegramConfig();
 * console.log(config.enabled);  // true or false
 * console.log(config.botToken); // "***...***" (masked)
 * console.log(config.mode);     // "webhook" or "polling"
 * ```
 */
export async function getTelegramConfig(): Promise<TelegramConfigResponse> {
  const response = await apiClient.get<APIResponse<TelegramConfigResponse>>(
    '/admin/settings/telegram/config'
  );
  return response.data.data;
}

/**
 * Update Telegram bot configuration
 * PUT /admin/settings/telegram/config
 * @requires Admin role
 *
 * @param data - Partial configuration to update
 *
 * @example
 * ```typescript
 * // Enable Telegram with a new bot token
 * await updateTelegramConfig({
 *   enabled: true,
 *   botToken: '123456:ABC-DEF...'
 * });
 *
 * // Disable Telegram
 * await updateTelegramConfig({ enabled: false });
 * ```
 */
export async function updateTelegramConfig(
  data: UpdateTelegramConfigRequest
): Promise<void> {
  await apiClient.put('/admin/settings/telegram/config', data);
}

/**
 * Test Telegram bot connection
 * POST /admin/settings/telegram/test
 * @requires Admin role
 *
 * Tests connectivity to the Telegram API using either:
 * - The provided bot token (for testing before saving)
 * - The saved bot token (if no token provided)
 *
 * @param data - Optional bot token to test
 * @returns Test result with bot username or error
 *
 * @example
 * ```typescript
 * // Test with a new token before saving
 * const result = await testTelegramConnection({
 *   botToken: '123456:ABC-DEF...'
 * });
 *
 * if (result.success) {
 *   console.log(`Connected to @${result.botUsername}`);
 *   await updateTelegramConfig({ botToken: '123456:ABC-DEF...' });
 * } else {
 *   console.error(`Failed: ${result.error}`);
 * }
 *
 * // Test with saved token
 * const result = await testTelegramConnection({});
 * ```
 */
export async function testTelegramConnection(
  data?: TestTelegramConnectionRequest
): Promise<TelegramTestResult> {
  const response = await apiClient.post<APIResponse<TelegramTestResult>>(
    '/admin/settings/telegram/test',
    data || {}
  );
  return response.data.data;
}
