/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend setting module
 * Last updated: 2026-01-23
 *
 * Note: All API endpoints require admin authentication.
 *
 * API Routes:
 * - GET /admin/settings/:category - Get all settings in a category
 * - PUT /admin/settings/:category - Update settings in a category
 * - GET /admin/settings/system - Get system settings (Added 2026-01-23)
 * - PUT /admin/settings/system - Update system settings (Added 2026-01-23)
 * - GET /admin/settings/oauth - Get OAuth settings (Added 2026-01-23)
 * - PUT /admin/settings/oauth - Update OAuth settings (Added 2026-01-23)
 * - GET /admin/settings/email - Get email settings (Added 2026-01-23)
 * - PUT /admin/settings/email - Update email settings (Added 2026-01-23)
 * - POST /admin/settings/email/test - Test email connection (Added 2026-01-23)
 * - GET /admin/settings/setup-status - Get setup status (Added 2026-01-23)
 * - GET /admin/settings/telegram/config - Get Telegram configuration
 * - PUT /admin/settings/telegram/config - Update Telegram configuration
 * - POST /admin/settings/telegram/test - Test Telegram connection
 */

import { apiClient } from '@/shared/lib/axios';
import type { APIResponse } from '@/shared/types/api.types';
import type {
  CategorySettingsResponse,
  UpdateCategorySettingsRequest,
  SystemSettingsResponse,
  UpdateSystemSettingsRequest,
  OAuthSettingsResponse,
  UpdateOAuthSettingsRequest,
  EmailSettingsResponse,
  UpdateEmailSettingsRequest,
  EmailTestRequest,
  EmailTestResponse,
  SetupStatusResponse,
  TelegramConfigResponse,
  UpdateTelegramConfigRequest,
  TestTelegramConnectionRequest,
  TelegramTestResult,
} from './types';

// ============================================================================
// Category Settings APIs
// ============================================================================

/**
 * Get all settings in a category
 * GET /admin/settings/:category
 * @requires Admin role
 *
 * @param category - Category name (e.g., 'telegram', 'notification')
 * @returns List of settings in the category
 *
 * @example
 * ```typescript
 * const result = await getCategorySettings('notification');
 * result.settings.forEach(s => console.log(s.key, s.value));
 * ```
 */
export async function getCategorySettings(
  category: string
): Promise<CategorySettingsResponse> {
  const response = await apiClient.get<APIResponse<CategorySettingsResponse>>(
    `/admin/settings/${category}`
  );
  return response.data.data;
}

/**
 * Update multiple settings in a category
 * PUT /admin/settings/:category
 * @requires Admin role
 *
 * @param category - Category name
 * @param data - Map of setting key to new value
 *
 * @example
 * ```typescript
 * await updateCategorySettings('notification', {
 *   settings: {
 *     'email_enabled': true,
 *     'email_from': 'noreply@example.com'
 *   }
 * });
 * ```
 */
export async function updateCategorySettings(
  category: string,
  data: UpdateCategorySettingsRequest
): Promise<void> {
  await apiClient.put(`/admin/settings/${category}`, data);
}

// ============================================================================
// System Settings APIs (Added 2026-01-23)
// ============================================================================

/**
 * Get system settings
 * GET /admin/settings/system
 * @requires Admin role
 *
 * Returns core system configuration values including API base URL,
 * subscription base URL, frontend URL, and timezone settings.
 * Each setting includes its value, source (database/environment/default),
 * and whether it's read-only.
 *
 * @returns System settings with source information
 *
 * @example
 * ```typescript
 * const settings = await getSystemSettings();
 * console.log('API URL:', settings.apiBaseUrl.value);
 * console.log('Source:', settings.apiBaseUrl.source); // 'environment'
 * console.log('Read-only:', settings.apiBaseUrl.isReadOnly); // true
 * ```
 */
export async function getSystemSettings(): Promise<SystemSettingsResponse> {
  const response = await apiClient.get<APIResponse<SystemSettingsResponse>>(
    '/admin/settings/system'
  );
  return response.data.data;
}

/**
 * Update system settings
 * PUT /admin/settings/system
 * @requires Admin role
 *
 * Updates modifiable system settings. Note that apiBaseUrl is read-only
 * and can only be configured via environment variable.
 *
 * @param data - Settings to update
 *
 * @example
 * ```typescript
 * await updateSystemSettings({
 *   subscriptionBaseUrl: 'https://subscribe.example.com',
 *   frontendUrl: 'https://app.example.com',
 * });
 * ```
 */
export async function updateSystemSettings(
  data: UpdateSystemSettingsRequest
): Promise<void> {
  await apiClient.put('/admin/settings/system', data);
}

// ============================================================================
// OAuth Settings APIs (Added 2026-01-23)
// ============================================================================

/**
 * Get OAuth settings
 * GET /admin/settings/oauth
 * @requires Admin role
 *
 * Returns OAuth configuration for all supported providers (Google, GitHub).
 * Each provider includes enabled status and settings with source info.
 * Sensitive values (client_secret) are masked.
 *
 * @returns OAuth settings for all providers
 *
 * @example
 * ```typescript
 * const oauth = await getOAuthSettings();
 * if (oauth.google.enabled) {
 *   console.log('Google Client ID:', oauth.google.clientId.value);
 * }
 * ```
 */
export async function getOAuthSettings(): Promise<OAuthSettingsResponse> {
  const response = await apiClient.get<APIResponse<OAuthSettingsResponse>>(
    '/admin/settings/oauth'
  );
  return response.data.data;
}

/**
 * Update OAuth settings
 * PUT /admin/settings/oauth
 * @requires Admin role
 *
 * Updates OAuth configuration for one or more providers.
 * Only specified fields will be updated.
 *
 * @param data - OAuth settings to update
 *
 * @example
 * ```typescript
 * await updateOAuthSettings({
 *   google: {
 *     clientId: 'new-client-id',
 *     clientSecret: 'new-client-secret',
 *     redirectUrl: 'https://app.example.com/auth/google/callback',
 *   },
 * });
 * ```
 */
export async function updateOAuthSettings(
  data: UpdateOAuthSettingsRequest
): Promise<void> {
  await apiClient.put('/admin/settings/oauth', data);
}

// ============================================================================
// Email Settings APIs (Added 2026-01-23)
// ============================================================================

/**
 * Get email settings
 * GET /admin/settings/email
 * @requires Admin role
 *
 * Returns SMTP email configuration with source information.
 * Sensitive values (smtp_password) are masked.
 *
 * @returns Email settings with source info
 *
 * @example
 * ```typescript
 * const email = await getEmailSettings();
 * console.log('SMTP Host:', email.smtpHost.value);
 * console.log('From:', email.fromAddress.value);
 * ```
 */
export async function getEmailSettings(): Promise<EmailSettingsResponse> {
  const response = await apiClient.get<APIResponse<EmailSettingsResponse>>(
    '/admin/settings/email'
  );
  return response.data.data;
}

/**
 * Update email settings
 * PUT /admin/settings/email
 * @requires Admin role
 *
 * Updates SMTP email configuration. Only specified fields will be updated.
 *
 * @param data - Email settings to update
 *
 * @example
 * ```typescript
 * await updateEmailSettings({
 *   smtpHost: 'smtp.example.com',
 *   smtpPort: 587,
 *   smtpUser: 'user@example.com',
 *   smtpPassword: 'password',
 *   fromAddress: 'noreply@example.com',
 *   fromName: 'My App',
 * });
 * ```
 */
export async function updateEmailSettings(
  data: UpdateEmailSettingsRequest
): Promise<void> {
  await apiClient.put('/admin/settings/email', data);
}

/**
 * Test email connection
 * POST /admin/settings/email/test
 * @requires Admin role
 *
 * Sends a test email to verify SMTP configuration is working.
 *
 * @param data - Test request with recipient email
 * @returns Test result with success status
 *
 * @example
 * ```typescript
 * const result = await testEmailConnection({
 *   recipientEmail: 'admin@example.com',
 * });
 * if (result.success) {
 *   console.log('Test email sent successfully');
 * } else {
 *   console.error('Failed:', result.error);
 * }
 * ```
 */
export async function testEmailConnection(
  data: EmailTestRequest
): Promise<EmailTestResponse> {
  const response = await apiClient.post<APIResponse<EmailTestResponse>>(
    '/admin/settings/email/test',
    data
  );
  return response.data.data;
}

// ============================================================================
// Setup Status API (Added 2026-01-23)
// ============================================================================

/**
 * Get setup status
 * GET /admin/settings/setup-status
 * @requires Admin role
 *
 * Checks if the system is properly configured for first-time setup.
 * Returns whether setup is complete and lists any missing required settings.
 *
 * @returns Setup status with missing settings
 *
 * @example
 * ```typescript
 * const status = await getSetupStatus();
 * if (status.requiresSetup) {
 *   console.log('Missing settings:', status.missingSettings);
 * }
 * ```
 */
export async function getSetupStatus(): Promise<SetupStatusResponse> {
  const response = await apiClient.get<APIResponse<SetupStatusResponse>>(
    '/admin/settings/setup-status'
  );
  return response.data.data;
}

// ============================================================================
// Telegram Configuration APIs
// ============================================================================

/**
 * Get Telegram bot configuration
 * GET /admin/settings/telegram/config
 * @requires Admin role
 *
 * Note: Sensitive fields (botToken, webhookSecret) are masked in the response.
 *
 * @returns Telegram configuration with masked sensitive values
 *
 * @example
 * ```typescript
 * const config = await getTelegramConfig();
 * console.log(config.enabled);  // true or false
 * console.log(config.botToken); // "***...***" (masked)
 * console.log(config.mode);     // "webhook" or "polling"
 * ```
 */
export async function getTelegramConfig(): Promise<TelegramConfigResponse> {
  const response = await apiClient.get<APIResponse<TelegramConfigResponse>>(
    '/admin/settings/telegram/config'
  );
  return response.data.data;
}

/**
 * Update Telegram bot configuration
 * PUT /admin/settings/telegram/config
 * @requires Admin role
 *
 * @param data - Partial configuration to update
 *
 * @example
 * ```typescript
 * // Enable Telegram with a new bot token
 * await updateTelegramConfig({
 *   enabled: true,
 *   botToken: '123456:ABC-DEF...'
 * });
 *
 * // Disable Telegram
 * await updateTelegramConfig({ enabled: false });
 * ```
 */
export async function updateTelegramConfig(
  data: UpdateTelegramConfigRequest
): Promise<void> {
  await apiClient.put('/admin/settings/telegram/config', data);
}

/**
 * Test Telegram bot connection
 * POST /admin/settings/telegram/test
 * @requires Admin role
 *
 * Tests connectivity to the Telegram API using either:
 * - The provided bot token (for testing before saving)
 * - The saved bot token (if no token provided)
 *
 * @param data - Optional bot token to test
 * @returns Test result with bot username or error
 *
 * @example
 * ```typescript
 * // Test with a new token before saving
 * const result = await testTelegramConnection({
 *   botToken: '123456:ABC-DEF...'
 * });
 *
 * if (result.success) {
 *   console.log(`Connected to @${result.botUsername}`);
 *   await updateTelegramConfig({ botToken: '123456:ABC-DEF...' });
 * } else {
 *   console.error(`Failed: ${result.error}`);
 * }
 *
 * // Test with saved token
 * const result = await testTelegramConnection({});
 * ```
 */
export async function testTelegramConnection(
  data?: TestTelegramConnectionRequest
): Promise<TelegramTestResult> {
  const response = await apiClient.post<APIResponse<TelegramTestResult>>(
    '/admin/settings/telegram/test',
    data || {}
  );
  return response.data.data;
}
