/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend setting module
 * Last updated: 2026-01-31
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 *
 * This module provides system settings management for admin users.
 * Settings are organized by category (e.g., 'telegram', 'notification', 'subscription').
 *
 * Recent changes:
 * - 2026-01-31: Removed Maintenance settings (feature removed)
 * - 2026-01-31: Added Branding, Security, Registration, Legal settings
 * - 2026-01-31: Added public API types for unauthenticated access
 * - 2026-01-30: Added SubscriptionSettingsResponse and UpdateSubscriptionSettingsRequest
 *   for managing subscription display settings (show_info_nodes)
 */

// ============================================================================
// System Setting Types
// ============================================================================

/**
 * Single system setting response
 * Represents a configuration value stored in the system
 */
export interface SystemSettingResponse {
  /** Stripe-style setting ID */
  sid: string;
  /** Category name (e.g., 'telegram', 'notification') */
  category: string;
  /** Setting key within the category */
  key: string;
  /** Setting value (type depends on valueType) */
  value: unknown;
  /** Value type: 'string', 'bool', 'int', 'json' */
  valueType: string;
  /** Human-readable description of the setting */
  description: string;
  /** Whether the value is sensitive (will be masked in responses) */
  isSensitive: boolean;
  /** Last update timestamp */
  updatedAt: string;
}

/**
 * Category settings response
 * Returns all settings within a specific category
 */
export interface CategorySettingsResponse {
  /** Category name */
  category: string;
  /** List of settings in this category */
  settings: SystemSettingResponse[];
}

/**
 * Request to update a single setting value
 */
export interface UpdateSettingRequest {
  /** New value for the setting */
  value: unknown;
}

/**
 * Request to batch update multiple settings in a category
 */
export interface UpdateCategorySettingsRequest {
  /** Map of setting key to new value */
  settings: Record<string, unknown>;
}

// ============================================================================
// Config Source Types (Added 2026-01-23)
// ============================================================================

/**
 * Configuration source type
 * Indicates where a configuration value comes from
 */
export type ConfigSource = 'database' | 'environment' | 'default';

/**
 * Setting value with source information
 * Used to show where configuration values come from
 */
export interface SettingWithSource {
  /** Setting value */
  value: unknown;
  /** Where this value comes from */
  source: ConfigSource;
  /** Whether this value is sensitive (should be masked) */
  isSensitive: boolean;
  /** Whether this setting is read-only (e.g., from environment) */
  isReadOnly?: boolean;
}

// ============================================================================
// System Settings Types (Added 2026-01-23)
// ============================================================================

/**
 * System settings response
 * Contains core system configuration values with source info
 */
export interface SystemSettingsResponse {
  /** API base URL setting */
  apiBaseUrl: SettingWithSource;
  /** Subscription base URL setting */
  subscriptionBaseUrl: SettingWithSource;
  /** Frontend URL setting */
  frontendUrl: SettingWithSource;
  /** Business timezone setting */
  timezone: SettingWithSource;
}

/**
 * Request to update system settings
 * Note: apiBaseUrl is read-only and can only be configured via environment variable
 */
export interface UpdateSystemSettingsRequest {
  /** New subscription base URL */
  subscriptionBaseUrl?: string;
  /** New frontend URL */
  frontendUrl?: string;
}

// ============================================================================
// OAuth Settings Types (Added 2026-01-23)
// ============================================================================

/**
 * OAuth provider settings
 * Configuration for a single OAuth provider (Google, GitHub, etc.)
 */
export interface OAuthProviderSettings {
  /** Whether this OAuth provider is enabled */
  enabled: boolean;
  /** OAuth client ID */
  clientId: SettingWithSource;
  /** OAuth client secret (masked) */
  clientSecret: SettingWithSource;
  /** OAuth redirect URL */
  redirectUrl: SettingWithSource;
}

/**
 * OAuth settings response
 * Contains OAuth configuration for all providers
 */
export interface OAuthSettingsResponse {
  /** Google OAuth settings */
  google: OAuthProviderSettings;
  /** GitHub OAuth settings */
  github: OAuthProviderSettings;
}

/**
 * Request to update a single OAuth provider
 */
export interface UpdateOAuthProviderRequest {
  /** New client ID */
  clientId?: string;
  /** New client secret */
  clientSecret?: string;
  /** New redirect URL */
  redirectUrl?: string;
}

/**
 * Request to update OAuth settings
 * Update configuration for one or more OAuth providers
 */
export interface UpdateOAuthSettingsRequest {
  /** Google OAuth settings to update */
  google?: UpdateOAuthProviderRequest;
  /** GitHub OAuth settings to update */
  github?: UpdateOAuthProviderRequest;
}

// ============================================================================
// Email Settings Types (Added 2026-01-23)
// ============================================================================

/**
 * Email settings response
 * Contains SMTP configuration for sending emails
 */
export interface EmailSettingsResponse {
  /** SMTP server hostname */
  smtpHost: SettingWithSource;
  /** SMTP server port */
  smtpPort: SettingWithSource;
  /** SMTP username for authentication */
  smtpUser: SettingWithSource;
  /** SMTP password (masked) */
  smtpPassword: SettingWithSource;
  /** Email sender address */
  fromAddress: SettingWithSource;
  /** Email sender display name */
  fromName: SettingWithSource;
}

/**
 * Request to update email settings
 * All fields are optional - only provided fields will be updated
 */
export interface UpdateEmailSettingsRequest {
  /** New SMTP hostname */
  smtpHost?: string;
  /** New SMTP port */
  smtpPort?: number;
  /** New SMTP username */
  smtpUser?: string;
  /** New SMTP password */
  smtpPassword?: string;
  /** New from address */
  fromAddress?: string;
  /** New from name */
  fromName?: string;
}

/**
 * Request to test email connection
 * Sends a test email to verify SMTP configuration
 */
export interface EmailTestRequest {
  /** Email address to send test email to */
  recipientEmail: string;
}

/**
 * Email test result
 * Response from testing email connection
 */
export interface EmailTestResponse {
  /** Whether the test email was sent successfully */
  success: boolean;
  /** Error message if failed */
  error?: string;
}

// ============================================================================
// Setup Status Types (Added 2026-01-23)
// ============================================================================

/**
 * Setup status response
 * Used to check if first-time configuration is needed
 */
export interface SetupStatusResponse {
  /** Whether the system is configured */
  isConfigured: boolean;
  /** Whether setup wizard should be shown */
  requiresSetup: boolean;
  /** List of missing required settings */
  missingSettings: string[];
}

// ============================================================================
// Telegram Configuration Types
// ============================================================================

/**
 * Telegram bot configuration response
 * Used for admin Telegram notifications
 */
export interface TelegramConfigResponse {
  /** Whether Telegram notifications are enabled */
  enabled: boolean;
  /** Bot token (masked for security) */
  botToken: string;
  /** Webhook URL for receiving Telegram updates */
  webhookUrl: string;
  /** Webhook secret (masked for security) */
  webhookSecret: string;
  /** Link to start conversation with the bot */
  botLink?: string;
  /** Operation mode: 'webhook' or 'polling' */
  mode: string;
}

/**
 * Request to update Telegram configuration
 * All fields are optional - only provided fields will be updated
 */
export interface UpdateTelegramConfigRequest {
  /** Enable or disable Telegram notifications */
  enabled?: boolean;
  /** New bot token */
  botToken?: string;
  /** New webhook URL */
  webhookUrl?: string;
  /** New webhook secret */
  webhookSecret?: string;
}

/**
 * Request to test Telegram bot connection
 */
export interface TestTelegramConnectionRequest {
  /** Bot token to test (optional - if empty, uses saved token) */
  botToken?: string;
}

/**
 * Result of Telegram connection test
 */
export interface TelegramTestResult {
  /** Whether the connection test succeeded */
  success: boolean;
  /** Bot username if successful */
  botUsername?: string;
  /** Error message if failed */
  error?: string;
}

// ============================================================================
// USDT Settings Types (Added 2026-01-25, Updated 2026-01-26)
// ============================================================================

/**
 * USDT payment settings response
 */
export interface USDTSettingsResponse {
  /** Whether USDT payment is enabled */
  enabled: SettingWithSource;
  /** Polygon (MATIC) network receiving addresses */
  polReceivingAddresses: SettingWithSource;
  /** Tron (TRC-20) network receiving addresses */
  trcReceivingAddresses: SettingWithSource;
  /** PolygonScan API key (masked in response) */
  polygonscanApiKey: SettingWithSource;
  /** TronGrid API key (masked in response) */
  trongridApiKey: SettingWithSource;
  /** Payment expiration time in minutes */
  paymentTtlMinutes: SettingWithSource;
  /** Required block confirmations for Polygon */
  polConfirmations: SettingWithSource;
  /** Required block confirmations for Tron */
  trcConfirmations: SettingWithSource;
}

/**
 * Request to update USDT settings
 */
export interface UpdateUSDTSettingsRequest {
  /** Enable or disable USDT payments */
  enabled?: boolean;
  /** New Polygon receiving addresses (array) */
  polReceivingAddresses?: string[];
  /** New Tron receiving addresses (array) */
  trcReceivingAddresses?: string[];
  /** New PolygonScan API key */
  polygonscanApiKey?: string;
  /** New TronGrid API key */
  trongridApiKey?: string;
  /** New payment TTL in minutes */
  paymentTtlMinutes?: number;
  /** New required confirmations for Polygon */
  polConfirmations?: number;
  /** New required confirmations for Tron */
  trcConfirmations?: number;
}

// ============================================================================
// Subscription Settings Types (Added 2026-01-30)
// ============================================================================

/**
 * Subscription settings response
 */
export interface SubscriptionSettingsResponse {
  /** Whether to show info nodes in subscription output */
  showInfoNodes: SettingWithSource;
}

/**
 * Request to update subscription settings
 */
export interface UpdateSubscriptionSettingsRequest {
  /** Enable or disable info nodes in subscription output */
  showInfoNodes?: boolean;
}

// ============================================================================
// Branding Settings Types (Added 2026-01-31)
// ============================================================================

/**
 * Branding settings response (admin)
 * Contains app branding configuration with source info
 */
export interface BrandingSettingsResponse {
  /** Application name */
  appName: SettingWithSource;
  /** Logo URL */
  logoUrl: SettingWithSource;
  /** Favicon URL */
  faviconUrl: SettingWithSource;
}

/**
 * Request to update branding settings
 */
export interface UpdateBrandingSettingsRequest {
  /** New application name (max 50 chars) */
  appName?: string;
  /** New logo URL (max 500 chars, must be /uploads/branding/* path) */
  logoUrl?: string;
  /** New favicon URL (max 500 chars, must be /uploads/branding/* path) */
  faviconUrl?: string;
}

/**
 * Public branding response (no auth required)
 * Simplified response without source tracking
 */
export interface PublicBrandingResponse {
  /** Application name */
  appName: string;
  /** Logo URL */
  logoUrl: string;
  /** Favicon URL */
  faviconUrl: string;
}

/**
 * Branding image upload response
 */
export interface BrandingUploadResponse {
  /** URL path to the uploaded image */
  url: string;
}

// ============================================================================
// Security Settings Types (Added 2026-01-31)
// ============================================================================

/**
 * Security settings response
 * Contains password policy, session, and login protection settings
 */
export interface SecuritySettingsResponse {
  // Password policy
  /** Minimum password length (default: 8) */
  passwordMinLength: SettingWithSource;
  /** Require uppercase letter (default: false) */
  passwordRequireUppercase: SettingWithSource;
  /** Require lowercase letter (default: false) */
  passwordRequireLowercase: SettingWithSource;
  /** Require number (default: false) */
  passwordRequireNumber: SettingWithSource;
  /** Require special character (default: false) */
  passwordRequireSpecial: SettingWithSource;
  /** Password expiry in days, 0 = never (default: 0) */
  passwordExpiryDays: SettingWithSource;

  // Session settings
  /** Session timeout in minutes (default: 1440 = 24 hours) */
  sessionTimeoutMinutes: SettingWithSource;

  // Login protection
  /** Max login attempts before lockout (default: 5) */
  maxLoginAttempts: SettingWithSource;
  /** Lockout duration in minutes (default: 15) */
  lockoutDurationMinutes: SettingWithSource;
}

/**
 * Request to update security settings
 */
export interface UpdateSecuritySettingsRequest {
  // Password policy
  /** Minimum password length (8-32) */
  passwordMinLength?: number;
  /** Require uppercase letter */
  passwordRequireUppercase?: boolean;
  /** Require lowercase letter */
  passwordRequireLowercase?: boolean;
  /** Require number */
  passwordRequireNumber?: boolean;
  /** Require special character */
  passwordRequireSpecial?: boolean;
  /** Password expiry in days (0-365) */
  passwordExpiryDays?: number;

  // Session settings
  /** Session timeout in minutes (5-43200) */
  sessionTimeoutMinutes?: number;

  // Login protection
  /** Max login attempts (3-20) */
  maxLoginAttempts?: number;
  /** Lockout duration in minutes (1-1440) */
  lockoutDurationMinutes?: number;
}

// ============================================================================
// Registration Settings Types (Added 2026-01-31)
// ============================================================================

/**
 * Registration settings response
 */
export interface RegistrationSettingsResponse {
  /** Whether new user registration is allowed */
  registrationEnabled: SettingWithSource;
  /** Whether email verification is required */
  emailVerificationRequired: SettingWithSource;
}

/**
 * Request to update registration settings
 */
export interface UpdateRegistrationSettingsRequest {
  /** Enable or disable registration */
  registrationEnabled?: boolean;
  /** Require email verification */
  emailVerificationRequired?: boolean;
}

/**
 * Public registration response (no auth required)
 */
export interface PublicRegistrationResponse {
  /** Whether registration is enabled */
  registrationEnabled: boolean;
  /** Whether email verification is required */
  emailVerificationRequired: boolean;
}

// ============================================================================
// Legal Settings Types (Added 2026-01-31)
// ============================================================================

/**
 * Legal settings response
 */
export interface LegalSettingsResponse {
  /** Terms of service URL */
  termsOfServiceUrl: SettingWithSource;
  /** Privacy policy URL */
  privacyPolicyUrl: SettingWithSource;
}

/**
 * Request to update legal settings
 */
export interface UpdateLegalSettingsRequest {
  /** New terms of service URL (max 500 chars) */
  termsOfServiceUrl?: string;
  /** New privacy policy URL (max 500 chars) */
  privacyPolicyUrl?: string;
}

/**
 * Public legal response (no auth required)
 */
export interface PublicLegalResponse {
  /** Terms of service URL */
  termsOfServiceUrl: string;
  /** Privacy policy URL */
  privacyPolicyUrl: string;
}

// ============================================================================
// Password Policy Types (Added 2026-01-31)
// ============================================================================

/**
 * Password policy rule for frontend display
 */
export interface PasswordPolicyRule {
  /** Rule type: min_length, max_length, uppercase, lowercase, number, special */
  type: string;
  /** Value for length rules */
  value?: number;
  /** Whether this rule is required (for character rules) */
  required?: boolean;
  /** Human-readable description */
  message: string;
}

/**
 * Public password policy response (no auth required)
 * Used by frontend to display password requirements
 */
export interface PublicPasswordPolicyResponse {
  /** Minimum password length */
  minLength: number;
  /** Maximum password length (bcrypt limit: 72) */
  maxLength: number;
  /** Require uppercase letter */
  requireUppercase: boolean;
  /** Require lowercase letter */
  requireLowercase: boolean;
  /** Require number */
  requireNumber: boolean;
  /** Require special character */
  requireSpecial: boolean;
  /** Array of rules for display */
  rules: PasswordPolicyRule[];
  /** Allowed special characters */
  specialCharacters: string;
}
