/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend setting module
 * Last updated: 2026-01-26
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 *
 * This module provides system settings management for admin users.
 * Settings are organized by category (e.g., 'telegram', 'notification').
 */

// ============================================================================
// System Setting Types
// ============================================================================

/**
 * Single system setting response
 * Represents a configuration value stored in the system
 */
export interface SystemSettingResponse {
  /** Stripe-style setting ID */
  sid: string;
  /** Category name (e.g., 'telegram', 'notification') */
  category: string;
  /** Setting key within the category */
  key: string;
  /** Setting value (type depends on valueType) */
  value: unknown;
  /** Value type: 'string', 'bool', 'int', 'json' */
  valueType: string;
  /** Human-readable description of the setting */
  description: string;
  /** Whether the value is sensitive (will be masked in responses) */
  isSensitive: boolean;
  /** Last update timestamp */
  updatedAt: string;
}

/**
 * Category settings response
 * Returns all settings within a specific category
 */
export interface CategorySettingsResponse {
  /** Category name */
  category: string;
  /** List of settings in this category */
  settings: SystemSettingResponse[];
}

/**
 * Request to update a single setting value
 */
export interface UpdateSettingRequest {
  /** New value for the setting */
  value: unknown;
}

/**
 * Request to batch update multiple settings in a category
 */
export interface UpdateCategorySettingsRequest {
  /** Map of setting key to new value */
  settings: Record<string, unknown>;
}

// ============================================================================
// Config Source Types (Added 2026-01-23)
// ============================================================================

/**
 * Configuration source type
 * Indicates where a configuration value comes from
 */
export type ConfigSource = 'database' | 'environment' | 'default';

/**
 * Setting value with source information
 * Used to show where configuration values come from
 */
export interface SettingWithSource {
  /** Setting value */
  value: unknown;
  /** Where this value comes from */
  source: ConfigSource;
  /** Whether this value is sensitive (should be masked) */
  isSensitive: boolean;
  /** Whether this setting is read-only (e.g., from environment) */
  isReadOnly?: boolean;
}

// ============================================================================
// System Settings Types (Added 2026-01-23)
// ============================================================================

/**
 * System settings response
 * Contains core system configuration values with source info
 */
export interface SystemSettingsResponse {
  /** API base URL setting */
  apiBaseUrl: SettingWithSource;
  /** Subscription base URL setting */
  subscriptionBaseUrl: SettingWithSource;
  /** Frontend URL setting */
  frontendUrl: SettingWithSource;
  /** Business timezone setting */
  timezone: SettingWithSource;
}

/**
 * Request to update system settings
 * Note: apiBaseUrl is read-only and can only be configured via environment variable
 */
export interface UpdateSystemSettingsRequest {
  /** New subscription base URL */
  subscriptionBaseUrl?: string;
  /** New frontend URL */
  frontendUrl?: string;
}

// ============================================================================
// OAuth Settings Types (Added 2026-01-23)
// ============================================================================

/**
 * OAuth provider settings
 * Configuration for a single OAuth provider (Google, GitHub, etc.)
 */
export interface OAuthProviderSettings {
  /** Whether this OAuth provider is enabled */
  enabled: boolean;
  /** OAuth client ID */
  clientId: SettingWithSource;
  /** OAuth client secret (masked) */
  clientSecret: SettingWithSource;
  /** OAuth redirect URL */
  redirectUrl: SettingWithSource;
}

/**
 * OAuth settings response
 * Contains OAuth configuration for all providers
 */
export interface OAuthSettingsResponse {
  /** Google OAuth settings */
  google: OAuthProviderSettings;
  /** GitHub OAuth settings */
  github: OAuthProviderSettings;
}

/**
 * Request to update a single OAuth provider
 */
export interface UpdateOAuthProviderRequest {
  /** New client ID */
  clientId?: string;
  /** New client secret */
  clientSecret?: string;
  /** New redirect URL */
  redirectUrl?: string;
}

/**
 * Request to update OAuth settings
 * Update configuration for one or more OAuth providers
 */
export interface UpdateOAuthSettingsRequest {
  /** Google OAuth settings to update */
  google?: UpdateOAuthProviderRequest;
  /** GitHub OAuth settings to update */
  github?: UpdateOAuthProviderRequest;
}

// ============================================================================
// Email Settings Types (Added 2026-01-23)
// ============================================================================

/**
 * Email settings response
 * Contains SMTP configuration for sending emails
 */
export interface EmailSettingsResponse {
  /** SMTP server hostname */
  smtpHost: SettingWithSource;
  /** SMTP server port */
  smtpPort: SettingWithSource;
  /** SMTP username for authentication */
  smtpUser: SettingWithSource;
  /** SMTP password (masked) */
  smtpPassword: SettingWithSource;
  /** Email sender address */
  fromAddress: SettingWithSource;
  /** Email sender display name */
  fromName: SettingWithSource;
}

/**
 * Request to update email settings
 * All fields are optional - only provided fields will be updated
 */
export interface UpdateEmailSettingsRequest {
  /** New SMTP hostname */
  smtpHost?: string;
  /** New SMTP port */
  smtpPort?: number;
  /** New SMTP username */
  smtpUser?: string;
  /** New SMTP password */
  smtpPassword?: string;
  /** New from address */
  fromAddress?: string;
  /** New from name */
  fromName?: string;
}

/**
 * Request to test email connection
 * Sends a test email to verify SMTP configuration
 */
export interface EmailTestRequest {
  /** Email address to send test email to */
  recipientEmail: string;
}

/**
 * Email test result
 * Response from testing email connection
 */
export interface EmailTestResponse {
  /** Whether the test email was sent successfully */
  success: boolean;
  /** Error message if failed */
  error?: string;
}

// ============================================================================
// Setup Status Types (Added 2026-01-23)
// ============================================================================

/**
 * Setup status response
 * Used to check if first-time configuration is needed
 */
export interface SetupStatusResponse {
  /** Whether the system is configured */
  isConfigured: boolean;
  /** Whether setup wizard should be shown */
  requiresSetup: boolean;
  /** List of missing required settings */
  missingSettings: string[];
}

// ============================================================================
// Telegram Configuration Types
// ============================================================================

/**
 * Telegram bot configuration response
 * Used for admin Telegram notifications
 */
export interface TelegramConfigResponse {
  /** Whether Telegram notifications are enabled */
  enabled: boolean;
  /** Bot token (masked for security) */
  botToken: string;
  /** Webhook URL for receiving Telegram updates */
  webhookUrl: string;
  /** Webhook secret (masked for security) */
  webhookSecret: string;
  /** Link to start conversation with the bot */
  botLink?: string;
  /** Operation mode: 'webhook' or 'polling' */
  mode: string;
}

/**
 * Request to update Telegram configuration
 * All fields are optional - only provided fields will be updated
 */
export interface UpdateTelegramConfigRequest {
  /** Enable or disable Telegram notifications */
  enabled?: boolean;
  /** New bot token */
  botToken?: string;
  /** New webhook URL */
  webhookUrl?: string;
  /** New webhook secret */
  webhookSecret?: string;
}

/**
 * Request to test Telegram bot connection
 */
export interface TestTelegramConnectionRequest {
  /** Bot token to test (optional - if empty, uses saved token) */
  botToken?: string;
}

/**
 * Result of Telegram connection test
 */
export interface TelegramTestResult {
  /** Whether the connection test succeeded */
  success: boolean;
  /** Bot username if successful */
  botUsername?: string;
  /** Error message if failed */
  error?: string;
}

// ============================================================================
// USDT Settings Types (Added 2026-01-25, Updated 2026-01-26)
// ============================================================================

/**
 * USDT payment settings response
 *
 * Contains USDT payment configuration for admin management.
 * All settings include source information (database, environment, or default).
 *
 * ## Multi-Wallet Support (Updated 2026-01-26)
 *
 * The system now supports multiple receiving addresses per chain for load balancing
 * and avoiding amount suffix collisions. Configure multiple wallets to handle
 * higher transaction volumes.
 *
 * ## Configuration Guide
 *
 * ### Required Settings
 * - `enabled`: Must be true to accept USDT payments
 * - `polReceivingAddresses` or `trcReceivingAddresses`: At least one receiving address
 *
 * ### Optional but Recommended
 * - `polygonscanApiKey`: For faster Polygon transaction monitoring (5 req/s vs 0.2 req/s)
 * - `trongridApiKey`: For faster Tron transaction monitoring (10 req/s vs 1 req/s)
 *
 * ### Default Values
 * - `paymentTtlMinutes`: 10 (payment expires after 10 minutes)
 * - `polConfirmations`: 12 (~30 seconds for finality)
 * - `trcConfirmations`: 19 (~1 minute for finality)
 */
export interface USDTSettingsResponse {
  /**
   * Whether USDT payment is enabled
   * Must be true for users to see USDT payment options
   */
  enabled: SettingWithSource;

  /**
   * Polygon (MATIC) network receiving addresses
   * Array of addresses for multi-wallet support
   * Format: 0x followed by 40 hex characters
   * Example: ["0xc2132D05D31c914a87C6611C10748AEb04B58e8F"]
   * Updated 2026-01-26: Changed from single address to array
   */
  polReceivingAddresses: SettingWithSource;

  /**
   * Tron (TRC-20) network receiving addresses
   * Array of addresses for multi-wallet support
   * Format: T followed by 33 base58 characters
   * Example: ["TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"]
   * Updated 2026-01-26: Changed from single address to array
   */
  trcReceivingAddresses: SettingWithSource;

  /**
   * PolygonScan API key (masked in response)
   * Used for monitoring Polygon blockchain transactions
   * Without this key, rate limiting is more conservative (1 req/10s)
   * Free API keys available at: https://polygonscan.com/apis
   */
  polygonscanApiKey: SettingWithSource;

  /**
   * TronGrid API key (masked in response)
   * Used for monitoring Tron blockchain transactions
   * Without this key, rate limiting is more conservative (1 req/10s)
   * Free API keys available at: https://www.trongrid.io/
   */
  trongridApiKey: SettingWithSource;

  /**
   * Payment expiration time in minutes
   * Default: 10 minutes
   * Recommended range: 5-30 minutes
   */
  paymentTtlMinutes: SettingWithSource;

  /**
   * Required block confirmations for Polygon
   * Default: 12 (~30 seconds)
   * Higher values increase security but delay confirmation
   */
  polConfirmations: SettingWithSource;

  /**
   * Required block confirmations for Tron
   * Default: 19 (~1 minute)
   * Higher values increase security but delay confirmation
   */
  trcConfirmations: SettingWithSource;
}

/**
 * Request to update USDT settings
 *
 * All fields are optional - only provided fields will be updated.
 * Settings are validated before saving.
 *
 * ## Multi-Wallet Support (Updated 2026-01-26)
 *
 * Addresses are now arrays to support multiple wallets per chain.
 * The system distributes payments across configured addresses to
 * avoid amount suffix collisions.
 *
 * @example
 * ```typescript
 * // Enable USDT with multiple Polygon addresses
 * await updateUSDTSettings({
 *   enabled: true,
 *   polReceivingAddresses: [
 *     '0x1234...',
 *     '0x5678...',
 *   ],
 *   polygonscanApiKey: 'YOUR_API_KEY',
 * });
 *
 * // Enable both Polygon and Tron with multiple addresses
 * await updateUSDTSettings({
 *   enabled: true,
 *   polReceivingAddresses: ['0x1234...', '0x5678...'],
 *   trcReceivingAddresses: ['T1234...', 'T5678...'],
 *   paymentTtlMinutes: 10,
 * });
 *
 * // Disable USDT payments
 * await updateUSDTSettings({
 *   enabled: false,
 * });
 * ```
 */
export interface UpdateUSDTSettingsRequest {
  /**
   * Enable or disable USDT payments
   * When disabled, users won't see USDT payment options
   */
  enabled?: boolean;

  /**
   * New Polygon receiving addresses (array)
   * Each must be a valid Polygon address (0x + 40 hex chars)
   * Maximum 10 addresses allowed
   * Updated 2026-01-26: Changed from single address to array
   */
  polReceivingAddresses?: string[];

  /**
   * New Tron receiving addresses (array)
   * Each must be a valid Tron address (T + 33 base58 chars)
   * Maximum 10 addresses allowed
   * Updated 2026-01-26: Changed from single address to array
   */
  trcReceivingAddresses?: string[];

  /**
   * New PolygonScan API key
   * Get free key at: https://polygonscan.com/apis
   * Improves transaction monitoring speed (5 req/s vs 0.2 req/s)
   */
  polygonscanApiKey?: string;

  /**
   * New TronGrid API key
   * Get free key at: https://www.trongrid.io/
   * Improves transaction monitoring speed (10 req/s vs 1 req/s)
   */
  trongridApiKey?: string;

  /**
   * New payment TTL in minutes
   * Range: 5-30 recommended
   * Default: 10 minutes
   */
  paymentTtlMinutes?: number;

  /**
   * New required confirmations for Polygon
   * Default: 12 (recommended for security/speed balance)
   * Range: 1-100
   */
  polConfirmations?: number;

  /**
   * New required confirmations for Tron
   * Default: 19 (recommended for security/speed balance)
   * Range: 1-100
   */
  trcConfirmations?: number;
}
