/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend setting module
 * Last updated: 2026-01-06
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 *
 * This module provides system settings management for admin users.
 * Settings are organized by category (e.g., 'telegram', 'notification').
 */

// ============================================================================
// System Setting Types
// ============================================================================

/**
 * Single system setting response
 * Represents a configuration value stored in the system
 */
export interface SystemSettingResponse {
  /** Stripe-style setting ID */
  sid: string;
  /** Category name (e.g., 'telegram', 'notification') */
  category: string;
  /** Setting key within the category */
  key: string;
  /** Setting value (type depends on valueType) */
  value: unknown;
  /** Value type: 'string', 'bool', 'int', 'json' */
  valueType: string;
  /** Human-readable description of the setting */
  description: string;
  /** Whether the value is sensitive (will be masked in responses) */
  isSensitive: boolean;
  /** Last update timestamp */
  updatedAt: string;
}

/**
 * Category settings response
 * Returns all settings within a specific category
 */
export interface CategorySettingsResponse {
  /** Category name */
  category: string;
  /** List of settings in this category */
  settings: SystemSettingResponse[];
}

/**
 * Request to update a single setting value
 */
export interface UpdateSettingRequest {
  /** New value for the setting */
  value: unknown;
}

/**
 * Request to batch update multiple settings in a category
 */
export interface UpdateCategorySettingsRequest {
  /** Map of setting key to new value */
  settings: Record<string, unknown>;
}

// ============================================================================
// Telegram Configuration Types
// ============================================================================

/**
 * Telegram bot configuration response
 * Used for admin Telegram notifications
 */
export interface TelegramConfigResponse {
  /** Whether Telegram notifications are enabled */
  enabled: boolean;
  /** Bot token (masked for security) */
  botToken: string;
  /** Webhook URL for receiving Telegram updates */
  webhookUrl: string;
  /** Webhook secret (masked for security) */
  webhookSecret: string;
  /** Link to start conversation with the bot */
  botLink?: string;
  /** Operation mode: 'webhook' or 'polling' */
  mode: string;
}

/**
 * Request to update Telegram configuration
 * All fields are optional - only provided fields will be updated
 */
export interface UpdateTelegramConfigRequest {
  /** Enable or disable Telegram notifications */
  enabled?: boolean;
  /** New bot token */
  botToken?: string;
  /** New webhook URL */
  webhookUrl?: string;
  /** New webhook secret */
  webhookSecret?: string;
}

/**
 * Request to test Telegram bot connection
 */
export interface TestTelegramConnectionRequest {
  /** Bot token to test (optional - if empty, uses saved token) */
  botToken?: string;
}

/**
 * Result of Telegram connection test
 */
export interface TelegramTestResult {
  /** Whether the connection test succeeded */
  success: boolean;
  /** Bot username if successful */
  botUsername?: string;
  /** Error message if failed */
  error?: string;
}
