/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2026-01-26
 *
 * Payment API client for creating and managing payments.
 *
 * ## Supported Payment Methods
 *
 * | Method | Description | Flow |
 * |--------|-------------|------|
 * | `stripe` | Credit/Debit cards | Redirect to Stripe checkout |
 * | `alipay` | Alipay (支付宝) | Redirect or scan QR code |
 * | `wechat` | WeChat Pay (微信支付) | Scan QR code |
 * | `usdt_pol` | USDT on Polygon | Manual wallet transfer |
 * | `usdt_trc` | USDT on Tron | Manual wallet transfer |
 *
 * ## USDT Payment Integration Guide
 *
 * USDT payments work differently from traditional payment methods:
 *
 * 1. **Create Payment**: Call `createPayment()` with `usdt_pol` or `usdt_trc`
 * 2. **Display Instructions**: Show the receiving address and exact amount
 * 3. **User Transfer**: User sends USDT from their wallet
 * 4. **Auto-Confirmation**: Backend monitors blockchain and confirms payment
 *
 * ### Key Points for USDT Payments
 *
 * - Amount has a unique suffix (e.g., 10.123456) for payment identification
 * - User must transfer the EXACT amount shown
 * - User must select the correct network (Polygon or Tron) in their wallet
 * - Payment expires after 30 minutes by default
 * - Confirmation takes ~30 seconds (Polygon) or ~1 minute (Tron)
 */

import { apiClient } from '@/shared/lib/axios';
import type { APIResponse } from '@/shared/types/api.types';
import type {
  CreatePaymentRequest,
  CreatePaymentResponse,
} from './types';

// ============================================================================
// Payment APIs
// ============================================================================

/**
 * Create a new payment
 * POST /payments
 *
 * Creates a payment for a subscription. The response varies based on payment method:
 *
 * **Traditional Payments (stripe, alipay, wechat):**
 * - Returns `paymentUrl` - redirect user to complete payment
 * - May include `qrCode` for mobile scanning
 *
 * **USDT Payments (usdt_pol, usdt_trc):**
 * - Returns USDT-specific fields for wallet transfer
 * - No redirect needed - user transfers manually
 *
 * @param data - Payment creation request
 * @returns Payment details with payment URL or USDT payment info
 * @throws Error if payment creation fails (e.g., invalid subscription, USDT not enabled)
 *
 * @example
 * ```typescript
 * // Example 1: Create a Stripe payment
 * const stripePayment = await createPayment({
 *   subscriptionId: 123,
 *   billingCycle: 'annual',
 *   paymentMethod: 'stripe',
 *   returnUrl: 'https://app.example.com/payment/success',
 * });
 * // Redirect user to Stripe checkout
 * window.location.href = stripePayment.paymentUrl;
 * ```
 *
 * @example
 * ```typescript
 * // Example 2: Create a USDT payment on Polygon
 * import { extractUSDTDisplayInfo, getChainDisplayName } from './types';
 *
 * const usdtPayment = await createPayment({
 *   subscriptionId: 123,
 *   billingCycle: 'annual',
 *   paymentMethod: 'usdt_pol',
 * });
 *
 * // Check if this is a USDT payment
 * if (usdtPayment.chainType) {
 *   const displayInfo = extractUSDTDisplayInfo(usdtPayment);
 *   if (displayInfo) {
 *     // Render USDT payment UI
 *     showUSDTPaymentDialog({
 *       amount: displayInfo.formattedAmount,
 *       address: displayInfo.address,
 *       network: displayInfo.chainDisplayName,
 *       expiresAt: displayInfo.expiresAt,
 *     });
 *   }
 * }
 * ```
 *
 * @example
 * ```typescript
 * // Example 3: Full USDT payment flow with React
 * function PaymentPage({ subscriptionId }: { subscriptionId: number }) {
 *   const [payment, setPayment] = useState<CreatePaymentResponse | null>(null);
 *   const [loading, setLoading] = useState(false);
 *
 *   const handleUSDTPayment = async (chain: 'usdt_pol' | 'usdt_trc') => {
 *     setLoading(true);
 *     try {
 *       const result = await createPayment({
 *         subscriptionId,
 *         billingCycle: 'annual',
 *         paymentMethod: chain,
 *       });
 *       setPayment(result);
 *     } catch (error) {
 *       toast.error('Failed to create payment');
 *     } finally {
 *       setLoading(false);
 *     }
 *   };
 *
 *   if (payment?.chainType) {
 *     return (
 *       <USDTPaymentInstructions
 *         amount={payment.usdtAmount!.toFixed(6)}
 *         address={payment.receivingAddress!}
 *         chain={getChainDisplayName(payment.chainType)}
 *         expiresAt={payment.expiredAt}
 *         onCopyAddress={() => {
 *           navigator.clipboard.writeText(payment.receivingAddress!);
 *           toast.success('Address copied!');
 *         }}
 *       />
 *     );
 *   }
 *
 *   return (
 *     <div>
 *       <h2>Select Payment Method</h2>
 *       <button onClick={() => handleUSDTPayment('usdt_pol')}>
 *         Pay with USDT (Polygon) - Low fees
 *       </button>
 *       <button onClick={() => handleUSDTPayment('usdt_trc')}>
 *         Pay with USDT (Tron) - Widely supported
 *       </button>
 *     </div>
 *   );
 * }
 * ```
 */
export async function createPayment(
  data: CreatePaymentRequest
): Promise<CreatePaymentResponse> {
  const response = await apiClient.post<APIResponse<CreatePaymentResponse>>(
    '/payments',
    data
  );
  return response.data.data;
}

/**
 * Handle payment callback (internal use only)
 * POST /payments/callback
 *
 * Note: This endpoint is called by payment gateway providers (Stripe, Alipay, etc.)
 * and should not be called directly by client applications.
 *
 * For USDT payments, the backend automatically monitors blockchain transactions
 * and confirms payments - no callback is needed.
 */
