/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2026-01-26
 *
 * Payment SDK - Create and manage payments
 *
 * ## Quick Start
 *
 * ```typescript
 * import {
 *   createPayment,
 *   isUSDTPaymentMethod,
 *   extractUSDTDisplayInfo,
 *   getChainDisplayName,
 * } from '@/api/payment';
 *
 * // Create a payment
 * const payment = await createPayment({
 *   subscriptionId: 123,
 *   billingCycle: 'annual',
 *   paymentMethod: 'usdt_pol',
 * });
 *
 * // Handle USDT payment
 * if (payment.chainType) {
 *   const displayInfo = extractUSDTDisplayInfo(payment);
 *   console.log(`Send ${displayInfo.formattedAmount} USDT to ${displayInfo.address}`);
 * }
 * ```
 *
 * ## Exports
 *
 * ### Types
 * - `PaymentMethod` - Payment method enum
 * - `BillingCycle` - Billing cycle enum
 * - `CreatePaymentRequest` - Request to create payment
 * - `CreatePaymentResponse` - Payment creation result
 * - `USDTPaymentDisplayInfo` - Helper type for USDT UI
 *
 * ### Functions
 * - `createPayment()` - Create a new payment
 * - `isUSDTPaymentMethod()` - Check if method is USDT-based
 * - `getChainDisplayName()` - Get display name for chain
 * - `extractUSDTDisplayInfo()` - Extract USDT info for UI
 */

export * from './types';
export * from './client';
