/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 */

/**
 * Payment method type
 */
export type PaymentMethod = 'alipay' | 'wechat' | 'stripe';

/**
 * Create payment request
 * POST /payments
 */
export interface CreatePaymentRequest {
  subscriptionId: number;
  paymentMethod: PaymentMethod;
  returnUrl?: string;
}

/**
 * Create payment response
 */
export interface CreatePaymentResponse {
  paymentId: number;
  orderNo: string;
  paymentUrl: string;
  qrCode?: string;
  expiredAt: string;
}
