/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2026-01-26
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 */

// ============================================================================
// Payment Method Types
// ============================================================================

/**
 * Payment method type
 *
 * Supported payment methods:
 * - `alipay`: Alipay (支付宝)
 * - `wechat`: WeChat Pay (微信支付)
 * - `stripe`: Stripe (credit/debit cards)
 * - `usdt_pol`: USDT on Polygon network (MATIC chain, low fees)
 * - `usdt_trc`: USDT on Tron network (TRC-20, widely supported)
 *
 * @example
 * ```typescript
 * // Traditional payment
 * const method: PaymentMethod = 'stripe';
 *
 * // Crypto payment - Polygon (recommended for low fees)
 * const method: PaymentMethod = 'usdt_pol';
 *
 * // Crypto payment - Tron (widely supported by exchanges)
 * const method: PaymentMethod = 'usdt_trc';
 * ```
 */
export type PaymentMethod = 'alipay' | 'wechat' | 'stripe' | 'usdt_pol' | 'usdt_trc';

/**
 * Billing cycle type for payment
 *
 * Available billing cycles:
 * - `monthly`: 1 month
 * - `quarterly`: 3 months
 * - `semi_annual`: 6 months
 * - `yearly`: 12 months
 *
 * Note: Use the same BillingCycle type from subscription module for consistency.
 * Import from '@/api/subscription' instead of defining locally.
 */
export type PaymentBillingCycle = 'monthly' | 'quarterly' | 'semi_annual' | 'yearly';

/**
 * Helper to check if a payment method is USDT-based
 *
 * @example
 * ```typescript
 * const isUSDT = isUSDTPaymentMethod('usdt_pol'); // true
 * const isUSDT = isUSDTPaymentMethod('stripe');   // false
 * ```
 */
export const isUSDTPaymentMethod = (method: PaymentMethod): boolean => {
  return method === 'usdt_pol' || method === 'usdt_trc';
};

/**
 * Get display name for chain type
 *
 * @example
 * ```typescript
 * getChainDisplayName('pol'); // 'Polygon (MATIC)'
 * getChainDisplayName('trc'); // 'Tron (TRC-20)'
 * ```
 */
export const getChainDisplayName = (chainType: string): string => {
  switch (chainType) {
    case 'pol':
      return 'Polygon (MATIC)';
    case 'trc':
      return 'Tron (TRC-20)';
    default:
      return chainType;
  }
};

// ============================================================================
// Payment Request/Response Types
// ============================================================================

/**
 * Create payment request
 * POST /payments
 *
 * Creates a new payment for a subscription. The response differs based on
 * the payment method:
 *
 * **For traditional payments (alipay, wechat, stripe):**
 * - Returns a `paymentUrl` to redirect the user
 * - May include a `qrCode` for mobile scanning
 *
 * **For USDT payments (usdt_pol, usdt_trc):**
 * - Returns USDT-specific fields for wallet transfer
 * - `usdtAmount`: Exact amount to transfer (includes unique suffix for identification)
 * - `receivingAddress`: Wallet address to send USDT to
 * - `chainType`: Blockchain network ('pol' or 'trc')
 * - `exchangeRate`: CNY/USDT rate used for conversion (display only)
 *
 * @example
 * ```typescript
 * // Create a Stripe payment
 * const stripePayment: CreatePaymentRequest = {
 *   subscriptionId: 123,
 *   billingCycle: 'annual',
 *   paymentMethod: 'stripe',
 *   returnUrl: 'https://app.example.com/payment/success',
 * };
 *
 * // Create a USDT payment on Polygon
 * const usdtPayment: CreatePaymentRequest = {
 *   subscriptionId: 123,
 *   billingCycle: 'annual',
 *   paymentMethod: 'usdt_pol',
 *   // returnUrl not needed for USDT - user transfers manually
 * };
 * ```
 */
export interface CreatePaymentRequest {
  /**
   * Subscription SID (Stripe-style ID: sub_xxx)
   * Must be a valid subscription belonging to the current user
   *
   * Example: "sub_abc123def456"
   */
  subscriptionId: string;

  /**
   * Billing cycle for the subscription
   * Determines the payment amount and subscription duration
   *
   * Note: Only cycles with defined pricing are allowed
   */
  billingCycle: PaymentBillingCycle;

  /**
   * Payment method to use
   * For USDT payments, determines which blockchain network to use
   */
  paymentMethod: PaymentMethod;

  /**
   * URL to redirect after payment completion (optional)
   * Only used for traditional payments (alipay, wechat, stripe)
   * Not needed for USDT payments
   */
  returnUrl?: string;
}

/**
 * Create payment response
 *
 * Contains payment details. For USDT payments, includes additional fields
 * needed to display the payment instructions to the user.
 *
 * ## USDT Payment Flow
 *
 * 1. User selects USDT payment method (Polygon or Tron)
 * 2. Frontend displays payment details:
 *    - Receiving address (wallet to send to)
 *    - Exact USDT amount (must match exactly for auto-confirmation)
 *    - Chain type (remind user to select correct network)
 *    - Expiration time (payment must be sent before this time)
 * 3. User transfers USDT from their wallet
 * 4. Backend monitors blockchain for incoming transaction
 * 5. After sufficient confirmations, payment is auto-confirmed
 *
 * ## Important Notes for USDT Payments
 *
 * - **Exact amount required**: The `usdtAmount` includes a unique suffix
 *   (e.g., 10.123456 instead of 10.00) to identify this specific payment.
 *   User MUST transfer the exact amount shown.
 * - **Correct network**: User must select the correct blockchain network
 *   in their wallet (Polygon or Tron) matching the `chainType`.
 * - **Confirmation time**: Polygon requires ~12 confirmations (~30 seconds),
 *   Tron requires ~19 confirmations (~1 minute).
 * - **Expiration**: Payment must be sent before `expiredAt`. Default is 30 minutes.
 *
 * @example
 * ```typescript
 * // Handle USDT payment response
 * const response = await createPayment({
 *   subscriptionId: 123,
 *   billingCycle: 'annual',
 *   paymentMethod: 'usdt_pol',
 * });
 *
 * if (response.chainType) {
 *   // This is a USDT payment
 *   console.log(`Send exactly ${response.usdtAmount} USDT`);
 *   console.log(`To address: ${response.receivingAddress}`);
 *   console.log(`Network: ${getChainDisplayName(response.chainType)}`);
 *   console.log(`Expires at: ${response.expiredAt}`);
 *   console.log(`Rate: 1 USDT = ¥${response.exchangeRate}`);
 * } else {
 *   // Traditional payment - redirect user
 *   window.location.href = response.paymentUrl;
 * }
 * ```
 */
export interface CreatePaymentResponse {
  /**
   * Unique payment ID
   * Can be used to query payment status
   */
  paymentId: number;

  /**
   * Order number for reference
   * Format: PAY_YYYYMMDD_XXXXXX
   */
  orderNo: string;

  /**
   * URL to complete payment
   * For traditional payments: redirect user to this URL
   * For USDT payments: not used (empty string)
   */
  paymentUrl: string;

  /**
   * QR code data URL for payment (optional)
   * Only present for alipay/wechat payments
   * Can be displayed as an image: <img src={qrCode} />
   */
  qrCode?: string;

  /**
   * Payment expiration time (ISO 8601 format)
   * Payment must be completed before this time
   * Example: "2026-01-26T15:30:00Z"
   */
  expiredAt: string;

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // USDT-specific fields (only present when paymentMethod is usdt_pol or usdt_trc)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  /**
   * Blockchain chain type (USDT only)
   * - 'pol': Polygon network (MATIC chain)
   * - 'trc': Tron network (TRC-20)
   *
   * Use `getChainDisplayName()` to get user-friendly name
   */
  chainType?: string;

  /**
   * Exact USDT amount to transfer (USDT only)
   *
   * ⚠️ IMPORTANT: This amount includes a unique suffix for payment identification.
   * User MUST transfer this EXACT amount, not a rounded value.
   *
   * Example: 10.123456 USDT (not 10.00 or 10.12)
   *
   * Display with 6 decimal places: `usdtAmount.toFixed(6)`
   */
  usdtAmount?: number;

  /**
   * Wallet address to receive USDT payment (USDT only)
   *
   * - Polygon addresses start with '0x' (42 characters)
   * - Tron addresses start with 'T' (34 characters)
   *
   * Display this prominently and provide a copy button for user convenience.
   */
  receivingAddress?: string;

  /**
   * Exchange rate used for CNY to USDT conversion (USDT only)
   *
   * This is the rate at the time of payment creation.
   * Display for user reference: "1 USDT ≈ ¥{exchangeRate}"
   *
   * Note: This is for display only. The actual USDT amount is fixed
   * once the payment is created.
   */
  exchangeRate?: number;
}

// ============================================================================
// Helper Types for UI
// ============================================================================

/**
 * USDT payment display info
 * Helper type for rendering USDT payment UI
 */
export interface USDTPaymentDisplayInfo {
  /** Formatted USDT amount (6 decimal places) */
  formattedAmount: string;
  /** Display name for chain (e.g., "Polygon (MATIC)") */
  chainDisplayName: string;
  /** Receiving wallet address */
  address: string;
  /** Exchange rate display (e.g., "¥7.25") */
  rateDisplay: string;
  /** Time remaining until expiration */
  expiresAt: Date;
}

/**
 * Extract USDT display info from payment response
 *
 * @example
 * ```typescript
 * const response = await createPayment({ ... paymentMethod: 'usdt_pol' });
 * const displayInfo = extractUSDTDisplayInfo(response);
 *
 * if (displayInfo) {
 *   return (
 *     <div>
 *       <p>Amount: {displayInfo.formattedAmount} USDT</p>
 *       <p>Network: {displayInfo.chainDisplayName}</p>
 *       <p>Address: {displayInfo.address}</p>
 *       <p>Rate: 1 USDT ≈ {displayInfo.rateDisplay}</p>
 *     </div>
 *   );
 * }
 * ```
 */
export const extractUSDTDisplayInfo = (
  response: CreatePaymentResponse
): USDTPaymentDisplayInfo | null => {
  if (!response.chainType || !response.usdtAmount || !response.receivingAddress) {
    return null;
  }

  return {
    formattedAmount: response.usdtAmount.toFixed(6),
    chainDisplayName: getChainDisplayName(response.chainType),
    address: response.receivingAddress,
    rateDisplay: response.exchangeRate ? `¥${response.exchangeRate.toFixed(2)}` : 'N/A',
    expiresAt: new Date(response.expiredAt),
  };
};
