/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2026-01-20
 */

// Export all modules
// Note: Some types may conflict (e.g., User from auth and user modules, RefreshTokenResponse from auth and subscription)
// Import from specific modules when needed to avoid ambiguity

// Auth module (exclude User to avoid conflict with user module)
export {
  register,
  login,
  verifyEmail,
  forgotPassword,
  resetPassword,
  getOAuthUrl,
  refreshToken,
  logout,
  getCurrentUser,
  getVersion,
} from './auth/client';

export type {
  RegisterRequest,
  RegisterResponse,
  LoginRequest,
  LoginResponse,
  VerifyEmailRequest,
  ForgotPasswordRequest,
  ResetPasswordRequest,
  RefreshTokenRequest,
  RefreshTokenResponse as AuthRefreshTokenResponse,
  UserDisplayInfo,
  VersionResponse,
} from './auth/types';

// User module (exclude types that conflict with profile module)
export {
  createUser,
  getUserById,
  getUserByEmail,
  updateUser,
  deleteUser,
  listUsers,
  adminResetPassword,
} from './user/client';

export type {
  CreateUserRequest,
  UpdateUserRequest,
  ListUsersParams,
  UserResponse,
  UserMetadata,
  PaginationResponse,
  ListUsersResponse,
  AdminResetPasswordRequest,
  UpdateProfileRequest as UserUpdateProfileRequest,
  ChangePasswordRequest as UserChangePasswordRequest,
} from './user/types';

// Profile module
export * from './profile';
export * from './node';
export * from './forward';
export * from './notification';
export * from './payment';

// Resource module (exclude BatchOperationResult to avoid conflict with forward module)
export {
  createResourceGroup,
  getResourceGroup,
  listResourceGroups,
  updateResourceGroup,
  deleteResourceGroup,
  activateResourceGroup,
  deactivateResourceGroup,
  addNodesToGroup,
  removeNodesFromGroup,
  listGroupNodes,
  addForwardAgentsToGroup,
  removeForwardAgentsFromGroup,
  listGroupForwardAgents,
  addForwardRulesToGroup,
  removeForwardRulesFromGroup,
  listGroupForwardRules,
} from './resource/client';

export type {
  ResourceGroup,
  ResourceGroupStatus,
  CreateResourceGroupRequest,
  UpdateResourceGroupRequest,
  ListResourceGroupsParams,
  AddNodesToGroupRequest,
  RemoveNodesFromGroupRequest,
  AddForwardAgentsToGroupRequest,
  RemoveForwardAgentsToGroupRequest,
  AddForwardRulesToGroupRequest,
  RemoveForwardRulesFromGroupRequest,
  NodeSummaryResponse,
  ForwardAgentSummaryResponse,
  ForwardRuleSummaryResponse,
  // Rename to avoid conflict with forward module
  BatchOperationResult as ResourceBatchOperationResult,
  BatchOperationError as ResourceBatchOperationError,
  ListGroupMembersParams,
} from './resource/types';

// Admin module (traffic statistics)
export * from './admin';

// Note: External Forward module has been removed (2026-01-20)
// External forward rules are now part of the unified ForwardRule model with rule_type='external'
// Use the 'forward' module instead

// Subscription module (exclude RefreshTokenResponse to avoid conflict with auth module)
export {
  createSubscription,
  getSubscription,
  listSubscriptions,
  updateSubscriptionStatus,
  changePlan,
  resetSubscriptionLink,
  getPublicPlans,
  getPlan,
  listPlans,
  createPlan,
  updatePlan,
  updatePlanStatus,
  getPlanPricings,
  generateToken,
  listTokens,
  revokeToken,
  refreshToken as refreshSubscriptionToken,
  getTrafficStats,
  // Admin Subscription APIs
  adminCreateSubscription,
  adminGetSubscription,
  adminListSubscriptions,
  adminUpdateSubscriptionStatus,
  adminChangeSubscriptionPlan,
} from './subscription/client';

export type {
  Subscription,
  SubscriptionStatus,
  SubscriptionPlan,
  PlanStatus,
  PlanType,
  PricingOption,
  BillingCycle,
  SubscriptionToken,
  TokenScope,
  CreateSubscriptionRequest,
  CreateSubscriptionResponse,
  UpdateSubscriptionStatusRequest,
  ChangePlanRequest,
  ListSubscriptionsParams,
  PricingOptionInput,
  CreatePlanRequest,
  UpdatePlanRequest,
  UpdatePlanStatusRequest,
  ListPlansParams,
  GenerateTokenRequest,
  GenerateTokenResponse,
  RefreshTokenResponse as SubscriptionRefreshTokenResponse,
  ListTokensParams,
  GetTrafficStatsParams,
  TrafficStatsRecord,
  TrafficSummary,
  TrafficStatsResponse,
  // Admin Subscription types
  AdminCreateSubscriptionRequest,
  AdminCreateSubscriptionResponse,
  AdminUpdateSubscriptionStatusRequest,
  AdminChangePlanRequest,
  AdminListSubscriptionsParams,
} from './subscription/types';

