/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 */

// Export all modules
// Note: Some types may conflict (e.g., User from auth and user modules, RefreshTokenResponse from auth and subscription)
// Import from specific modules when needed to avoid ambiguity

// Auth module (exclude User to avoid conflict with user module)
export {
  register,
  login,
  verifyEmail,
  forgotPassword,
  resetPassword,
  getOAuthUrl,
  refreshToken,
  logout,
  getCurrentUser,
} from './auth/client';

export type {
  RegisterRequest,
  RegisterResponse,
  LoginRequest,
  LoginResponse,
  VerifyEmailRequest,
  ForgotPasswordRequest,
  ResetPasswordRequest,
  RefreshTokenRequest,
  RefreshTokenResponse as AuthRefreshTokenResponse,
  UserDisplayInfo,
  User,
  OAuthProvider,
  OAuthCallbackMessage,
} from './auth/types';

// User module
export * from './user';

// Other modules
export * from './profile';
export * from './node';
export * from './forward';
export * from './notification';
export * from './payment';

// Subscription module (exclude RefreshTokenResponse to avoid conflict with auth module)
export {
  createSubscription,
  getSubscription,
  listSubscriptions,
  updateSubscriptionStatus,
  changePlan,
  getPublicPlans,
  getPlan,
  listPlans,
  createPlan,
  updatePlan,
  updatePlanStatus,
  getPlanPricings,
  generateToken,
  listTokens,
  revokeToken,
  refreshSubscriptionToken,
} from './subscription/client';

export type {
  Subscription,
  SubscriptionStatus,
  SubscriptionPlan,
  PlanStatus,
  PricingOption,
  BillingCycle,
  SubscriptionToken,
  TokenScope,
  CreateSubscriptionRequest,
  CreateSubscriptionResponse,
  UpdateSubscriptionStatusRequest,
  ChangePlanRequest,
  ListSubscriptionsParams,
  CreatePlanRequest,
  UpdatePlanRequest,
  UpdatePlanStatusRequest,
  ListPlansParams,
  GenerateTokenRequest,
  GenerateTokenResponse,
  RefreshTokenResponse as SubscriptionRefreshTokenResponse,
  ListTokensParams,
} from './subscription/types';

// Admin module exports with namespace to avoid conflicts
export {
  adminCreateSubscription,
  adminGetSubscription,
  adminListSubscriptions,
  adminUpdateSubscriptionStatus,
  adminChangeSubscriptionPlan,
} from './admin/client';

export type {
  AdminCreateSubscriptionRequest,
  AdminCreateSubscriptionResponse,
  AdminUpdateSubscriptionStatusRequest,
  AdminChangePlanRequest,
  AdminListSubscriptionsParams,
} from './admin/types';
