/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2025-12-22
 */

// Export all modules
// Note: Some types may conflict (e.g., User from auth and user modules, RefreshTokenResponse from auth and subscription)
// Import from specific modules when needed to avoid ambiguity

// Auth module (exclude User to avoid conflict with user module)
export {
  register,
  login,
  verifyEmail,
  forgotPassword,
  resetPassword,
  getOAuthUrl,
  refreshToken,
  logout,
  getCurrentUser,
} from './auth/client';

export type {
  RegisterRequest,
  RegisterResponse,
  LoginRequest,
  LoginResponse,
  VerifyEmailRequest,
  ForgotPasswordRequest,
  ResetPasswordRequest,
  RefreshTokenRequest,
  RefreshTokenResponse as AuthRefreshTokenResponse,
  UserDisplayInfo,
} from './auth/types';

// User module (exclude types that conflict with profile module)
export {
  createUser,
  getUserById,
  getUserByEmail,
  updateUser,
  deleteUser,
  listUsers,
  adminResetPassword,
} from './user/client';

export type {
  CreateUserRequest,
  UpdateUserRequest,
  ListUsersParams,
  UserResponse,
  UserMetadata,
  PaginationResponse,
  ListUsersResponse,
  AdminResetPasswordRequest,
  UpdateProfileRequest as UserUpdateProfileRequest,
  ChangePasswordRequest as UserChangePasswordRequest,
} from './user/types';

// Profile module
export * from './profile';
export * from './node';
export * from './forward';
export * from './notification';
export * from './payment';
export * from './resource';

// Admin module (traffic statistics)
export * from './admin';

// Subscription module (exclude RefreshTokenResponse to avoid conflict with auth module)
export {
  createSubscription,
  getSubscription,
  listSubscriptions,
  updateSubscriptionStatus,
  changePlan,
  resetSubscriptionLink,
  getPublicPlans,
  getPlan,
  listPlans,
  createPlan,
  updatePlan,
  updatePlanStatus,
  getPlanPricings,
  generateToken,
  listTokens,
  revokeToken,
  refreshToken as refreshSubscriptionToken,
  getTrafficStats,
  // Admin Subscription APIs
  adminCreateSubscription,
  adminGetSubscription,
  adminListSubscriptions,
  adminUpdateSubscriptionStatus,
  adminChangeSubscriptionPlan,
} from './subscription/client';

export type {
  Subscription,
  SubscriptionStatus,
  SubscriptionPlan,
  PlanStatus,
  PlanType,
  PricingOption,
  BillingCycle,
  SubscriptionToken,
  TokenScope,
  CreateSubscriptionRequest,
  CreateSubscriptionResponse,
  UpdateSubscriptionStatusRequest,
  ChangePlanRequest,
  ListSubscriptionsParams,
  PricingOptionInput,
  CreatePlanRequest,
  UpdatePlanRequest,
  UpdatePlanStatusRequest,
  ListPlansParams,
  GenerateTokenRequest,
  GenerateTokenResponse,
  RefreshTokenResponse as SubscriptionRefreshTokenResponse,
  ListTokensParams,
  GetTrafficStatsParams,
  TrafficStatsRecord,
  TrafficSummary,
  TrafficStatsResponse,
  // Admin Subscription types
  AdminCreateSubscriptionRequest,
  AdminCreateSubscriptionResponse,
  AdminUpdateSubscriptionStatusRequest,
  AdminChangePlanRequest,
  AdminListSubscriptionsParams,
} from './subscription/types';

