/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 */

import { apiClient } from '@/shared/lib/axios';
import type { APIResponse, ListResponse } from '@/shared/types/api.types';
import type {
  Announcement,
  Notification,
  NotificationTemplate,
  CreateAnnouncementRequest,
  UpdateAnnouncementRequest,
  UpdateAnnouncementStatusRequest,
  ListAnnouncementsParams,
  ListPublicAnnouncementsParams,
  ListNotificationsParams,
  UpdateNotificationStatusRequest,
  UpdateAllNotificationsStatusRequest,
  UnreadCountResponse,
  CreateTemplateRequest,
  ListTemplatesParams,
  RenderTemplateRequest,
  RenderTemplateResponse,
} from './types';

// ============================================================================
// Announcement APIs
// ============================================================================

/**
 * Create a new announcement (admin only)
 * POST /announcements
 */
export async function createAnnouncement(
  data: CreateAnnouncementRequest
): Promise<Announcement> {
  const response = await apiClient.post<APIResponse<Announcement>>(
    '/announcements',
    data
  );
  return response.data.data;
}

/**
 * Get announcement by ID
 * GET /announcements/:id
 */
export async function getAnnouncement(id: number): Promise<Announcement> {
  const response = await apiClient.get<APIResponse<Announcement>>(
    `/announcements/${id}`
  );
  return response.data.data;
}

/**
 * Update announcement by ID (admin only)
 * PUT /announcements/:id
 */
export async function updateAnnouncement(
  id: number,
  data: UpdateAnnouncementRequest
): Promise<Announcement> {
  const response = await apiClient.put<APIResponse<Announcement>>(
    `/announcements/${id}`,
    data
  );
  return response.data.data;
}

/**
 * Update announcement status (admin only)
 * PATCH /announcements/:id/status
 */
export async function updateAnnouncementStatus(
  id: number,
  data: UpdateAnnouncementStatusRequest
): Promise<Announcement> {
  const response = await apiClient.patch<APIResponse<Announcement>>(
    `/announcements/${id}/status`,
    data
  );
  return response.data.data;
}

/**
 * Delete announcement by ID (admin only)
 * DELETE /announcements/:id
 */
export async function deleteAnnouncement(id: number): Promise<void> {
  await apiClient.delete<APIResponse<null>>(`/announcements/${id}`);
}

/**
 * List announcements (admin only)
 * GET /announcements
 */
export async function listAnnouncements(
  params?: ListAnnouncementsParams
): Promise<ListResponse<Announcement>> {
  const response = await apiClient.get<APIResponse<ListResponse<Announcement>>>(
    '/announcements',
    { params }
  );
  return response.data.data;
}

/**
 * List public announcements (no auth required)
 * GET /public/announcements
 */
export async function listPublicAnnouncements(
  params?: ListPublicAnnouncementsParams
): Promise<ListResponse<Announcement>> {
  const response = await apiClient.get<APIResponse<ListResponse<Announcement>>>(
    '/public/announcements',
    { params }
  );
  return response.data.data;
}

// ============================================================================
// Notification APIs
// ============================================================================

/**
 * List user's notifications
 * GET /notifications
 */
export async function listNotifications(
  params?: ListNotificationsParams
): Promise<ListResponse<Notification>> {
  const response = await apiClient.get<APIResponse<ListResponse<Notification>>>(
    '/notifications',
    { params }
  );
  return response.data.data;
}

/**
 * Get unread notification count
 * GET /notifications/unread-count
 */
export async function getUnreadCount(): Promise<UnreadCountResponse> {
  const response = await apiClient.get<APIResponse<UnreadCountResponse>>(
    '/notifications/unread-count'
  );
  return response.data.data;
}

/**
 * Update notification status (mark as read or archive)
 * PATCH /notifications/:id/status
 */
export async function updateNotificationStatus(
  id: number,
  data: UpdateNotificationStatusRequest
): Promise<void> {
  await apiClient.patch<APIResponse<null>>(
    `/notifications/${id}/status`,
    data
  );
}

/**
 * Mark all notifications as read
 * PATCH /notifications/status
 */
export async function updateAllNotificationsStatus(
  data: UpdateAllNotificationsStatusRequest
): Promise<void> {
  await apiClient.patch<APIResponse<null>>('/notifications/status', data);
}

/**
 * Delete notification by ID
 * DELETE /notifications/:id
 */
export async function deleteNotification(id: number): Promise<void> {
  await apiClient.delete<APIResponse<null>>(`/notifications/${id}`);
}

// ============================================================================
// Notification Template APIs
// ============================================================================

/**
 * Create a new notification template (admin only)
 * POST /notification-templates
 */
export async function createTemplate(
  data: CreateTemplateRequest
): Promise<NotificationTemplate> {
  const response = await apiClient.post<APIResponse<NotificationTemplate>>(
    '/notification-templates',
    data
  );
  return response.data.data;
}

/**
 * List notification templates
 * GET /notification-templates
 */
export async function listTemplates(
  params?: ListTemplatesParams
): Promise<NotificationTemplate[]> {
  const response = await apiClient.get<APIResponse<NotificationTemplate[]>>(
    '/notification-templates',
    { params }
  );
  return response.data.data;
}

/**
 * Render notification template with variables
 * POST /notification-templates/render
 */
export async function renderTemplate(
  data: RenderTemplateRequest
): Promise<RenderTemplateResponse> {
  const response = await apiClient.post<APIResponse<RenderTemplateResponse>>(
    '/notification-templates/render',
    data
  );
  return response.data.data;
}
