/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2026-01-30
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 */

/**
 * Announcement entity
 * Updated 2026-01-29: Changed id from number to string (SID format: ann_xxx)
 * Updated 2026-01-29: Added isRead field for tracking user read status
 */
export interface Announcement {
  id: string; // Updated: Now uses SID format (ann_xxx)
  title: string;
  content: string;
  contentHtml?: string;
  type: AnnouncementType;
  status: AnnouncementStatus;
  priority: number;
  scheduledAt?: string;
  expiresAt?: string;
  viewCount: number;
  createdAt: string;
  updatedAt: string;
  isRead?: boolean; // Added 2026-01-29: User read status (only returned for authenticated users)
}

/**
 * Announcement type
 */
export type AnnouncementType = 'system' | 'maintenance' | 'feature' | 'promotion';

/**
 * Announcement status
 */
export type AnnouncementStatus = 'draft' | 'published' | 'archived';

/**
 * Create announcement request
 * POST /announcements
 */
export interface CreateAnnouncementRequest {
  title: string;
  content: string;
  type: AnnouncementType;
  priority?: number;
  scheduledAt?: string;
  expiresAt?: string;
}

/**
 * Update announcement request
 * PUT /announcements/:id
 */
export interface UpdateAnnouncementRequest {
  title?: string;
  content?: string;
  type?: AnnouncementType;
  priority?: number;
  scheduledAt?: string;
  expiresAt?: string;
}

/**
 * Update announcement status request
 * PATCH /announcements/:id/status
 * Updated 2026-01-30: Removed sendNotification field (announcements no longer create notifications)
 */
export interface UpdateAnnouncementStatusRequest {
  status: AnnouncementStatus;
}

/**
 * List announcements params
 * GET /announcements
 */
export interface ListAnnouncementsParams {
  page?: number;
  pageSize?: number;
  type?: AnnouncementType;
  status?: AnnouncementStatus;
}

/**
 * List public announcements params
 * GET /public/announcements
 */
export interface ListPublicAnnouncementsParams {
  page?: number;
  pageSize?: number;
}

/**
 * Notification entity
 */
export interface Notification {
  id: number;
  userId: number;
  type: string;
  title: string;
  content: string;
  relatedId?: number;
  readStatus: NotificationReadStatus;
  archivedAt?: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * Notification read status
 */
export type NotificationReadStatus = 'read' | 'unread';

/**
 * List notifications params
 * GET /notifications
 */
export interface ListNotificationsParams {
  limit?: number;
  offset?: number;
  status?: NotificationReadStatus;
}

/**
 * Update notification status request
 * PATCH /notifications/:id/status
 */
export interface UpdateNotificationStatusRequest {
  status: 'read' | 'archived';
}

/**
 * Update all notifications status request
 * PATCH /notifications/status
 */
export interface UpdateAllNotificationsStatusRequest {
  status: 'read';
}

/**
 * Unread count response
 */
export interface UnreadCountResponse {
  count: number;
}

/**
 * Notification template entity
 */
export interface NotificationTemplate {
  id: number;
  templateType: string;
  name: string;
  title: string;
  content: string;
  variables?: string[];
  enabled: boolean;
  createdAt: string;
  updatedAt: string;
}

/**
 * Create template request
 * POST /notification-templates
 */
export interface CreateTemplateRequest {
  templateType: string;
  name: string;
  title: string;
  content: string;
  variables?: string[];
  enabled?: boolean;
}

/**
 * List templates params
 * GET /notification-templates
 */
export interface ListTemplatesParams {
  page?: number;
  pageSize?: number;
  enabled?: boolean;
}

/**
 * Render template request
 * POST /notification-templates/render
 */
export interface RenderTemplateRequest {
  templateType: string;
  variables: Record<string, unknown>;
}

/**
 * Render template response
 */
export interface RenderTemplateResponse {
  title: string;
  content: string;
}
