/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend - internal/interfaces/http/handlers/admin/resourcegrouphandler.go
 * Last updated: 2025-12-19
 *
 * Recent changes:
 * - 2025-12-19: Changed all id parameters from number|string to string only (SID format: rg_xxx)
 * - 2025-12-19: Removed getResourceGroupBySid (route removed, /:id now accepts SID directly)
 */

import { apiClient } from '@/shared/lib/axios';
import type { APIResponse, ListResponse } from '@/shared/types/api.types';
import type {
  ResourceGroup,
  CreateResourceGroupRequest,
  UpdateResourceGroupRequest,
  ListResourceGroupsParams,
  AddNodesToGroupRequest,
  RemoveNodesFromGroupRequest,
  AddForwardAgentsToGroupRequest,
  RemoveForwardAgentsToGroupRequest,
  NodeSummaryResponse,
  ForwardAgentSummaryResponse,
  BatchOperationResult,
  ListGroupMembersParams,
} from './types';

// ============================================================================
// Admin Resource Group APIs
// All endpoints require Admin authentication
// Updated: 2025-12-19 - All :id parameters now use Stripe-style SID (rg_xxx)
// ============================================================================

/**
 * Create resource group (Admin)
 * POST /admin/resource-groups
 * @requires Authentication, Admin
 */
export async function createResourceGroup(
  data: CreateResourceGroupRequest
): Promise<ResourceGroup> {
  const response = await apiClient.post<APIResponse<ResourceGroup>>(
    '/admin/resource-groups',
    data
  );
  return response.data.data;
}

/**
 * Get resource group by SID (Admin)
 * GET /admin/resource-groups/:id
 * @requires Authentication, Admin
 * @param id - Resource group's Stripe-style ID (rg_xxx)
 * Updated: 2025-12-19 - Changed id type to string only (SID format)
 */
export async function getResourceGroup(id: string): Promise<ResourceGroup> {
  const response = await apiClient.get<APIResponse<ResourceGroup>>(
    `/admin/resource-groups/${id}`
  );
  return response.data.data;
}

/**
 * List resource groups (Admin)
 * GET /admin/resource-groups
 * @requires Authentication, Admin
 */
export async function listResourceGroups(
  params?: ListResourceGroupsParams
): Promise<ListResponse<ResourceGroup>> {
  const response = await apiClient.get<APIResponse<ListResponse<ResourceGroup>>>(
    '/admin/resource-groups',
    { params }
  );
  return response.data.data;
}

/**
 * Update resource group (Admin)
 * PATCH /admin/resource-groups/:id
 * @requires Authentication, Admin
 * @param id - Resource group's Stripe-style ID (rg_xxx)
 * Updated: 2025-12-19 - Changed id type to string only (SID format)
 */
export async function updateResourceGroup(
  id: string,
  data: UpdateResourceGroupRequest
): Promise<ResourceGroup> {
  const response = await apiClient.patch<APIResponse<ResourceGroup>>(
    `/admin/resource-groups/${id}`,
    data
  );
  return response.data.data;
}

/**
 * Delete resource group (Admin)
 * DELETE /admin/resource-groups/:id
 * @requires Authentication, Admin
 * @param id - Resource group's Stripe-style ID (rg_xxx)
 * Updated: 2025-12-19 - Changed id type to string only (SID format)
 */
export async function deleteResourceGroup(id: string): Promise<void> {
  await apiClient.delete(`/admin/resource-groups/${id}`);
}

/**
 * Activate resource group (Admin)
 * POST /admin/resource-groups/:id/activate
 * @requires Authentication, Admin
 * @param id - Resource group's Stripe-style ID (rg_xxx)
 * Updated: 2025-12-19 - Changed id type to string only (SID format)
 */
export async function activateResourceGroup(
  id: string
): Promise<ResourceGroup> {
  const response = await apiClient.post<APIResponse<ResourceGroup>>(
    `/admin/resource-groups/${id}/activate`
  );
  return response.data.data;
}

/**
 * Deactivate resource group (Admin)
 * POST /admin/resource-groups/:id/deactivate
 * @requires Authentication, Admin
 * @param id - Resource group's Stripe-style ID (rg_xxx)
 * Updated: 2025-12-19 - Changed id type to string only (SID format)
 */
export async function deactivateResourceGroup(
  id: string
): Promise<ResourceGroup> {
  const response = await apiClient.post<APIResponse<ResourceGroup>>(
    `/admin/resource-groups/${id}/deactivate`
  );
  return response.data.data;
}

// ============================================================================
// Resource Group Membership APIs
// Added: 2025-12-19
// Updated: 2025-12-19 - All :id parameters now use Stripe-style SID (rg_xxx)
// ============================================================================

/**
 * Add nodes to a resource group (Admin)
 * POST /admin/resource-groups/:id/nodes
 * @requires Authentication, Admin
 * @param id - Resource group's Stripe-style ID (rg_xxx)
 * Updated: 2025-12-19 - Changed id type to string only (SID format)
 */
export async function addNodesToGroup(
  id: string,
  data: AddNodesToGroupRequest
): Promise<BatchOperationResult> {
  const response = await apiClient.post<APIResponse<BatchOperationResult>>(
    `/admin/resource-groups/${id}/nodes`,
    data
  );
  return response.data.data;
}

/**
 * Remove nodes from a resource group (Admin)
 * DELETE /admin/resource-groups/:id/nodes
 * @requires Authentication, Admin
 * @param id - Resource group's Stripe-style ID (rg_xxx)
 * Updated: 2025-12-19 - Changed id type to string only (SID format)
 */
export async function removeNodesFromGroup(
  id: string,
  data: RemoveNodesFromGroupRequest
): Promise<BatchOperationResult> {
  const response = await apiClient.delete<APIResponse<BatchOperationResult>>(
    `/admin/resource-groups/${id}/nodes`,
    { data }
  );
  return response.data.data;
}

/**
 * List nodes in a resource group (Admin)
 * GET /admin/resource-groups/:id/nodes
 * @requires Authentication, Admin
 * @param id - Resource group's Stripe-style ID (rg_xxx)
 * Updated: 2025-12-19 - Changed id type to string only (SID format)
 */
export async function listGroupNodes(
  id: string,
  params?: ListGroupMembersParams
): Promise<ListResponse<NodeSummaryResponse>> {
  const response = await apiClient.get<APIResponse<ListResponse<NodeSummaryResponse>>>(
    `/admin/resource-groups/${id}/nodes`,
    { params }
  );
  return response.data.data;
}

/**
 * Add forward agents to a resource group (Admin)
 * POST /admin/resource-groups/:id/forward-agents
 * @requires Authentication, Admin
 * @param id - Resource group's Stripe-style ID (rg_xxx)
 * Updated: 2025-12-19 - Changed id type to string only (SID format)
 */
export async function addForwardAgentsToGroup(
  id: string,
  data: AddForwardAgentsToGroupRequest
): Promise<BatchOperationResult> {
  const response = await apiClient.post<APIResponse<BatchOperationResult>>(
    `/admin/resource-groups/${id}/forward-agents`,
    data
  );
  return response.data.data;
}

/**
 * Remove forward agents from a resource group (Admin)
 * DELETE /admin/resource-groups/:id/forward-agents
 * @requires Authentication, Admin
 * @param id - Resource group's Stripe-style ID (rg_xxx)
 * Updated: 2025-12-19 - Changed id type to string only (SID format)
 */
export async function removeForwardAgentsFromGroup(
  id: string,
  data: RemoveForwardAgentsToGroupRequest
): Promise<BatchOperationResult> {
  const response = await apiClient.delete<APIResponse<BatchOperationResult>>(
    `/admin/resource-groups/${id}/forward-agents`,
    { data }
  );
  return response.data.data;
}

/**
 * List forward agents in a resource group (Admin)
 * GET /admin/resource-groups/:id/forward-agents
 * @requires Authentication, Admin
 * @param id - Resource group's Stripe-style ID (rg_xxx)
 * Updated: 2025-12-19 - Changed id type to string only (SID format)
 */
export async function listGroupForwardAgents(
  id: string,
  params?: ListGroupMembersParams
): Promise<ListResponse<ForwardAgentSummaryResponse>> {
  const response = await apiClient.get<APIResponse<ListResponse<ForwardAgentSummaryResponse>>>(
    `/admin/resource-groups/${id}/forward-agents`,
    { params }
  );
  return response.data.data;
}
