/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend - internal/application/resource/dto/resourcegroupdto.go
 * Last updated: 2025-12-22
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 */

/**
 * Resource group status
 */
export type ResourceGroupStatus = 'active' | 'inactive';

/**
 * Resource group entity
 * Represents a group of resources associated with a plan
 * Updated: 2025-12-22 - Removed id field (internal auto-increment ID should not be exposed)
 */
export interface ResourceGroup {
  /** Stripe-style ID: rg_xxx */
  sid: string;
  name: string;
  /** Plan's Stripe-style ID: plan_xxx */
  planId: string;
  description?: string;
  status: ResourceGroupStatus;
  createdAt: string;
  updatedAt: string;
}

/**
 * Create resource group request
 * POST /admin/resource-groups
 * Updated: 2025-12-19 - Changed planId to string (Stripe-style ID: plan_xxx)
 */
export interface CreateResourceGroupRequest {
  name: string;
  /** Plan's Stripe-style ID: plan_xxx */
  planId: string;
  description?: string;
}

/**
 * Update resource group request
 * PATCH /admin/resource-groups/:id
 */
export interface UpdateResourceGroupRequest {
  name?: string;
  description?: string;
}

/**
 * List resource groups params
 * GET /admin/resource-groups
 */
export interface ListResourceGroupsParams {
  /** Filter by plan ID (Stripe-style ID: plan_xxx) */
  planId?: string;
  /** Filter by status */
  status?: ResourceGroupStatus;
  /** Page number (1-based) */
  page?: number;
  /** Items per page */
  pageSize?: number;
}

// ========== Resource Group Membership Types ==========
// Added: 2025-12-19

/**
 * Request to add nodes to a resource group
 * POST /admin/resource-groups/:id/nodes
 */
export interface AddNodesToGroupRequest {
  /** Node SIDs to add (e.g., ["node_xxx", "node_yyy"]) */
  nodeIds: string[];
}

/**
 * Request to remove nodes from a resource group
 * DELETE /admin/resource-groups/:id/nodes
 */
export interface RemoveNodesFromGroupRequest {
  /** Node SIDs to remove (e.g., ["node_xxx", "node_yyy"]) */
  nodeIds: string[];
}

/**
 * Request to add forward agents to a resource group
 * POST /admin/resource-groups/:id/forward-agents
 */
export interface AddForwardAgentsToGroupRequest {
  /** Agent SIDs to add (e.g., ["fa_xxx", "fa_yyy"]) */
  agentIds: string[];
}

/**
 * Request to remove forward agents from a resource group
 * DELETE /admin/resource-groups/:id/forward-agents
 */
export interface RemoveForwardAgentsToGroupRequest {
  /** Agent SIDs to remove (e.g., ["fa_xxx", "fa_yyy"]) */
  agentIds: string[];
}

/**
 * Node summary for group member list (simplified)
 * Updated: 2025-12-19 - Changed groupId to groupIds array for multiple resource groups
 */
export interface NodeSummaryResponse {
  /** Node SID (e.g., "node_xK9mP2vL3nQ") */
  id: string;
  name: string;
  status: string;
  /** Resource group SIDs this node belongs to */
  groupIds?: string[];
  createdAt: string;
}

/**
 * Forward agent summary for group member list (simplified)
 */
export interface ForwardAgentSummaryResponse {
  /** Agent SID (e.g., "fa_xK9mP2vL3nQ") */
  id: string;
  name: string;
  status: string;
  /** Resource group SID */
  groupId?: string;
  createdAt: string;
}

/**
 * Batch operation result
 */
export interface BatchOperationResult {
  /** SIDs that were successfully processed */
  succeeded: string[];
  /** Items that failed with error details */
  failed?: BatchOperationError[];
}

/**
 * Batch operation error for a single item
 */
export interface BatchOperationError {
  /** SID of the failed item */
  id: string;
  /** Error reason */
  reason: string;
}

/**
 * Request params for listing group members
 * GET /admin/resource-groups/:id/nodes
 * GET /admin/resource-groups/:id/forward-agents
 */
export interface ListGroupMembersParams {
  /** Page number (1-based) */
  page?: number;
  /** Items per page */
  pageSize?: number;
}
