/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend node module
 */

import { apiClient } from '@/shared/lib/axios';
import type { APIResponse, ListResponse } from '@/shared/types/api.types';
import type {
  Node,
  CreateNodeRequest,
  UpdateNodeRequest,
  UpdateNodeStatusRequest,
  ListNodesParams,
  GenerateNodeTokenResponse,
  NodeGroup,
  CreateNodeGroupRequest,
  UpdateNodeGroupRequest,
  ListNodeGroupsParams,
  AddNodeToGroupRequest,
  BatchAddNodesToGroupRequest,
  BatchRemoveNodesFromGroupRequest,
  BatchOperationResponse,
  AssociatePlanRequest,
  ListGroupNodesResponse,
} from './types';

// ============================================================================
// Node Management APIs
// ============================================================================

/**
 * Create a new node
 * POST /nodes
 * @requires Admin role
 */
export async function createNode(data: CreateNodeRequest): Promise<Node> {
  const response = await apiClient.post<APIResponse<Node>>('/nodes', data);
  return response.data.data;
}

/**
 * Get node by ID
 * GET /nodes/:id
 * @requires Admin role
 */
export async function getNode(id: number): Promise<Node> {
  const response = await apiClient.get<APIResponse<Node>>(`/nodes/${id}`);
  return response.data.data;
}

/**
 * Update node
 * PUT /nodes/:id
 * @requires Admin role
 */
export async function updateNode(
  id: number,
  data: UpdateNodeRequest
): Promise<Node> {
  const response = await apiClient.put<APIResponse<Node>>(`/nodes/${id}`, data);
  return response.data.data;
}

/**
 * Delete node
 * DELETE /nodes/:id
 * @requires Admin role
 */
export async function deleteNode(id: number): Promise<void> {
  await apiClient.delete(`/nodes/${id}`);
}

/**
 * List nodes with pagination and filters
 * GET /nodes
 * @requires Admin role
 */
export async function listNodes(
  params?: ListNodesParams
): Promise<ListResponse<Node>> {
  const response = await apiClient.get<APIResponse<ListResponse<Node>>>(
    '/nodes',
    { params }
  );
  return response.data.data;
}

/**
 * Update node status (active/inactive/maintenance)
 * PATCH /nodes/:id/status
 * @requires Admin role
 */
export async function updateNodeStatus(
  id: number,
  data: UpdateNodeStatusRequest
): Promise<Node> {
  const response = await apiClient.patch<APIResponse<Node>>(
    `/nodes/${id}/status`,
    data
  );
  return response.data.data;
}

/**
 * Generate API token for node
 * POST /nodes/:id/tokens
 * @requires Admin role
 * @returns Token information (token is only shown once)
 */
export async function generateNodeToken(
  id: number
): Promise<GenerateNodeTokenResponse> {
  const response = await apiClient.post<APIResponse<GenerateNodeTokenResponse>>(
    `/nodes/${id}/tokens`
  );
  return response.data.data;
}

// ============================================================================
// Node Group Management APIs
// ============================================================================

/**
 * Create a new node group
 * POST /node-groups
 * @requires Admin role
 */
export async function createNodeGroup(
  data: CreateNodeGroupRequest
): Promise<NodeGroup> {
  const response = await apiClient.post<APIResponse<NodeGroup>>(
    '/node-groups',
    data
  );
  return response.data.data;
}

/**
 * Get node group by ID
 * GET /node-groups/:id
 * @requires Admin role
 */
export async function getNodeGroup(id: number): Promise<NodeGroup> {
  const response = await apiClient.get<APIResponse<NodeGroup>>(
    `/node-groups/${id}`
  );
  return response.data.data;
}

/**
 * Update node group
 * PUT /node-groups/:id
 * @requires Admin role
 */
export async function updateNodeGroup(
  id: number,
  data: UpdateNodeGroupRequest
): Promise<NodeGroup> {
  const response = await apiClient.put<APIResponse<NodeGroup>>(
    `/node-groups/${id}`,
    data
  );
  return response.data.data;
}

/**
 * Delete node group
 * DELETE /node-groups/:id
 * @requires Admin role
 */
export async function deleteNodeGroup(id: number): Promise<void> {
  await apiClient.delete(`/node-groups/${id}`);
}

/**
 * List node groups with pagination and filters
 * GET /node-groups
 * @requires Admin role
 */
export async function listNodeGroups(
  params?: ListNodeGroupsParams
): Promise<ListResponse<NodeGroup>> {
  const response = await apiClient.get<APIResponse<ListResponse<NodeGroup>>>(
    '/node-groups',
    { params }
  );
  return response.data.data;
}

/**
 * Add a single node to a group
 * POST /node-groups/:id/nodes
 * @requires Admin role
 */
export async function addNodeToGroup(
  groupId: number,
  data: AddNodeToGroupRequest
): Promise<NodeGroup> {
  const response = await apiClient.post<APIResponse<NodeGroup>>(
    `/node-groups/${groupId}/nodes`,
    data
  );
  return response.data.data;
}

/**
 * Remove a node from a group
 * DELETE /node-groups/:id/nodes/:nodeId
 * @requires Admin role
 */
export async function removeNodeFromGroup(
  groupId: number,
  nodeId: number
): Promise<void> {
  await apiClient.delete(`/node-groups/${groupId}/nodes/${nodeId}`);
}

/**
 * Batch add multiple nodes to a group
 * POST /node-groups/:id/nodes/batch
 * @requires Admin role
 */
export async function batchAddNodesToGroup(
  groupId: number,
  data: BatchAddNodesToGroupRequest
): Promise<BatchOperationResponse> {
  const response = await apiClient.post<APIResponse<BatchOperationResponse>>(
    `/node-groups/${groupId}/nodes/batch`,
    data
  );
  return response.data.data;
}

/**
 * Batch remove multiple nodes from a group
 * DELETE /node-groups/:id/nodes/batch
 * @requires Admin role
 */
export async function batchRemoveNodesFromGroup(
  groupId: number,
  data: BatchRemoveNodesFromGroupRequest
): Promise<BatchOperationResponse> {
  const response = await apiClient.delete<APIResponse<BatchOperationResponse>>(
    `/node-groups/${groupId}/nodes/batch`,
    { data }
  );
  return response.data.data;
}

/**
 * List all nodes in a group
 * GET /node-groups/:id/nodes
 * @requires Admin role
 */
export async function listGroupNodes(
  groupId: number
): Promise<ListGroupNodesResponse> {
  const response = await apiClient.get<APIResponse<ListGroupNodesResponse>>(
    `/node-groups/${groupId}/nodes`
  );
  return response.data.data;
}

/**
 * Associate a subscription plan with a node group
 * POST /node-groups/:id/plans
 * @requires Admin role
 */
export async function associatePlanWithGroup(
  groupId: number,
  data: AssociatePlanRequest
): Promise<NodeGroup> {
  const response = await apiClient.post<APIResponse<NodeGroup>>(
    `/node-groups/${groupId}/plans`,
    data
  );
  return response.data.data;
}

/**
 * Disassociate a subscription plan from a node group
 * DELETE /node-groups/:id/plans/:planId
 * @requires Admin role
 */
export async function disassociatePlanFromGroup(
  groupId: number,
  planId: number
): Promise<void> {
  await apiClient.delete(`/node-groups/${groupId}/plans/${planId}`);
}
