/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend node module
 * Last updated: 2025-12-22
 *
 * Note: Node IDs are now Stripe-style prefixed IDs (e.g., "node_xK9mP2vL3nQ")
 *
 * Recent changes:
 * - 2025-12-22: listNodes now supports includeUserNodes param for admin node filtering
 * - 2025-12-20: Added user node management functions (createUserNode, listUserNodes, etc.)
 * - 2025-12-18: Removed all NodeGroup related functions (NodeGroup feature removed)
 */

import { apiClient } from '@/shared/lib/axios';
import type { APIResponse, ListResponse } from '@/shared/types/api.types';
import type {
  Node,
  CreateNodeRequest,
  UpdateNodeRequest,
  UpdateNodeStatusRequest,
  ListNodesParams,
  GenerateNodeTokenResponse,
  GenerateNodeInstallScriptResponse,
  GetNodeInstallScriptParams,
  UserNode,
  CreateUserNodeRequest,
  CreateUserNodeResponse,
  UpdateUserNodeRequest,
  ListUserNodesParams,
  RegenerateUserNodeTokenResponse,
  UserNodeUsage,
  UserNodeInstallScriptResponse,
  GetUserNodeInstallScriptParams,
} from './types';

// ============================================================================
// Node Management APIs (Admin)
// ============================================================================

/**
 * Create a new node
 * POST /nodes
 * @requires Admin role
 */
export async function createNode(data: CreateNodeRequest): Promise<Node> {
  const response = await apiClient.post<APIResponse<Node>>('/nodes', data);
  return response.data.data;
}

/**
 * Get node by ID
 * GET /nodes/:id
 * @param id - Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
 * @requires Admin role
 */
export async function getNode(id: string): Promise<Node> {
  const response = await apiClient.get<APIResponse<Node>>(`/nodes/${id}`);
  return response.data.data;
}

/**
 * Update node
 * PUT /nodes/:id
 * @param id - Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
 * @requires Admin role
 */
export async function updateNode(
  id: string,
  data: UpdateNodeRequest
): Promise<Node> {
  const response = await apiClient.put<APIResponse<Node>>(`/nodes/${id}`, data);
  return response.data.data;
}

/**
 * Delete node
 * DELETE /nodes/:id
 * @param id - Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
 * @requires Admin role
 */
export async function deleteNode(id: string): Promise<void> {
  await apiClient.delete(`/nodes/${id}`);
}

/**
 * List nodes with pagination and filters
 * GET /nodes
 * @requires Admin role
 * Updated: 2025-12-22 - Added includeUserNodes param (default: false - only admin nodes)
 */
export async function listNodes(
  params?: ListNodesParams
): Promise<ListResponse<Node>> {
  const response = await apiClient.get<APIResponse<ListResponse<Node>>>(
    '/nodes',
    { params }
  );
  return response.data.data;
}

/**
 * Update node status (active/inactive/maintenance)
 * PATCH /nodes/:id/status
 * @param id - Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
 * @requires Admin role
 */
export async function updateNodeStatus(
  id: string,
  data: UpdateNodeStatusRequest
): Promise<Node> {
  const response = await apiClient.patch<APIResponse<Node>>(
    `/nodes/${id}/status`,
    data
  );
  return response.data.data;
}

/**
 * Generate API token for node
 * POST /nodes/:id/tokens
 * @param id - Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
 * @requires Admin role
 * @returns Token information (token is only shown once)
 */
export async function generateNodeToken(
  id: string
): Promise<GenerateNodeTokenResponse> {
  const response = await apiClient.post<APIResponse<GenerateNodeTokenResponse>>(
    `/nodes/${id}/tokens`
  );
  return response.data.data;
}

/**
 * Get install script command for node
 * GET /nodes/:id/install-script
 * @param id - Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
 * @requires Admin role
 * @returns Install script information including install/uninstall commands
 */
export async function getNodeInstallScript(
  id: string,
  params?: GetNodeInstallScriptParams
): Promise<GenerateNodeInstallScriptResponse> {
  const response = await apiClient.get<APIResponse<GenerateNodeInstallScriptResponse>>(
    `/nodes/${id}/install-script`,
    { params }
  );
  return response.data.data;
}

// ============================================================================
// User Node Management APIs
// Added: 2025-12-20
// ============================================================================

/**
 * Create a new user-owned node
 * POST /user/nodes
 * @requires Authentication
 * Added: 2025-12-20
 */
export async function createUserNode(
  data: CreateUserNodeRequest
): Promise<CreateUserNodeResponse> {
  const response = await apiClient.post<APIResponse<CreateUserNodeResponse>>(
    '/user/nodes',
    data
  );
  return response.data.data;
}

/**
 * List current user's nodes with pagination and filters
 * GET /user/nodes
 * @requires Authentication
 * Added: 2025-12-20
 */
export async function listUserNodes(
  params?: ListUserNodesParams
): Promise<ListResponse<UserNode>> {
  const response = await apiClient.get<APIResponse<ListResponse<UserNode>>>(
    '/user/nodes',
    { params }
  );
  return response.data.data;
}

/**
 * Get a specific user-owned node by ID
 * GET /user/nodes/:id
 * @param id - Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
 * @requires Authentication, Ownership
 * Added: 2025-12-20
 */
export async function getUserNode(id: string): Promise<UserNode> {
  const response = await apiClient.get<APIResponse<UserNode>>(
    `/user/nodes/${id}`
  );
  return response.data.data;
}

/**
 * Update a user-owned node
 * PUT /user/nodes/:id
 * @param id - Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
 * @requires Authentication, Ownership
 * Added: 2025-12-20
 */
export async function updateUserNode(
  id: string,
  data: UpdateUserNodeRequest
): Promise<UserNode> {
  const response = await apiClient.put<APIResponse<UserNode>>(
    `/user/nodes/${id}`,
    data
  );
  return response.data.data;
}

/**
 * Delete a user-owned node
 * DELETE /user/nodes/:id
 * @param id - Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
 * @requires Authentication, Ownership
 * Added: 2025-12-20
 */
export async function deleteUserNode(id: string): Promise<void> {
  await apiClient.delete(`/user/nodes/${id}`);
}

/**
 * Regenerate token for a user-owned node
 * POST /user/nodes/:id/regenerate-token
 * @param id - Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
 * @requires Authentication, Ownership
 * @returns New token (only shown once)
 * Added: 2025-12-20
 */
export async function regenerateUserNodeToken(
  id: string
): Promise<RegenerateUserNodeTokenResponse> {
  const response = await apiClient.post<APIResponse<RegenerateUserNodeTokenResponse>>(
    `/user/nodes/${id}/regenerate-token`
  );
  return response.data.data;
}

/**
 * Get current user's node usage and quota
 * GET /user/nodes/usage
 * @requires Authentication
 * @returns Node usage statistics and quota limits
 * Added: 2025-12-20
 */
export async function getUserNodeUsage(): Promise<UserNodeUsage> {
  const response = await apiClient.get<APIResponse<UserNodeUsage>>(
    '/user/nodes/usage'
  );
  return response.data.data;
}

/**
 * Get install script command for a user-owned node
 * GET /user/nodes/:id/install-script
 * @param id - Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
 * @requires Authentication, Ownership
 * @returns Install script information including install/uninstall commands
 * Added: 2025-12-20
 */
export async function getUserNodeInstallScript(
  id: string,
  params?: GetUserNodeInstallScriptParams
): Promise<UserNodeInstallScriptResponse> {
  const response = await apiClient.get<APIResponse<UserNodeInstallScriptResponse>>(
    `/user/nodes/${id}/install-script`,
    { params }
  );
  return response.data.data;
}
