/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend node module
 * Last updated: 2025-12-18
 *
 * Note: Node IDs are now Stripe-style prefixed IDs (e.g., "node_xK9mP2vL3nQ")
 *
 * Updated 2025-12-18: Removed all NodeGroup related functions (NodeGroup feature removed)
 */

import { apiClient } from '@/shared/lib/axios';
import type { APIResponse, ListResponse } from '@/shared/types/api.types';
import type {
  Node,
  CreateNodeRequest,
  UpdateNodeRequest,
  UpdateNodeStatusRequest,
  ListNodesParams,
  GenerateNodeTokenResponse,
  GenerateNodeInstallScriptResponse,
  GetNodeInstallScriptParams,
} from './types';

// ============================================================================
// Node Management APIs
// ============================================================================

/**
 * Create a new node
 * POST /nodes
 * @requires Admin role
 */
export async function createNode(data: CreateNodeRequest): Promise<Node> {
  const response = await apiClient.post<APIResponse<Node>>('/nodes', data);
  return response.data.data;
}

/**
 * Get node by ID
 * GET /nodes/:id
 * @param id - Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
 * @requires Admin role
 */
export async function getNode(id: string): Promise<Node> {
  const response = await apiClient.get<APIResponse<Node>>(`/nodes/${id}`);
  return response.data.data;
}

/**
 * Update node
 * PUT /nodes/:id
 * @param id - Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
 * @requires Admin role
 */
export async function updateNode(
  id: string,
  data: UpdateNodeRequest
): Promise<Node> {
  const response = await apiClient.put<APIResponse<Node>>(`/nodes/${id}`, data);
  return response.data.data;
}

/**
 * Delete node
 * DELETE /nodes/:id
 * @param id - Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
 * @requires Admin role
 */
export async function deleteNode(id: string): Promise<void> {
  await apiClient.delete(`/nodes/${id}`);
}

/**
 * List nodes with pagination and filters
 * GET /nodes
 * @requires Admin role
 */
export async function listNodes(
  params?: ListNodesParams
): Promise<ListResponse<Node>> {
  const response = await apiClient.get<APIResponse<ListResponse<Node>>>(
    '/nodes',
    { params }
  );
  return response.data.data;
}

/**
 * Update node status (active/inactive/maintenance)
 * PATCH /nodes/:id/status
 * @param id - Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
 * @requires Admin role
 */
export async function updateNodeStatus(
  id: string,
  data: UpdateNodeStatusRequest
): Promise<Node> {
  const response = await apiClient.patch<APIResponse<Node>>(
    `/nodes/${id}/status`,
    data
  );
  return response.data.data;
}

/**
 * Generate API token for node
 * POST /nodes/:id/tokens
 * @param id - Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
 * @requires Admin role
 * @returns Token information (token is only shown once)
 */
export async function generateNodeToken(
  id: string
): Promise<GenerateNodeTokenResponse> {
  const response = await apiClient.post<APIResponse<GenerateNodeTokenResponse>>(
    `/nodes/${id}/tokens`
  );
  return response.data.data;
}

/**
 * Get install script command for node
 * GET /nodes/:id/install-script
 * @param id - Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
 * @requires Admin role
 * @returns Install script information including install/uninstall commands
 */
export async function getNodeInstallScript(
  id: string,
  params?: GetNodeInstallScriptParams
): Promise<GenerateNodeInstallScriptResponse> {
  const response = await apiClient.get<APIResponse<GenerateNodeInstallScriptResponse>>(
    `/nodes/${id}/install-script`,
    { params }
  );
  return response.data.data;
}
