/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend node module
 */

/**
 * Node status
 */
export type NodeStatus = 'active' | 'inactive' | 'maintenance' | 'error';

/**
 * Node protocol type
 */
export type NodeProtocol = 'shadowsocks' | 'trojan';

/**
 * Node entity
 */
export interface Node {
  id: number;
  name: string;
  description?: string;
  serverAddress: string;
  serverPort: number;
  protocol: NodeProtocol;
  encryptionMethod: string;
  plugin?: string;
  pluginOpts?: Record<string, string>;
  status: NodeStatus;
  region?: string;
  tags?: string[];
  customFields?: Record<string, unknown>;
  sortOrder: number;
  maintenanceReason?: string;
  isAvailable: boolean;
  version: number;
  trafficUsed?: number;
  trafficLimit?: number;
  createdAt: string;
  updatedAt: string;
  systemStatus?: NodeSystemStatus;
}

/**
 * Node system status (real-time metrics from monitoring)
 */
export interface NodeSystemStatus {
  cpu: string;
  memory: string;
  disk: string;
  uptime: number;
  updatedAt: number;
}

/**
 * Create node request
 * POST /nodes
 */
export interface CreateNodeRequest {
  name: string;
  serverAddress: string;
  serverPort: number;
  protocol: NodeProtocol;
  encryptionMethod: string;
  plugin?: string;
  pluginOpts?: Record<string, string>;
  region?: string;
  tags?: string[];
  description?: string;
  sortOrder?: number;
}

/**
 * Update node request
 * PUT /nodes/:id
 */
export interface UpdateNodeRequest {
  name?: string;
  serverAddress?: string;
  serverPort?: number;
  encryptionMethod?: string;
  plugin?: string;
  pluginOpts?: Record<string, string>;
  status?: NodeStatus;
  region?: string;
  tags?: string[];
  description?: string;
  sortOrder?: number;
}

/**
 * Update node status request
 * PATCH /nodes/:id/status
 */
export interface UpdateNodeStatusRequest {
  status: NodeStatus;
}

/**
 * List nodes params
 * GET /nodes
 */
export interface ListNodesParams {
  page?: number;
  pageSize?: number;
  status?: NodeStatus;
  region?: string;
  tags?: string[];
  orderBy?: string;
  order?: 'asc' | 'desc';
}

/**
 * Generate node token response
 * POST /nodes/:id/tokens
 */
export interface GenerateNodeTokenResponse {
  nodeId: number;
  token: string;
  tokenPrefix: string;
  expiresAt?: string;
  createdAt: string;
}

/**
 * Node token response (alias for compatibility)
 */
export type NodeTokenResponse = GenerateNodeTokenResponse;

/**
 * Node group entity
 */
export interface NodeGroup {
  id: number;
  name: string;
  description: string;
  nodeIds: number[];
  subscriptionPlanIds: number[];
  isPublic: boolean;
  sortOrder: number;
  metadata?: Record<string, unknown>;
  nodeCount: number;
  version: number;
  createdAt: string;
  updatedAt: string;
}

/**
 * Create node group request
 * POST /node-groups
 */
export interface CreateNodeGroupRequest {
  name: string;
  description?: string;
  isPublic?: boolean;
  sortOrder?: number;
}

/**
 * Update node group request
 * PUT /node-groups/:id
 */
export interface UpdateNodeGroupRequest {
  name?: string;
  description?: string;
  isPublic?: boolean;
  sortOrder?: number;
}

/**
 * List node groups params
 * GET /node-groups
 */
export interface ListNodeGroupsParams {
  page?: number;
  pageSize?: number;
  isPublic?: boolean;
}

/**
 * Add node to group request
 * POST /node-groups/:id/nodes
 */
export interface AddNodeToGroupRequest {
  nodeId: number;
}

/**
 * Batch add nodes to group request
 * POST /node-groups/:id/nodes/batch
 */
export interface BatchAddNodesToGroupRequest {
  nodeIds: number[];
}

/**
 * Batch remove nodes from group request
 * DELETE /node-groups/:id/nodes/batch
 */
export interface BatchRemoveNodesFromGroupRequest {
  nodeIds: number[];
}

/**
 * Associate plan with group request
 * POST /node-groups/:id/plans
 */
export interface AssociatePlanRequest {
  planId: number;
}

/**
 * List group nodes response
 * GET /node-groups/:id/nodes
 * Returns array of nodes directly
 */
export type ListGroupNodesResponse = Node[];

/**
 * Batch operation response
 */
export interface BatchOperationResponse {
  message: string;
  addedCount?: number;
  removedCount?: number;
  failedCount?: number;
}
