/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend node module
 * Last updated: 2025-12-22
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 *
 * ID Format: Stripe-style prefixed IDs
 * - Node: "node_xK9mP2vL3nQ" (prefix: node_)
 *
 * Recent changes:
 * - 2025-12-22: Added includeUserNodes param to ListNodesParams for admin node filtering
 * - 2025-12-20: Added user node management types (UserNode, CreateUserNodeRequest, UpdateUserNodeRequest, etc.)
 * - 2025-12-18: Made serverAddress optional in CreateNodeRequest (can be auto-detected from agent)
 * - 2025-12-18: Removed all NodeGroup related types (NodeGroup feature removed)
 */

/**
 * Node status
 */
export type NodeStatus = 'active' | 'inactive' | 'maintenance';

/**
 * Node protocol type
 */
export type NodeProtocol = 'shadowsocks' | 'trojan';

/**
 * Transport protocol for Trojan
 */
export type TransportProtocol = 'tcp' | 'ws' | 'grpc';

/**
 * Node entity
 * ID format: "node_xK9mP2vL3nQ" (Stripe-style prefixed ID)
 * Updated: 2025-12-19 - Changed groupId to groupIds array for multiple resource groups
 */
export interface Node {
  id: string; // Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
  name: string;
  serverAddress: string;
  /** Port for agent connections */
  agentPort: number;
  /** Port for client subscriptions (if null, uses agentPort) */
  subscriptionPort?: number;
  protocol: NodeProtocol;
  encryptionMethod: string;
  plugin?: string;
  pluginOpts?: Record<string, string>;
  status: NodeStatus;
  region?: string;
  tags?: string[];
  customFields?: Record<string, unknown>;
  sortOrder: number;
  /** Transport protocol for Trojan (tcp, ws, grpc) */
  transportProtocol?: TransportProtocol;
  /** WebSocket host header or gRPC service name */
  host?: string;
  /** WebSocket path */
  path?: string;
  /** TLS Server Name Indication */
  sni?: string;
  /** Allow insecure TLS connection */
  allowInsecure?: boolean;
  maintenanceReason?: string;
  /** Indicates if the node agent is online (reported within 5 minutes) */
  isOnline: boolean;
  /** Last time the node agent reported status */
  lastSeenAt?: string;
  /** Resource group SIDs this node belongs to (e.g., ["rg_xK9mP2vL3nQ", "rg_yL0nQ3wM4oR"]) */
  groupIds?: string[];
  version: number;
  createdAt: string;
  updatedAt: string;
  systemStatus?: NodeSystemStatus;
}

/**
 * Node system status (real-time metrics from monitoring)
 */
export interface NodeSystemStatus {
  cpu: string;
  memory: string;
  disk: string;
  uptime: number;
  updatedAt: number;
  /** Public IPv4 address reported by agent */
  publicIpv4?: string;
  /** Public IPv6 address reported by agent */
  publicIpv6?: string;
}

/**
 * Create node request
 * POST /nodes
 */
export interface CreateNodeRequest {
  name: string;
  /** Server address (optional, can be auto-detected from agent's public IP) */
  serverAddress?: string;
  /** Port for agent connections (required) */
  agentPort: number;
  /** Port for client subscriptions (if null, uses agentPort) */
  subscriptionPort?: number;
  protocol: NodeProtocol;
  /** Encryption method (for Shadowsocks) */
  encryptionMethod?: string;
  plugin?: string;
  pluginOpts?: Record<string, string>;
  region?: string;
  tags?: string[];
  description?: string;
  sortOrder?: number;
  /** Transport protocol for Trojan (tcp, ws, grpc) */
  transportProtocol?: TransportProtocol;
  /** WebSocket host header or gRPC service name */
  host?: string;
  /** WebSocket path */
  path?: string;
  /** TLS Server Name Indication */
  sni?: string;
  /** Allow insecure TLS connection (for self-signed certs) */
  allowInsecure?: boolean;
}

/**
 * Update node request
 * PUT /nodes/:id
 * Updated: 2025-12-19 - Added groupSid field for resource group association
 */
export interface UpdateNodeRequest {
  name?: string;
  serverAddress?: string;
  /** Port for agent connections */
  agentPort?: number;
  /** Port for client subscriptions */
  subscriptionPort?: number;
  /** Encryption method (for Shadowsocks) */
  encryptionMethod?: string;
  plugin?: string;
  pluginOpts?: Record<string, string>;
  status?: NodeStatus;
  region?: string;
  tags?: string[];
  description?: string;
  sortOrder?: number;
  /** Resource group SID to associate with (use empty string to remove association) */
  groupSid?: string;
  /** Transport protocol for Trojan (tcp, ws, grpc) */
  transportProtocol?: TransportProtocol;
  /** WebSocket host header or gRPC service name */
  host?: string;
  /** WebSocket path */
  path?: string;
  /** TLS Server Name Indication */
  sni?: string;
  /** Allow insecure TLS connection */
  allowInsecure?: boolean;
}

/**
 * Update node status request
 * PATCH /nodes/:id/status
 */
export interface UpdateNodeStatusRequest {
  status: NodeStatus;
}

/**
 * List nodes params
 * GET /nodes
 * Updated: 2025-12-22 - Added includeUserNodes param
 */
export interface ListNodesParams {
  page?: number;
  pageSize?: number;
  status?: NodeStatus;
  /** Include user-created nodes in the list (default: false - only admin-created nodes) */
  includeUserNodes?: boolean;
}

/**
 * Generate node token response
 * POST /nodes/:id/tokens
 */
export interface GenerateNodeTokenResponse {
  nodeId: string; // Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
  token: string;
  tokenPrefix: string;
  expiresAt?: string;
  createdAt: string;
}

/**
 * Generate node install script response
 * GET /nodes/:id/install-script
 */
export interface GenerateNodeInstallScriptResponse {
  installCommand: string;
  uninstallCommand: string;
  scriptUrl: string;
  apiUrl: string;
  nodeId: string; // Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
  token: string;
}

/**
 * Generate node install script params
 * GET /nodes/:id/install-script
 */
export interface GetNodeInstallScriptParams {
  /** Override the node's stored token */
  token?: string;
  /** Override the default API URL */
  apiUrl?: string;
}

// ============================================================================
// User Node Management Types
// Added: 2025-12-20
// ============================================================================

/**
 * User-owned node entity
 * Contains fewer fields than Node, hiding admin-specific information
 * GET /user/nodes/:id
 * Added: 2025-12-20
 */
export interface UserNode {
  id: string; // Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
  name: string;
  serverAddress: string;
  /** Port for agent connections */
  agentPort: number;
  /** Port for client subscriptions (if null, uses agentPort) */
  subscriptionPort?: number;
  protocol: NodeProtocol;
  /** Encryption method (Shadowsocks only) */
  encryptionMethod?: string;
  status: NodeStatus;
  /** Indicates if the node agent is online */
  isOnline: boolean;
  /** Last time the node agent reported status */
  lastSeenAt?: string;
  /** Transport protocol for Trojan */
  transportProtocol?: TransportProtocol;
  /** WebSocket host or gRPC service name */
  host?: string;
  /** WebSocket path */
  path?: string;
  /** TLS SNI */
  sni?: string;
  /** Allow insecure TLS */
  allowInsecure?: boolean;
  createdAt: string;
  updatedAt: string;
}

/**
 * Create user node request
 * POST /user/nodes
 * Added: 2025-12-20
 */
export interface CreateUserNodeRequest {
  name: string;
  /** Server address (optional, can be auto-detected from agent's public IP) */
  serverAddress?: string;
  /** Port for agent connections (required) */
  agentPort: number;
  /** Port for client subscriptions (if null, uses agentPort) */
  subscriptionPort?: number;
  /** Protocol type: shadowsocks or trojan */
  protocol: NodeProtocol;
  /** Encryption method (for Shadowsocks, e.g., "aes-256-gcm") */
  method?: string;
  /** Plugin name (for Shadowsocks) */
  plugin?: string;
  /** Plugin options */
  pluginOpts?: Record<string, string>;
  /** Transport protocol for Trojan (tcp, ws, grpc) */
  transportProtocol?: TransportProtocol;
  /** WebSocket host header or gRPC service name */
  host?: string;
  /** WebSocket path */
  path?: string;
  /** TLS Server Name Indication */
  sni?: string;
  /** Allow insecure TLS connection */
  allowInsecure?: boolean;
}

/**
 * Create user node response
 * POST /user/nodes
 * Added: 2025-12-20
 */
export interface CreateUserNodeResponse {
  node: UserNode;
  /** Token for node authentication (only shown once) */
  token: string;
  /** Token prefix for identification */
  tokenPrefix: string;
}

/**
 * Update user node request
 * PUT /user/nodes/:id
 * Added: 2025-12-20
 */
export interface UpdateUserNodeRequest {
  name?: string;
  serverAddress?: string;
  /** Port for agent connections */
  agentPort?: number;
  /** Port for client subscriptions */
  subscriptionPort?: number;
}

/**
 * List user nodes params
 * GET /user/nodes
 * Added: 2025-12-20
 */
export interface ListUserNodesParams {
  page?: number;
  pageSize?: number;
  status?: NodeStatus;
  search?: string;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

/**
 * Regenerate user node token response
 * POST /user/nodes/:id/regenerate-token
 * Added: 2025-12-20
 */
export interface RegenerateUserNodeTokenResponse {
  nodeId: string; // Stripe-style prefixed ID (e.g., "node_xK9mP2vL3nQ")
  /** New token (only shown once) */
  token: string;
  /** Token prefix for identification */
  tokenPrefix: string;
}

/**
 * User node usage/quota response
 * GET /user/nodes/usage
 * Added: 2025-12-20
 */
export interface UserNodeUsage {
  /** Current number of user-owned nodes */
  nodeCount: number;
  /** Maximum allowed nodes (0 means unlimited) */
  nodeLimit: number;
}

/**
 * User node install script response
 * GET /user/nodes/:id/install-script
 * Added: 2025-12-20
 */
export interface UserNodeInstallScriptResponse {
  installCommand: string;
  uninstallCommand: string;
  scriptUrl: string;
  apiUrl: string;
  /** Internal node ID (numeric) */
  nodeId: number;
  token: string;
}

/**
 * User node install script params
 * GET /user/nodes/:id/install-script
 * Added: 2025-12-20
 */
export interface GetUserNodeInstallScriptParams {
  /** Override the default API URL */
  apiUrl?: string;
}
