/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2025-12-26
 *
 * Recent changes:
 * - 2025-12-26: Added deletePlan and deleteSubscription APIs
 * - 2025-12-19: Changed all ID parameters from number to string (Stripe-style IDs)
 * - 2025-12-18: Added Plan-Node entitlement management APIs (getPlanNodes, bindNodes, unbindNodes)
 * - 2025-12-18: Changed plan routes from /subscription-plans to /plans
 */

import { apiClient } from '@/shared/lib/axios';
import type { APIResponse, ListResponse } from '@/shared/types/api.types';
import type {
  Subscription,
  SubscriptionPlan,
  SubscriptionToken,
  CreateSubscriptionRequest,
  CreateSubscriptionResponse,
  UpdateSubscriptionStatusRequest,
  ChangePlanRequest,
  ListSubscriptionsParams,
  CreatePlanRequest,
  UpdatePlanRequest,
  UpdatePlanStatusRequest,
  ListPlansParams,
  GenerateTokenRequest,
  GenerateTokenResponse,
  RefreshTokenResponse,
  ListTokensParams,
  GetTrafficStatsParams,
  TrafficStatsResponse,
  GetPlanNodesResult,
  BindNodesRequest,
  UnbindNodesRequest,
  AdminCreateSubscriptionRequest,
  AdminCreateSubscriptionResponse,
  AdminUpdateSubscriptionStatusRequest,
  AdminChangePlanRequest,
  AdminListSubscriptionsParams,
} from './types';

// ============================================================================
// Subscription APIs
// ============================================================================

/**
 * Create a new subscription for current user
 * POST /subscriptions
 */
export async function createSubscription(
  data: CreateSubscriptionRequest
): Promise<CreateSubscriptionResponse> {
  const response = await apiClient.post<APIResponse<CreateSubscriptionResponse>>(
    '/subscriptions',
    data
  );
  return response.data.data;
}

/**
 * Get subscription by ID
 * GET /subscriptions/:id
 * @param id - Subscription's Stripe-style ID (sub_xxx)
 */
export async function getSubscription(id: string): Promise<Subscription> {
  const response = await apiClient.get<APIResponse<Subscription>>(
    `/subscriptions/${id}`
  );
  return response.data.data;
}

/**
 * List current user's subscriptions
 * GET /subscriptions
 */
export async function listSubscriptions(
  params?: ListSubscriptionsParams
): Promise<ListResponse<Subscription>> {
  const response = await apiClient.get<APIResponse<ListResponse<Subscription>>>(
    '/subscriptions',
    { params }
  );
  return response.data.data;
}

/**
 * Update subscription status (e.g., cancel)
 * PATCH /subscriptions/:id/status
 * @param id - Subscription's Stripe-style ID (sub_xxx)
 */
export async function updateSubscriptionStatus(
  id: string,
  data: UpdateSubscriptionStatusRequest
): Promise<void> {
  await apiClient.patch<APIResponse<null>>(
    `/subscriptions/${id}/status`,
    data
  );
}

/**
 * Change subscription plan
 * PATCH /subscriptions/:id/plan
 * @param id - Subscription's Stripe-style ID (sub_xxx)
 */
export async function changePlan(
  id: string,
  data: ChangePlanRequest
): Promise<void> {
  await apiClient.patch<APIResponse<null>>(
    `/subscriptions/${id}/plan`,
    data
  );
}

/**
 * Reset subscription link (generates new UUID)
 * PUT /subscriptions/:id/link
 * @param id - Subscription's Stripe-style ID (sub_xxx)
 */
export async function resetSubscriptionLink(id: string): Promise<Subscription> {
  const response = await apiClient.put<APIResponse<Subscription>>(
    `/subscriptions/${id}/link`
  );
  return response.data.data;
}

/**
 * Delete subscription (soft delete)
 * DELETE /subscriptions/:id
 * @param id - Subscription's Stripe-style ID (sub_xxx)
 * @note Only cancelled or expired subscriptions can be deleted
 * Added: 2025-12-26
 */
export async function deleteSubscription(id: string): Promise<void> {
  await apiClient.delete<APIResponse<null>>(
    `/subscriptions/${id}`
  );
}

// ============================================================================
// Subscription Plan APIs
// ============================================================================

/**
 * Get public plans (no auth required)
 * GET /plans/public
 */
export async function getPublicPlans(): Promise<SubscriptionPlan[]> {
  const response = await apiClient.get<APIResponse<SubscriptionPlan[]>>(
    '/plans/public'
  );
  return response.data.data;
}

/**
 * Get plan by ID
 * GET /plans/:id
 * @param id - Plan's Stripe-style ID (plan_xxx)
 */
export async function getPlan(id: string): Promise<SubscriptionPlan> {
  const response = await apiClient.get<APIResponse<SubscriptionPlan>>(
    `/plans/${id}`
  );
  return response.data.data;
}

/**
 * List all plans (admin)
 * GET /plans
 */
export async function listPlans(
  params?: ListPlansParams
): Promise<ListResponse<SubscriptionPlan>> {
  const response = await apiClient.get<APIResponse<ListResponse<SubscriptionPlan>>>(
    '/plans',
    { params }
  );
  return response.data.data;
}

/**
 * Create a new plan (admin)
 * POST /plans
 */
export async function createPlan(
  data: CreatePlanRequest
): Promise<SubscriptionPlan> {
  const response = await apiClient.post<APIResponse<SubscriptionPlan>>(
    '/plans',
    data
  );
  return response.data.data;
}

/**
 * Update a plan (admin)
 * PUT /plans/:id
 * @param id - Plan's Stripe-style ID (plan_xxx)
 */
export async function updatePlan(
  id: string,
  data: UpdatePlanRequest
): Promise<SubscriptionPlan> {
  const response = await apiClient.put<APIResponse<SubscriptionPlan>>(
    `/plans/${id}`,
    data
  );
  return response.data.data;
}

/**
 * Update plan status (admin)
 * PATCH /plans/:id/status
 * @param id - Plan's Stripe-style ID (plan_xxx)
 */
export async function updatePlanStatus(
  id: string,
  data: UpdatePlanStatusRequest
): Promise<void> {
  await apiClient.patch<APIResponse<null>>(
    `/plans/${id}/status`,
    data
  );
}

/**
 * Delete plan (soft delete, admin only)
 * DELETE /plans/:id
 * @param id - Plan's Stripe-style ID (plan_xxx)
 * @note Only plans with no active subscriptions can be deleted
 * Added: 2025-12-26
 */
export async function deletePlan(id: string): Promise<void> {
  await apiClient.delete<APIResponse<null>>(
    `/plans/${id}`
  );
}

/**
 * Get plan pricings
 * GET /plans/:id/pricings
 * @param id - Plan's Stripe-style ID (plan_xxx)
 */
export async function getPlanPricings(id: string): Promise<SubscriptionPlan> {
  const response = await apiClient.get<APIResponse<SubscriptionPlan>>(
    `/plans/${id}/pricings`
  );
  return response.data.data;
}

// ============================================================================
// Plan-Node Entitlement Management APIs
// Added: 2025-12-18
// ============================================================================

/**
 * Get all nodes associated with a plan (admin)
 * GET /plans/:id/nodes
 * @requires Authentication, Admin
 * @param planId - Plan's Stripe-style ID (plan_xxx)
 */
export async function getPlanNodes(planId: string): Promise<GetPlanNodesResult> {
  const response = await apiClient.get<APIResponse<GetPlanNodesResult>>(
    `/plans/${planId}/nodes`
  );
  return response.data.data;
}

/**
 * Bind nodes to a plan (admin)
 * POST /plans/:id/nodes
 * @requires Authentication, Admin
 * @description Only works for node-type plans. Binds the specified nodes to the plan.
 * @param planId - Plan's Stripe-style ID (plan_xxx)
 */
export async function bindNodes(
  planId: string,
  data: BindNodesRequest
): Promise<void> {
  await apiClient.post<APIResponse<null>>(
    `/plans/${planId}/nodes`,
    data
  );
}

/**
 * Unbind nodes from a plan (admin)
 * DELETE /plans/:id/nodes
 * @requires Authentication, Admin
 * @description Removes the association between the specified nodes and the plan.
 * @param planId - Plan's Stripe-style ID (plan_xxx)
 */
export async function unbindNodes(
  planId: string,
  data: UnbindNodesRequest
): Promise<void> {
  await apiClient.delete<APIResponse<null>>(
    `/plans/${planId}/nodes`,
    { data }
  );
}

// ============================================================================
// Subscription Token APIs
// ============================================================================

/**
 * Generate a new subscription token
 * POST /subscriptions/:id/tokens
 * @param subscriptionId - Subscription's Stripe-style ID (sub_xxx)
 */
export async function generateToken(
  subscriptionId: string,
  data: GenerateTokenRequest
): Promise<GenerateTokenResponse> {
  const response = await apiClient.post<APIResponse<GenerateTokenResponse>>(
    `/subscriptions/${subscriptionId}/tokens`,
    data
  );
  return response.data.data;
}

/**
 * List subscription tokens
 * GET /subscriptions/:id/tokens
 * @param subscriptionId - Subscription's Stripe-style ID (sub_xxx)
 */
export async function listTokens(
  subscriptionId: string,
  params?: ListTokensParams
): Promise<SubscriptionToken[]> {
  const response = await apiClient.get<APIResponse<SubscriptionToken[]>>(
    `/subscriptions/${subscriptionId}/tokens`,
    { params }
  );
  return response.data.data;
}

/**
 * Revoke a subscription token
 * DELETE /subscriptions/:id/tokens/:tokenId
 * @param subscriptionId - Subscription's Stripe-style ID (sub_xxx)
 * @param tokenId - Token's Stripe-style ID (stoken_xxx)
 */
export async function revokeToken(
  subscriptionId: string,
  tokenId: string
): Promise<void> {
  await apiClient.delete<APIResponse<null>>(
    `/subscriptions/${subscriptionId}/tokens/${tokenId}`
  );
}

/**
 * Refresh a subscription token
 * POST /subscriptions/:id/tokens/:tokenId/refresh
 * @param subscriptionId - Subscription's Stripe-style ID (sub_xxx)
 * @param tokenId - Token's Stripe-style ID (stoken_xxx)
 */
export async function refreshToken(
  subscriptionId: string,
  tokenId: string
): Promise<RefreshTokenResponse> {
  const response = await apiClient.post<APIResponse<RefreshTokenResponse>>(
    `/subscriptions/${subscriptionId}/tokens/${tokenId}/refresh`
  );
  return response.data.data;
}

// ============================================================================
// Traffic Statistics APIs
// ============================================================================

/**
 * Get subscription traffic statistics
 * GET /subscriptions/:id/traffic-stats
 * @param subscriptionId - Subscription's Stripe-style ID (sub_xxx)
 */
export async function getTrafficStats(
  subscriptionId: string,
  params: GetTrafficStatsParams
): Promise<TrafficStatsResponse> {
  const response = await apiClient.get<APIResponse<TrafficStatsResponse>>(
    `/subscriptions/${subscriptionId}/traffic-stats`,
    { params }
  );
  return response.data.data;
}

// ============================================================================
// Admin Subscription Management APIs
// Migrated from admin SDK: 2025-12-19
// ============================================================================

/**
 * Create subscription (Admin)
 * POST /admin/subscriptions
 * @requires Authentication, Admin
 */
export async function adminCreateSubscription(
  data: AdminCreateSubscriptionRequest
): Promise<AdminCreateSubscriptionResponse> {
  const response = await apiClient.post<APIResponse<AdminCreateSubscriptionResponse>>(
    '/admin/subscriptions',
    data
  );
  return response.data.data;
}

/**
 * Get subscription by ID (Admin)
 * GET /admin/subscriptions/:id
 * @requires Authentication, Admin
 * @param id - Subscription's Stripe-style ID (sub_xxx)
 * Updated: 2025-12-19 - Changed id type to string only (SID format)
 */
export async function adminGetSubscription(id: string): Promise<Subscription> {
  const response = await apiClient.get<APIResponse<Subscription>>(
    `/admin/subscriptions/${id}`
  );
  return response.data.data;
}

/**
 * List all subscriptions (Admin)
 * GET /admin/subscriptions
 * @requires Authentication, Admin
 */
export async function adminListSubscriptions(
  params?: AdminListSubscriptionsParams
): Promise<ListResponse<Subscription>> {
  const response = await apiClient.get<APIResponse<ListResponse<Subscription>>>(
    '/admin/subscriptions',
    { params }
  );
  return response.data.data;
}

/**
 * Update subscription status (Admin)
 * PATCH /admin/subscriptions/:id/status
 * @requires Authentication, Admin
 * @param id - Subscription's Stripe-style ID (sub_xxx)
 * Updated: 2025-12-19 - Changed id type to string only (SID format)
 */
export async function adminUpdateSubscriptionStatus(
  id: string,
  data: AdminUpdateSubscriptionStatusRequest
): Promise<void> {
  await apiClient.patch(`/admin/subscriptions/${id}/status`, data);
}

/**
 * Change subscription plan (Admin)
 * PATCH /admin/subscriptions/:id/plan
 * @requires Authentication, Admin
 * @param id - Subscription's Stripe-style ID (sub_xxx)
 * Updated: 2025-12-19 - Changed id type to string only (SID format)
 */
export async function adminChangeSubscriptionPlan(
  id: string,
  data: AdminChangePlanRequest
): Promise<void> {
  await apiClient.patch(`/admin/subscriptions/${id}/plan`, data);
}
