/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 */

import { apiClient } from '@/shared/lib/axios';
import type { APIResponse, ListResponse } from '@/shared/types/api.types';
import type {
  Subscription,
  SubscriptionPlan,
  SubscriptionToken,
  CreateSubscriptionRequest,
  CreateSubscriptionResponse,
  UpdateSubscriptionStatusRequest,
  ChangePlanRequest,
  ListSubscriptionsParams,
  CreatePlanRequest,
  UpdatePlanRequest,
  UpdatePlanStatusRequest,
  ListPlansParams,
  GenerateTokenRequest,
  GenerateTokenResponse,
  RefreshTokenResponse,
  ListTokensParams,
} from './types';

// ============================================================================
// Subscription APIs
// ============================================================================

/**
 * Create a new subscription for current user
 * POST /subscriptions
 */
export async function createSubscription(
  data: CreateSubscriptionRequest
): Promise<CreateSubscriptionResponse> {
  const response = await apiClient.post<APIResponse<CreateSubscriptionResponse>>(
    '/subscriptions',
    data
  );
  return response.data.data;
}

/**
 * Get subscription by ID
 * GET /subscriptions/:id
 */
export async function getSubscription(id: number): Promise<Subscription> {
  const response = await apiClient.get<APIResponse<Subscription>>(
    `/subscriptions/${id}`
  );
  return response.data.data;
}

/**
 * List current user's subscriptions
 * GET /subscriptions
 */
export async function listSubscriptions(
  params?: ListSubscriptionsParams
): Promise<ListResponse<Subscription>> {
  const response = await apiClient.get<APIResponse<ListResponse<Subscription>>>(
    '/subscriptions',
    { params }
  );
  return response.data.data;
}

/**
 * Update subscription status (e.g., cancel)
 * PATCH /subscriptions/:id/status
 */
export async function updateSubscriptionStatus(
  id: number,
  data: UpdateSubscriptionStatusRequest
): Promise<void> {
  await apiClient.patch<APIResponse<null>>(
    `/subscriptions/${id}/status`,
    data
  );
}

/**
 * Change subscription plan
 * PATCH /subscriptions/:id/plan
 */
export async function changePlan(
  id: number,
  data: ChangePlanRequest
): Promise<void> {
  await apiClient.patch<APIResponse<null>>(
    `/subscriptions/${id}/plan`,
    data
  );
}

// ============================================================================
// Subscription Plan APIs
// ============================================================================

/**
 * Get public plans (no auth required)
 * GET /subscription-plans/public
 */
export async function getPublicPlans(): Promise<SubscriptionPlan[]> {
  const response = await apiClient.get<APIResponse<SubscriptionPlan[]>>(
    '/subscription-plans/public'
  );
  return response.data.data;
}

/**
 * Get plan by ID
 * GET /subscription-plans/:id
 */
export async function getPlan(id: number): Promise<SubscriptionPlan> {
  const response = await apiClient.get<APIResponse<SubscriptionPlan>>(
    `/subscription-plans/${id}`
  );
  return response.data.data;
}

/**
 * List all plans (admin)
 * GET /subscription-plans
 */
export async function listPlans(
  params?: ListPlansParams
): Promise<ListResponse<SubscriptionPlan>> {
  const response = await apiClient.get<APIResponse<ListResponse<SubscriptionPlan>>>(
    '/subscription-plans',
    { params }
  );
  return response.data.data;
}

/**
 * Create a new plan (admin)
 * POST /subscription-plans
 */
export async function createPlan(
  data: CreatePlanRequest
): Promise<SubscriptionPlan> {
  const response = await apiClient.post<APIResponse<SubscriptionPlan>>(
    '/subscription-plans',
    data
  );
  return response.data.data;
}

/**
 * Update a plan (admin)
 * PUT /subscription-plans/:id
 */
export async function updatePlan(
  id: number,
  data: UpdatePlanRequest
): Promise<SubscriptionPlan> {
  const response = await apiClient.put<APIResponse<SubscriptionPlan>>(
    `/subscription-plans/${id}`,
    data
  );
  return response.data.data;
}

/**
 * Update plan status (admin)
 * PATCH /subscription-plans/:id/status
 */
export async function updatePlanStatus(
  id: number,
  data: UpdatePlanStatusRequest
): Promise<void> {
  await apiClient.patch<APIResponse<null>>(
    `/subscription-plans/${id}/status`,
    data
  );
}

/**
 * Get plan pricings
 * GET /subscription-plans/:id/pricings
 */
export async function getPlanPricings(id: number): Promise<SubscriptionPlan> {
  const response = await apiClient.get<APIResponse<SubscriptionPlan>>(
    `/subscription-plans/${id}/pricings`
  );
  return response.data.data;
}

// ============================================================================
// Subscription Token APIs
// ============================================================================

/**
 * Generate a new subscription token
 * POST /subscriptions/:id/tokens
 */
export async function generateToken(
  subscriptionId: number,
  data: GenerateTokenRequest
): Promise<GenerateTokenResponse> {
  const response = await apiClient.post<APIResponse<GenerateTokenResponse>>(
    `/subscriptions/${subscriptionId}/tokens`,
    data
  );
  return response.data.data;
}

/**
 * List subscription tokens
 * GET /subscriptions/:id/tokens
 */
export async function listTokens(
  subscriptionId: number,
  params?: ListTokensParams
): Promise<SubscriptionToken[]> {
  const response = await apiClient.get<APIResponse<SubscriptionToken[]>>(
    `/subscriptions/${subscriptionId}/tokens`,
    { params }
  );
  return response.data.data;
}

/**
 * Revoke a subscription token
 * DELETE /subscriptions/:id/tokens/:tokenId
 */
export async function revokeToken(
  subscriptionId: number,
  tokenId: number
): Promise<void> {
  await apiClient.delete<APIResponse<null>>(
    `/subscriptions/${subscriptionId}/tokens/${tokenId}`
  );
}

/**
 * Refresh a subscription token
 * POST /subscriptions/:id/tokens/:tokenId/refresh
 */
export async function refreshSubscriptionToken(
  subscriptionId: number,
  tokenId: number
): Promise<RefreshTokenResponse> {
  const response = await apiClient.post<APIResponse<RefreshTokenResponse>>(
    `/subscriptions/${subscriptionId}/tokens/${tokenId}/refresh`
  );
  return response.data.data;
}
