/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 */

/**
 * Subscription entity
 */
export interface Subscription {
  id: number;
  userId: number;
  plan?: SubscriptionPlan;
  status: SubscriptionStatus;
  startDate: string;
  endDate: string;
  autoRenew: boolean;
  currentPeriodStart: string;
  currentPeriodEnd: string;
  isExpired: boolean;
  isActive: boolean;
  cancelledAt?: string;
  cancelReason?: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * Subscription status
 */
export type SubscriptionStatus = 'active' | 'cancelled' | 'renewed' | 'expired' | 'pending';

/**
 * Subscription plan entity
 */
export interface SubscriptionPlan {
  id: number;
  name: string;
  slug: string;
  description: string;
  /** @deprecated Use pricings array instead */
  price: number;
  /** @deprecated Use pricings array instead */
  currency: string;
  /** @deprecated Use pricings array instead */
  billingCycle: string;
  trialDays: number;
  status: PlanStatus;
  features?: string[];
  limits?: Record<string, unknown>;
  apiRateLimit: number;
  maxUsers: number;
  maxProjects: number;
  isPublic: boolean;
  sortOrder: number;
  pricings?: PricingOption[];
  createdAt: string;
  updatedAt: string;
}

/**
 * Plan status
 */
export type PlanStatus = 'active' | 'inactive';

/**
 * Pricing option for a plan
 */
export interface PricingOption {
  billingCycle: BillingCycle;
  price: number;
  currency: string;
  isActive: boolean;
}

/**
 * Billing cycle options
 */
export type BillingCycle = 'weekly' | 'monthly' | 'quarterly' | 'semi_annual' | 'yearly' | 'lifetime';

/**
 * Subscription token
 */
export interface SubscriptionToken {
  id: number;
  subscriptionId: number;
  name: string;
  prefix: string;
  scope: TokenScope;
  expiresAt?: string;
  lastUsedAt?: string;
  usageCount: number;
  isActive: boolean;
  createdAt: string;
}

/**
 * Token scope
 */
export type TokenScope = 'full' | 'readonly' | 'traffic_only';

/**
 * Create subscription request
 * POST /subscriptions
 */
export interface CreateSubscriptionRequest {
  planId: number;
  billingCycle: BillingCycle;
  startDate?: string;
  autoRenew?: boolean;
  paymentInfo?: Record<string, unknown>;
}

/**
 * Create subscription response
 */
export interface CreateSubscriptionResponse {
  subscription: Subscription;
  token: SubscriptionToken;
}

/**
 * Update subscription status request
 * PATCH /subscriptions/:id/status
 */
export interface UpdateSubscriptionStatusRequest {
  status: 'cancelled';
  reason?: string;
  immediate?: boolean;
}

/**
 * Change plan request
 * PATCH /subscriptions/:id/plan
 */
export interface ChangePlanRequest {
  newPlanId: number;
  changeType: 'upgrade' | 'downgrade';
  effectiveDate: 'immediate' | 'period_end';
}

/**
 * List subscriptions params
 * GET /subscriptions
 */
export interface ListSubscriptionsParams {
  page?: number;
  pageSize?: number;
  status?: SubscriptionStatus;
}

/**
 * Create plan request
 * POST /subscription-plans
 */
export interface CreatePlanRequest {
  name: string;
  slug: string;
  description?: string;
  price: number;
  currency: string;
  billingCycle: string;
  trialDays?: number;
  features?: string[];
  limits?: Record<string, unknown>;
  apiRateLimit?: number;
  maxUsers?: number;
  maxProjects?: number;
  isPublic?: boolean;
  sortOrder?: number;
}

/**
 * Update plan request
 * PUT /subscription-plans/:id
 */
export interface UpdatePlanRequest {
  description?: string;
  price?: number;
  currency?: string;
  features?: string[];
  limits?: Record<string, unknown>;
  apiRateLimit?: number;
  maxUsers?: number;
  maxProjects?: number;
  isPublic?: boolean;
  sortOrder?: number;
}

/**
 * Update plan status request
 * PATCH /subscription-plans/:id/status
 */
export interface UpdatePlanStatusRequest {
  status: PlanStatus;
}

/**
 * List plans params
 * GET /subscription-plans
 */
export interface ListPlansParams {
  page?: number;
  pageSize?: number;
  status?: PlanStatus;
  isPublic?: boolean;
  billingCycle?: string;
}

/**
 * Generate token request
 * POST /subscriptions/:id/tokens
 */
export interface GenerateTokenRequest {
  name: string;
  scope: TokenScope;
  expiresAt?: string;
}

/**
 * Generate token response
 * Returns the raw token value (only shown once)
 */
export interface GenerateTokenResponse {
  /** The raw token value (only shown once, store securely) */
  token: string;
  /** Token ID for future reference */
  tokenId: number;
  /** Token prefix for identification */
  prefix: string;
  /** Token expiration time */
  expiresAt?: string;
  /** Token creation time */
  createdAt: string;
}

/**
 * Refresh token response
 * Returns a new token to replace the old one
 */
export interface RefreshTokenResponse {
  /** The new raw token value (only shown once, store securely) */
  newToken: string;
  /** New token ID */
  tokenId: number;
  /** Token expiration time */
  expiresAt?: string;
}

/**
 * List tokens params
 * GET /subscriptions/:id/tokens
 */
export interface ListTokensParams {
  activeOnly?: boolean;
}
