/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2025-12-19
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 *
 * Recent changes:
 * - 2025-12-19: Changed all IDs to Stripe-style string format (sub_xxx, plan_xxx, stoken_xxx)
 * - 2025-12-19: Changed Subscription.id to string, added userId as string
 * - 2025-12-19: Changed SubscriptionPlan.id to string
 * - 2025-12-19: Changed SubscriptionToken.id to string, added subscriptionId as string
 * - 2025-12-18: Added Plan-Node entitlement management types (BindNodesRequest, UnbindNodesRequest, PlanNode, GetPlanNodesResult)
 * - 2025-12-18: Removed price, currency, billingCycle from SubscriptionPlan (now use pricings array only)
 * - 2025-12-18: Added PlanType type and planType field to SubscriptionPlan
 */

/**
 * Subscription entity
 * Updated: 2025-12-19 - Changed id to Stripe-style string (sub_xxx), added userId as string
 */
export interface Subscription {
  /** Stripe-style ID: sub_xxx */
  id: string;
  /** User's Stripe-style ID */
  userId: string;
  /** Unique identifier for subscription link */
  uuid: string;
  /** Full subscribe URL for clients (e.g., https://api.example.com/s/{uuid}) */
  subscribeUrl: string;
  plan?: SubscriptionPlan;
  status: SubscriptionStatus;
  startDate: string;
  endDate: string;
  autoRenew: boolean;
  currentPeriodStart: string;
  currentPeriodEnd: string;
  isExpired: boolean;
  isActive: boolean;
  cancelledAt?: string;
  cancelReason?: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * Subscription status
 */
export type SubscriptionStatus = 'active' | 'cancelled' | 'renewed' | 'expired' | 'pending';

/**
 * Subscription plan entity
 * Updated: 2025-12-19 - Changed id to Stripe-style string (plan_xxx)
 */
export interface SubscriptionPlan {
  /** Stripe-style ID: plan_xxx */
  id: string;
  name: string;
  slug: string;
  description: string;
  trialDays: number;
  status: PlanStatus;
  /** Plan type: node or forward */
  planType: PlanType;
  limits?: Record<string, unknown>;
  apiRateLimit: number;
  maxUsers: number;
  maxProjects: number;
  isPublic: boolean;
  sortOrder: number;
  /** Multiple pricing options for different billing cycles */
  pricings: PricingOption[];
  createdAt: string;
  updatedAt: string;
}

/**
 * Plan status
 */
export type PlanStatus = 'active' | 'inactive';

/**
 * Plan type - determines the subscription service type
 */
export type PlanType = 'node' | 'forward';

/**
 * Pricing option for a plan
 */
export interface PricingOption {
  billingCycle: BillingCycle;
  price: number;
  currency: string;
  isActive: boolean;
}

/**
 * Billing cycle options
 */
export type BillingCycle = 'weekly' | 'monthly' | 'quarterly' | 'semi_annual' | 'yearly' | 'lifetime';

/**
 * Subscription token
 * Updated: 2025-12-19 - Changed id to Stripe-style string (stoken_xxx), added subscriptionId as string
 */
export interface SubscriptionToken {
  /** Stripe-style ID: stoken_xxx */
  id: string;
  /** Subscription's Stripe-style ID */
  subscriptionId: string;
  name: string;
  prefix: string;
  scope: TokenScope;
  expiresAt?: string;
  lastUsedAt?: string;
  usageCount: number;
  isActive: boolean;
  createdAt: string;
}

/**
 * Token scope
 */
export type TokenScope = 'full' | 'readonly' | 'traffic_only';

/**
 * Create subscription request
 * POST /subscriptions
 * Updated: 2025-12-19 - Changed planId to string (Stripe-style ID)
 */
export interface CreateSubscriptionRequest {
  /** Plan's Stripe-style ID: plan_xxx */
  planId: string;
  billingCycle: BillingCycle;
  startDate?: string;
  autoRenew?: boolean;
  paymentInfo?: Record<string, unknown>;
}

/**
 * Create subscription response
 */
export interface CreateSubscriptionResponse {
  subscription: Subscription;
  token: SubscriptionToken;
}

/**
 * Update subscription status request
 * PATCH /subscriptions/:id/status
 */
export interface UpdateSubscriptionStatusRequest {
  status: 'cancelled';
  reason?: string;
  immediate?: boolean;
}

/**
 * Change plan request
 * PATCH /subscriptions/:id/plan
 * Updated: 2025-12-19 - Changed newPlanId to string (Stripe-style ID)
 */
export interface ChangePlanRequest {
  /** New plan's Stripe-style ID: plan_xxx */
  newPlanId: string;
  changeType: 'upgrade' | 'downgrade';
  effectiveDate: 'immediate' | 'period_end';
}

/**
 * List subscriptions params
 * GET /subscriptions
 */
export interface ListSubscriptionsParams {
  page?: number;
  pageSize?: number;
  status?: SubscriptionStatus;
}

/**
 * Pricing option input for creating/updating plans
 */
export interface PricingOptionInput {
  billingCycle: string;
  price: number;
  currency: string;
  isActive?: boolean;
}

/**
 * Create plan request
 * POST /plans
 */
export interface CreatePlanRequest {
  name: string;
  slug: string;
  description?: string;
  /** Plan type: node or forward (required) */
  planType: PlanType;
  trialDays?: number;
  limits?: Record<string, unknown>;
  apiRateLimit?: number;
  maxUsers?: number;
  maxProjects?: number;
  isPublic?: boolean;
  sortOrder?: number;
  /** Required: at least one pricing option must be provided */
  pricings: PricingOptionInput[];
}

/**
 * Update plan request
 * PUT /plans/:id
 */
export interface UpdatePlanRequest {
  description?: string;
  limits?: Record<string, unknown>;
  apiRateLimit?: number;
  maxUsers?: number;
  maxProjects?: number;
  isPublic?: boolean;
  sortOrder?: number;
  /** Optional: update pricing options for different billing cycles */
  pricings?: PricingOptionInput[];
}

/**
 * Update plan status request
 * PATCH /plans/:id/status
 */
export interface UpdatePlanStatusRequest {
  status: PlanStatus;
}

/**
 * List plans params
 * GET /plans
 */
export interface ListPlansParams {
  page?: number;
  pageSize?: number;
  status?: PlanStatus;
  isPublic?: boolean;
  /** Filter by plan type: node or forward */
  planType?: PlanType;
}

/**
 * Generate token request
 * POST /subscriptions/:id/tokens
 */
export interface GenerateTokenRequest {
  name: string;
  scope: TokenScope;
  expiresAt?: string;
}

/**
 * Generate token response
 * Returns the raw token value (only shown once)
 * Updated: 2025-12-19 - Changed tokenId to string (Stripe-style ID)
 */
export interface GenerateTokenResponse {
  /** The raw token value (only shown once, store securely) */
  token: string;
  /** Token's Stripe-style ID: stoken_xxx */
  tokenId: string;
  /** Token prefix for identification */
  prefix: string;
  /** Token expiration time */
  expiresAt?: string;
  /** Token creation time */
  createdAt: string;
}

/**
 * Refresh token response
 * Returns a new token to replace the old one
 * Updated: 2025-12-19 - Changed tokenId to string (Stripe-style ID)
 */
export interface RefreshTokenResponse {
  /** The new raw token value (only shown once, store securely) */
  newToken: string;
  /** New token's Stripe-style ID: stoken_xxx */
  tokenId: string;
  /** Token expiration time */
  expiresAt?: string;
}

/**
 * List tokens params
 * GET /subscriptions/:id/tokens
 */
export interface ListTokensParams {
  activeOnly?: boolean;
}

/**
 * Traffic stats query params
 * GET /subscriptions/:id/traffic-stats
 */
export interface GetTrafficStatsParams {
  /** Start time in RFC3339 format (required) */
  from: string;
  /** End time in RFC3339 format (required) */
  to: string;
  /** Granularity: hour, day, or month */
  granularity?: 'hour' | 'day' | 'month';
  /** Page number (default: 1) */
  page?: number;
  /** Page size (default: 100, max: 1000) */
  pageSize?: number;
}

/**
 * Traffic stats record
 */
export interface TrafficStatsRecord {
  nodeId: number;
  upload: number;
  download: number;
  total: number;
  period: string;
}

/**
 * Traffic summary
 */
export interface TrafficSummary {
  totalUpload: number;
  totalDownload: number;
  total: number;
}

/**
 * Traffic stats response
 * GET /subscriptions/:id/traffic-stats
 */
export interface TrafficStatsResponse {
  records: TrafficStatsRecord[];
  summary: TrafficSummary;
  total: number;
  page: number;
  pageSize: number;
}

// ============================================================================
// Plan-Node Entitlement Management Types
// Added: 2025-12-18
// ============================================================================

/**
 * A node associated with a plan
 * Used in GetPlanNodesResult
 */
export interface PlanNode {
  id: number;
  name: string;
  serverAddress: string;
  protocol: string;
  status: string;
}

/**
 * Result of getting plan nodes
 * GET /plans/:id/nodes
 */
export interface GetPlanNodesResult {
  nodes: PlanNode[];
  total: number;
}

/**
 * Bind nodes to plan request
 * POST /plans/:id/nodes
 */
export interface BindNodesRequest {
  /** Array of node IDs to bind to the plan */
  nodeIds: number[];
}

/**
 * Unbind nodes from plan request
 * DELETE /plans/:id/nodes
 */
export interface UnbindNodesRequest {
  /** Array of node IDs to unbind from the plan */
  nodeIds: number[];
}

// ============================================================================
// Admin Subscription Management Types
// Migrated from admin SDK: 2025-12-19
// ============================================================================

/**
 * Admin create subscription request
 * POST /admin/subscriptions
 * Updated: 2025-12-19 - Changed userId and planId to string (Stripe-style IDs)
 */
export interface AdminCreateSubscriptionRequest {
  /** User's Stripe-style ID: user_xxx */
  userId: string;
  /** Plan's Stripe-style ID: plan_xxx */
  planId: string;
  billingCycle: BillingCycle;
  startDate?: string;
  autoRenew?: boolean;
  paymentInfo?: Record<string, unknown>;
  /** Whether to activate immediately, defaults to true for admin */
  activate?: boolean;
}

/**
 * Admin create subscription response
 * Returns both subscription and token
 */
export interface AdminCreateSubscriptionResponse {
  subscription: Subscription;
  token: SubscriptionToken;
}

/**
 * Admin update subscription status request
 * PATCH /admin/subscriptions/:id/status
 */
export interface AdminUpdateSubscriptionStatusRequest {
  /** Status to set: active (activate), cancelled (cancel), renewed (renew) */
  status: 'active' | 'cancelled' | 'renewed';
  /** Cancellation reason (required when status is 'cancelled') */
  reason?: string;
  /** Whether to cancel immediately or at period end (for cancellation) */
  immediate?: boolean;
}

/**
 * Admin change plan request
 * PATCH /admin/subscriptions/:id/plan
 * Updated: 2025-12-19 - Changed newPlanId to string (Stripe-style ID: plan_xxx)
 */
export interface AdminChangePlanRequest {
  /** New plan's Stripe-style ID: plan_xxx */
  newPlanId: string;
  changeType: 'upgrade' | 'downgrade';
  effectiveDate: 'immediate' | 'period_end';
}

/**
 * Admin list subscriptions params
 * GET /admin/subscriptions
 */
export interface AdminListSubscriptionsParams {
  page?: number;
  pageSize?: number;
  userId?: number;
  status?: SubscriptionStatus;
}
