/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2026-03-07
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 *
 * ID Format: All ID parameters accept Stripe-style prefixed IDs
 * - Forward Agent: "fa_xK9mP2vL3nQ" (prefix: fa_)
 * - Forward Rule: "fr_xK9mP2vL3nQ" (prefix: fr_)
 * - Subscription: "sub_xK9mP2vL3nQ" (prefix: sub_)
 *
 * Recent changes:
 * - 2026-03-02: targetAddress supports private/internal IPs for LAN forwarding
 * - 2026-02-03: Synced with types.ts changes (groupSids array, UserGroupInfo)
 * - 2026-02-02: Synced with LoadBalanceStrategy type updates in types.ts
 * - 2026-01-10: Added batch operation APIs (batchCreateForwardRules, batchDeleteForwardRules, etc.)
 * - 2026-01-07: Added subscription forward rule APIs (createSubscriptionForwardRule, listSubscriptionForwardRules, etc.)
 * - 2026-01-05: Updated listForwardAgents/listUserForwardAgents to use sortBy/sortOrder params
 * - 2026-01-04: Added broadcastAPIURLChange for notifying agents of API URL migration
 * - 2026-01-02: Added subscribeForwardAgentEvents for SSE real-time agent event subscription
 */

import { apiClient } from '@/shared/lib/axios';
import type { APIResponse, ListResponse } from '@/shared/types/api.types';
import type {
  ForwardRule,
  CreateForwardRuleRequest,
  UpdateForwardRuleRequest,
  UpdateForwardRuleStatusRequest,
  ListForwardRulesParams,
  ReorderForwardRulesRequest,
  ForwardAgent,
  ForwardAgentWithToken,
  CreateForwardAgentRequest,
  UpdateForwardAgentRequest,
  UpdateForwardAgentStatusRequest,
  ListForwardAgentsParams,
  RegenerateTokenResponse,
  GetAgentTokenResponse,
  AgentRuntimeStatus,
  AgentVersionInfo,
  TriggerUpdateResponse,
  AgentBatchUpdateRequest,
  AgentBatchUpdateResponse,
  RuleOverallStatusResponse,
  ExitEndpoint,
  ProbeRuleRequest,
  RuleProbeResponse,
  InstallCommandResponse,
  GetInstallScriptParams,
  UserForwardUsage,
  UserForwardAgent,
  ListUserForwardAgentsParams,
  ForwardAgentEvent,
  ForwardAgentEventsParams,
  BroadcastAPIURLChangedRequest,
  BroadcastAPIURLChangedResponse,
  NotifyAgentAPIURLChangedRequest,
  NotifyAgentAPIURLChangedResponse,
  // Subscription forward rule types (Added: 2026-01-07)
  SubscriptionForwardUsage,
  CreateSubscriptionForwardRuleRequest,
  UpdateSubscriptionForwardRuleRequest,
  ListSubscriptionForwardRulesParams,
  // Batch operation types (Added: 2026-01-10)
  BatchOperationResult,
  BatchCreateResponse,
  BatchCreateForwardRulesRequest,
  BatchDeleteForwardRulesRequest,
  BatchToggleForwardRulesStatusRequest,
  BatchUpdateForwardRulesRequest,
} from './types';

// ========== Forward Rule APIs ==========

/**
 * Create forward rule (Admin only)
 * POST /forward-rules
 *
 * targetAddress accepts both public and private/internal IPs (e.g., 192.168.x, 10.x)
 * for LAN forwarding scenarios. The forwarding agent connects to the target, not the backend.
 */
export const createForwardRule = async (
  data: CreateForwardRuleRequest
): Promise<ForwardRule> => {
  const response = await apiClient.post<APIResponse<ForwardRule>>('/forward-rules', data);
  return response.data.data;
};

/**
 * Get forward rule by ID (Admin only)
 * GET /forward-rules/:id
 */
export const getForwardRule = async (id: number | string): Promise<ForwardRule> => {
  const response = await apiClient.get<APIResponse<ForwardRule>>(`/forward-rules/${id}`);
  return response.data.data;
};

/**
 * Update forward rule (Admin only)
 * PUT /forward-rules/:id
 *
 */
export const updateForwardRule = async (
  id: number | string,
  data: UpdateForwardRuleRequest
): Promise<void> => {
  await apiClient.put(`/forward-rules/${id}`, data);
};

/**
 * Delete forward rule (Admin only)
 * DELETE /forward-rules/:id
 */
export const deleteForwardRule = async (id: number | string): Promise<void> => {
  await apiClient.delete(`/forward-rules/${id}`);
};

/**
 * List forward rules (Admin only)
 * GET /forward-rules
 */
export const listForwardRules = async (
  params?: ListForwardRulesParams
): Promise<ListResponse<ForwardRule>> => {
  const response = await apiClient.get<APIResponse<ListResponse<ForwardRule>>>(
    '/forward-rules',
    { params }
  );
  return response.data.data;
};

/**
 * Update forward rule status (Admin only)
 * PATCH /forward-rules/:id/status
 */
export const updateForwardRuleStatus = async (
  id: number | string,
  data: UpdateForwardRuleStatusRequest
): Promise<void> => {
  await apiClient.patch(`/forward-rules/${id}/status`, data);
};

/**
 * Enable forward rule (Admin only)
 * POST /forward-rules/:id/enable
 */
export const enableForwardRule = async (id: number | string): Promise<void> => {
  await apiClient.post(`/forward-rules/${id}/enable`);
};

/**
 * Disable forward rule (Admin only)
 * POST /forward-rules/:id/disable
 */
export const disableForwardRule = async (id: number | string): Promise<void> => {
  await apiClient.post(`/forward-rules/${id}/disable`);
};

/**
 * Reset forward rule traffic counters (Admin only)
 * POST /forward-rules/:id/reset-traffic
 */
export const resetForwardRuleTraffic = async (id: number | string): Promise<void> => {
  await apiClient.post(`/forward-rules/${id}/reset-traffic`);
};

/**
 * Reorder forward rules (Admin only)
 * PATCH /forward-rules/reorder
 *
 * Batch update sort order for multiple forward rules.
 * This is an admin-only operation that can reorder any rules.
 *
 * @param data - Reorder request containing array of rule orders
 *
 * @example
 * ```typescript
 * // Reorder rules to new positions
 * await reorderForwardRules({
 *   ruleOrders: [
 *     { ruleId: 'fr_xK9mP2vL3nQ', sortOrder: 100 },
 *     { ruleId: 'fr_yL8nQ3wM4oR', sortOrder: 200 },
 *     { ruleId: 'fr_zM7oR4xN5pS', sortOrder: 300 }
 *   ]
 * });
 * ```
 *
 * Added: 2025-12-23
 */
export const reorderForwardRules = async (
  data: ReorderForwardRulesRequest
): Promise<void> => {
  await apiClient.patch('/forward-rules/reorder', data);
};

// ========== Batch Forward Rule APIs (Admin) ==========
// Added: 2026-01-10

/**
 * Batch create forward rules (Admin only)
 * POST /forward-rules/batch
 *
 * Creates multiple forward rules in a single request.
 * Uses partial failure mode: continues processing even if some rules fail.
 * Maximum 100 rules per batch.
 *
 * @param data - Batch create request containing array of rules
 * @returns Batch create response with succeeded and failed items
 *
 * @example
 * ```typescript
 * const result = await batchCreateForwardRules({
 *   rules: [
 *     {
 *       agentId: 'fa_xK9mP2vL3nQ',
 *       ruleType: 'direct',
 *       name: 'MySQL Forward',
 *       targetAddress: '192.168.1.100',
 *       targetPort: 3306,
 *       protocol: 'tcp'
 *     },
 *     {
 *       agentId: 'fa_yL8nQ3wM4oR',
 *       ruleType: 'direct',
 *       name: 'Redis Forward',
 *       targetAddress: '192.168.1.101',
 *       targetPort: 6379,
 *       protocol: 'tcp'
 *     }
 *   ]
 * });
 * console.log(`Created ${result.succeeded.length} rules`);
 * if (result.failed?.length) {
 *   console.log(`Failed: ${result.failed.length}`);
 * }
 * ```
 *
 * Added: 2026-01-10
 */
export const batchCreateForwardRules = async (
  data: BatchCreateForwardRulesRequest
): Promise<BatchCreateResponse> => {
  const response = await apiClient.post<APIResponse<BatchCreateResponse>>(
    '/forward-rules/batch',
    data
  );
  return response.data.data;
};

/**
 * Batch delete forward rules (Admin only)
 * DELETE /forward-rules/batch
 *
 * Deletes multiple forward rules in a single transactional request.
 * All operations succeed or all fail (rollback on any error).
 * Pre-validation errors are returned before any deletion is attempted.
 * Maximum 100 rules per batch. Duplicate IDs are automatically deduplicated.
 *
 * @param data - Batch delete request containing array of rule IDs
 * @returns Batch operation result with succeeded and failed items
 *
 * @example
 * ```typescript
 * const result = await batchDeleteForwardRules({
 *   ruleIds: ['fr_xK9mP2vL3nQ', 'fr_yL8nQ3wM4oR', 'fr_zM7oR4xN5pS']
 * });
 * console.log(`Deleted ${result.succeeded.length} rules`);
 * ```
 *
 * Added: 2026-01-10
 */
export const batchDeleteForwardRules = async (
  data: BatchDeleteForwardRulesRequest
): Promise<BatchOperationResult> => {
  const response = await apiClient.delete<APIResponse<BatchOperationResult>>(
    '/forward-rules/batch',
    { data }
  );
  return response.data.data;
};

/**
 * Batch toggle forward rules status (Admin only)
 * PATCH /forward-rules/batch/status
 *
 * Enables or disables multiple forward rules in a single transactional request.
 * All operations succeed or all fail (rollback on any error).
 * Pre-validation errors are returned before any status change is attempted.
 * Maximum 100 rules per batch. Duplicate IDs are automatically deduplicated.
 *
 * @param data - Batch toggle status request containing rule IDs and target status
 * @returns Batch operation result with succeeded and failed items
 *
 * @example
 * ```typescript
 * // Enable multiple rules
 * const result = await batchToggleForwardRulesStatus({
 *   ruleIds: ['fr_xK9mP2vL3nQ', 'fr_yL8nQ3wM4oR'],
 *   status: 'enabled'
 * });
 * console.log(`Updated ${result.succeeded.length} rules`);
 * ```
 *
 * Added: 2026-01-10
 */
export const batchToggleForwardRulesStatus = async (
  data: BatchToggleForwardRulesStatusRequest
): Promise<BatchOperationResult> => {
  const response = await apiClient.patch<APIResponse<BatchOperationResult>>(
    '/forward-rules/batch/status',
    data
  );
  return response.data.data;
};

/**
 * Batch update forward rules (Admin only)
 * PATCH /forward-rules/batch
 *
 * Updates multiple forward rules' basic fields in a single transactional request.
 * Only name, remark, and sortOrder can be updated via batch operation.
 * All operations succeed or all fail (rollback on any error).
 * Pre-validation errors are returned before any update is attempted.
 * Maximum 100 rules per batch. Duplicate IDs are deduplicated (last occurrence wins).
 *
 * @param data - Batch update request containing array of updates
 * @returns Batch operation result with succeeded and failed items
 *
 * @example
 * ```typescript
 * const result = await batchUpdateForwardRules({
 *   updates: [
 *     { ruleId: 'fr_xK9mP2vL3nQ', name: 'New MySQL Name', sortOrder: 100 },
 *     { ruleId: 'fr_yL8nQ3wM4oR', remark: 'Updated remark', sortOrder: 200 }
 *   ]
 * });
 * console.log(`Updated ${result.succeeded.length} rules`);
 * ```
 *
 * Added: 2026-01-10
 */
export const batchUpdateForwardRules = async (
  data: BatchUpdateForwardRulesRequest
): Promise<BatchOperationResult> => {
  const response = await apiClient.patch<APIResponse<BatchOperationResult>>(
    '/forward-rules/batch',
    data
  );
  return response.data.data;
};

// ========== Forward Agent APIs ==========

/**
 * Create forward agent (Admin only)
 * POST /forward-agents
 * @returns Agent with token (token is only returned on creation)
 *
 * Note: The token does NOT need to be copied immediately. You can retrieve it
 * later via `getForwardAgentToken()` or `getInstallCommand()`.
 */
export const createForwardAgent = async (
  data: CreateForwardAgentRequest
): Promise<ForwardAgentWithToken> => {
  const response = await apiClient.post<APIResponse<ForwardAgentWithToken>>(
    '/forward-agents',
    data
  );
  return response.data.data;
};

/**
 * Get forward agent by ID (Admin only)
 * GET /forward-agents/:id
 */
export const getForwardAgent = async (id: number | string): Promise<ForwardAgent> => {
  const response = await apiClient.get<APIResponse<ForwardAgent>>(`/forward-agents/${id}`);
  return response.data.data;
};

/**
 * Update forward agent (Admin only)
 * PUT /forward-agents/:id
 */
export const updateForwardAgent = async (
  id: number | string,
  data: UpdateForwardAgentRequest
): Promise<void> => {
  await apiClient.put(`/forward-agents/${id}`, data);
};

/**
 * Delete forward agent (Admin only)
 * DELETE /forward-agents/:id
 */
export const deleteForwardAgent = async (id: number | string): Promise<void> => {
  await apiClient.delete(`/forward-agents/${id}`);
};

/**
 * List forward agents (Admin only)
 * GET /forward-agents
 */
export const listForwardAgents = async (
  params?: ListForwardAgentsParams
): Promise<ListResponse<ForwardAgent>> => {
  const response = await apiClient.get<APIResponse<ListResponse<ForwardAgent>>>(
    '/forward-agents',
    { params }
  );
  return response.data.data;
};

/**
 * Update forward agent status (Admin only)
 * PATCH /forward-agents/:id/status
 */
export const updateForwardAgentStatus = async (
  id: number | string,
  data: UpdateForwardAgentStatusRequest
): Promise<void> => {
  await apiClient.patch(`/forward-agents/${id}/status`, data);
};

/**
 * Enable forward agent (Admin only)
 * POST /forward-agents/:id/enable
 */
export const enableForwardAgent = async (id: number | string): Promise<void> => {
  await apiClient.post(`/forward-agents/${id}/enable`);
};

/**
 * Disable forward agent (Admin only)
 * POST /forward-agents/:id/disable
 */
export const disableForwardAgent = async (id: number | string): Promise<void> => {
  await apiClient.post(`/forward-agents/${id}/disable`);
};

/**
 * Get forward agent token (Admin only)
 * GET /forward-agents/:id/token
 * @returns Current token for the agent (without regenerating)
 */
export const getForwardAgentToken = async (
  id: number | string
): Promise<GetAgentTokenResponse> => {
  const response = await apiClient.get<APIResponse<GetAgentTokenResponse>>(
    `/forward-agents/${id}/token`
  );
  return response.data.data;
};

/**
 * Regenerate forward agent token (Admin only)
 * POST /forward-agents/:id/regenerate-token
 * @returns New token for the agent (generates a new token, invalidating the old one)
 */
export const regenerateForwardAgentToken = async (
  id: number | string
): Promise<RegenerateTokenResponse> => {
  const response = await apiClient.post<APIResponse<RegenerateTokenResponse>>(
    `/forward-agents/${id}/regenerate-token`
  );
  return response.data.data;
};

/**
 * Get forward agent runtime status (Admin only)
 * GET /forward-agents/:id/status
 * @returns Agent runtime status including CPU, memory, disk, connections, etc.
 *
 * Note: This is a dedicated endpoint for high-frequency polling of agent status.
 * For normal use cases, the systemStatus field in getForwardAgent response
 * provides the same information embedded in the agent details.
 */
export const getForwardAgentRuntimeStatus = async (
  id: number | string
): Promise<AgentRuntimeStatus> => {
  const response = await apiClient.get<APIResponse<AgentRuntimeStatus>>(
    `/forward-agents/${id}/status`
  );
  return response.data.data;
};

// ========== Agent Version APIs ==========
// Added: 2025-12-31

/**
 * Get forward agent version information (Admin only)
 * GET /forward-agents/:id/version
 * @returns Version info including current version, latest version, and update availability
 *
 * This endpoint fetches the agent's current version and compares it with the latest
 * available version from GitHub releases using semantic versioning.
 *
 * @example
 * ```typescript
 * const versionInfo = await getAgentVersion('fa_xK9mP2vL3nQ');
 * console.log(`Current: ${versionInfo.currentVersion}`);
 * console.log(`Latest: ${versionInfo.latestVersion}`);
 * if (versionInfo.hasUpdate) {
 *   console.log('Update available!');
 *   console.log(`Download: ${versionInfo.downloadUrl}`);
 * }
 * ```
 */
export const getAgentVersion = async (
  id: number | string
): Promise<AgentVersionInfo> => {
  const response = await apiClient.get<APIResponse<AgentVersionInfo>>(
    `/forward-agents/${id}/version`
  );
  return response.data.data;
};

/**
 * Trigger forward agent update (Admin only)
 * POST /forward-agents/:id/update
 * @returns Update command response with command ID for tracking
 *
 * Sends an update command to the agent via WebSocket to trigger self-update.
 * The agent must be online to receive the command.
 *
 * Prerequisites:
 * - Agent must be online (connected via WebSocket)
 * - Agent platform and architecture must be known
 * - A newer version must be available
 *
 * @example
 * ```typescript
 * try {
 *   const result = await triggerAgentUpdate('fa_xK9mP2vL3nQ');
 *   console.log(`Update triggered: ${result.commandId}`);
 *   console.log(`Target version: ${result.targetVersion}`);
 * } catch (error) {
 *   // Handle: agent offline, already latest, platform unknown, etc.
 * }
 * ```
 */
export const triggerAgentUpdate = async (
  id: number | string
): Promise<TriggerUpdateResponse> => {
  const response = await apiClient.post<APIResponse<TriggerUpdateResponse>>(
    `/forward-agents/${id}/update`
  );
  return response.data.data;
};

/**
 * Batch trigger forward agent updates (Admin only)
 * POST /forward-agents/batch-update
 * @returns Batch update response with succeeded, failed, and skipped agents
 *
 * Sends update commands to multiple agents at once.
 * Must specify exactly one of agentIds or updateAll.
 *
 * Each agent is processed independently:
 * - Succeeded: Update command sent successfully
 * - Failed: Error occurred (agent not found, no download available, etc.)
 * - Skipped: Agent offline, platform unknown, or already up to date
 *
 * @example
 * ```typescript
 * // Update specific agents
 * const result = await batchTriggerAgentUpdate({
 *   agentIds: ['fa_xK9mP2vL3nQ', 'fa_yL8nQ3wM4oR']
 * });
 * console.log(`Succeeded: ${result.succeeded.length}`);
 * console.log(`Failed: ${result.failed.length}`);
 * console.log(`Skipped: ${result.skipped.length}`);
 *
 * // Update all agents with available updates
 * const result = await batchTriggerAgentUpdate({ updateAll: true });
 * if (result.truncated) {
 *   console.log('Results truncated, max 1000 agents per request');
 * }
 * ```
 *
 * Added: 2025-12-31
 */
export const batchTriggerAgentUpdate = async (
  data: AgentBatchUpdateRequest
): Promise<AgentBatchUpdateResponse> => {
  const response = await apiClient.post<APIResponse<AgentBatchUpdateResponse>>(
    '/forward-agents/batch-update',
    data
  );
  return response.data.data;
};

/**
 * Broadcast API URL change to connected forward agents (Admin only)
 * POST /forward-agents/broadcast-url-change
 * @returns Response with count of notified forward agents
 *
 * Use this endpoint when migrating to a new API server.
 * Connected forward agents will receive a command to update their local
 * configuration and reconnect to the new URL.
 *
 * Prerequisites:
 * - Forward agents must be connected via WebSocket to receive the notification
 * - Admin authentication required
 *
 * Note: For nodes, use POST /nodes/broadcast-url-change (node SDK) instead.
 *
 * @example
 * ```typescript
 * const result = await broadcastAPIURLChange({
 *   newUrl: 'https://new-api.example.com',
 *   reason: 'Server migration to new data center'
 * });
 * console.log(`Notified ${result.agentsNotified} of ${result.agentsOnline} forward agents`);
 * ```
 *
 * Added: 2026-01-04
 * Updated: 2026-01-04 - Simplified to forward agents only (nodes use separate endpoint)
 */
export const broadcastAPIURLChange = async (
  data: BroadcastAPIURLChangedRequest
): Promise<BroadcastAPIURLChangedResponse> => {
  const response = await apiClient.post<APIResponse<BroadcastAPIURLChangedResponse>>(
    '/forward-agents/broadcast-url-change',
    data
  );
  return response.data.data;
};

/**
 * Notify a single forward agent of API URL change (Admin only)
 * POST /forward-agents/:id/url-change
 *
 * Use this endpoint to notify a specific forward agent when migrating to a new API server.
 * The agent will receive a notification to update its local configuration and reconnect.
 *
 * @param agentId - Stripe-style agent ID (e.g., "fa_xK9mP2vL3nQ")
 * @param data - URL change notification data
 * @returns Whether the notification was sent successfully
 *
 * @example
 * ```typescript
 * const result = await notifyAgentAPIURLChange('fa_xK9mP2vL3nQ', {
 *   newUrl: 'https://new-api.example.com',
 *   reason: 'Server migration'
 * });
 * if (result.notified) {
 *   console.log(`Agent ${result.agentId} was notified`);
 * } else {
 *   console.log(`Agent ${result.agentId} is not connected`);
 * }
 * ```
 *
 * Added: 2026-01-04
 */
export const notifyAgentAPIURLChange = async (
  agentId: string,
  data: NotifyAgentAPIURLChangedRequest
): Promise<NotifyAgentAPIURLChangedResponse> => {
  const response = await apiClient.post<APIResponse<NotifyAgentAPIURLChangedResponse>>(
    `/forward-agents/${agentId}/url-change`,
    data
  );
  return response.data.data;
};

// ========== Forward Agent API (Client APIs) ==========

/**
 * Get exit endpoint information for WS tunnel connection
 * GET /forward-agent-api/exit-endpoint/:agent_id
 * Note: Requires forward agent token authentication
 */
export const getExitEndpoint = async (agentId: number | string): Promise<ExitEndpoint> => {
  const response = await apiClient.get<APIResponse<ExitEndpoint>>(
    `/forward-agent-api/exit-endpoint/${agentId}`
  );
  return response.data.data;
};

// ========== Forward Rule Status APIs ==========

/**
 * Get forward rule overall status (Admin only)
 * GET /forward-rules/:id/status
 * @returns Aggregated status for a forward rule across all agents
 *
 * For multi-hop rules (entry, chain, direct_chain), this aggregates status from all agents:
 * - Overall sync status: failed > pending > synced (worst takes priority)
 * - Overall run status: error > stopped > starting > unknown > running (worst takes priority)
 *
 * @example
 * ```typescript
 * const status = await getRuleOverallStatus('fr_xK9mP2vL3nQ');
 * console.log(status.overallSyncStatus); // 'synced' | 'pending' | 'failed'
 * console.log(status.overallRunStatus);  // 'running' | 'stopped' | 'error' | 'starting' | 'unknown'
 * console.log(status.healthyAgents);     // Number of healthy agents
 * console.log(status.agentStatuses);     // Detailed per-agent status
 * ```
 *
 * Added: 2025-12-25
 */
export const getRuleOverallStatus = async (
  id: number | string
): Promise<RuleOverallStatusResponse> => {
  const response = await apiClient.get<APIResponse<RuleOverallStatusResponse>>(
    `/forward-rules/${id}/status`
  );
  return response.data.data;
};

// ========== Probe APIs ==========

/**
 * Probe a forward rule (Admin only)
 * POST /forward-rules/:id/probe
 * @param id Rule ID
 * @param data Optional probe request with IP version override
 * @returns Probe result with latency information
 *
 * For direct rules: returns targetLatencyMs
 * For entry rules: returns tunnelLatencyMs (entry→exit) + targetLatencyMs (exit→target)
 */
export const probeRule = async (
  id: number | string,
  data?: ProbeRuleRequest
): Promise<RuleProbeResponse> => {
  const response = await apiClient.post<APIResponse<RuleProbeResponse>>(
    `/forward-rules/${id}/probe`,
    data
  );
  return response.data.data;
};

// ========== Install Script APIs ==========

/**
 * Get install command for forward agent (Admin only)
 * GET /forward-agents/:id/install-script
 *
 * @param id Agent ID
 * @param params.token Optional: API token. If not provided, uses agent's stored token
 * @param params.serverUrl Optional: Override default server URL
 * @returns Install command that can be executed on target server
 *
 * Usage:
 * 1. Call getInstallCommand() to get the install command
 * 2. Copy and execute the installCommand on target server
 *
 * Example response:
 * {
 *   installCommand: "curl -fsSL https://...install.sh | sudo bash -s -- --server https://... --token fwd_xxx",
 *   uninstallCommand: "curl -fsSL https://...install.sh | sudo bash -s -- uninstall",
 *   scriptUrl: "https://raw.githubusercontent.com/orris-inc/orris-client/main/scripts/install.sh",
 *   serverUrl: "https://api.example.com",
 *   token: "fwd_xxx"
 * }
 */
export const getInstallCommand = async (
  id: number | string,
  params?: GetInstallScriptParams
): Promise<InstallCommandResponse> => {
  const response = await apiClient.get<APIResponse<InstallCommandResponse>>(
    `/forward-agents/${id}/install-script`,
    { params }
  );
  return response.data.data;
};

// ========== User Forward Rule APIs ==========

/**
 * Create user forward rule
 * POST /user/forward-rules
 * Note: User must have an active subscription with forward feature enabled
 *
 * targetAddress accepts private/internal IPs for LAN forwarding.
 */
export const createUserForwardRule = async (
  data: CreateForwardRuleRequest
): Promise<ForwardRule> => {
  const response = await apiClient.post<APIResponse<ForwardRule>>('/user/forward-rules', data);
  return response.data.data;
};

/**
 * List user's forward rules with pagination
 * GET /user/forward-rules
 */
export const listUserForwardRules = async (
  params?: ListForwardRulesParams
): Promise<ListResponse<ForwardRule>> => {
  const response = await apiClient.get<APIResponse<ListResponse<ForwardRule>>>(
    '/user/forward-rules',
    { params }
  );
  return response.data.data;
};

/**
 * Get user's forward rule usage and quota information
 * GET /user/forward-rules/usage
 * @returns Usage statistics including rule count, limits, traffic used, and allowed types
 */
export const getUserForwardUsage = async (): Promise<UserForwardUsage> => {
  const response = await apiClient.get<APIResponse<UserForwardUsage>>(
    '/user/forward-rules/usage'
  );
  return response.data.data;
};

/**
 * Get user's forward rule by ID
 * GET /user/forward-rules/:id
 * Note: User can only access their own forward rules
 */
export const getUserForwardRule = async (id: string): Promise<ForwardRule> => {
  const response = await apiClient.get<APIResponse<ForwardRule>>(
    `/user/forward-rules/${id}`
  );
  return response.data.data;
};

/**
 * Update user's forward rule
 * PUT /user/forward-rules/:id
 * Note: User can only update their own forward rules
 */
export const updateUserForwardRule = async (
  id: string,
  data: UpdateForwardRuleRequest
): Promise<void> => {
  await apiClient.put(`/user/forward-rules/${id}`, data);
};

/**
 * Delete user's forward rule
 * DELETE /user/forward-rules/:id
 * Note: User can only delete their own forward rules
 */
export const deleteUserForwardRule = async (id: string): Promise<void> => {
  await apiClient.delete(`/user/forward-rules/${id}`);
};

/**
 * Enable user's forward rule
 * POST /user/forward-rules/:id/enable
 * Note: User can only enable their own forward rules
 */
export const enableUserForwardRule = async (id: string): Promise<void> => {
  await apiClient.post(`/user/forward-rules/${id}/enable`);
};

/**
 * Disable user's forward rule
 * POST /user/forward-rules/:id/disable
 * Note: User can only disable their own forward rules
 */
export const disableUserForwardRule = async (id: string): Promise<void> => {
  await apiClient.post(`/user/forward-rules/${id}/disable`);
};

/**
 * Reorder user's forward rules
 * PATCH /user/forward-rules/reorder
 *
 * Batch update sort order for user's own forward rules.
 * Only rules owned by the authenticated user can be reordered.
 *
 * @param data - Reorder request containing array of rule orders
 *
 * @example
 * ```typescript
 * // Reorder user's rules to new positions
 * await reorderUserForwardRules({
 *   ruleOrders: [
 *     { ruleId: 'fr_xK9mP2vL3nQ', sortOrder: 100 },
 *     { ruleId: 'fr_yL8nQ3wM4oR', sortOrder: 200 }
 *   ]
 * });
 * ```
 *
 * Added: 2025-12-23
 */
export const reorderUserForwardRules = async (
  data: ReorderForwardRulesRequest
): Promise<void> => {
  await apiClient.patch('/user/forward-rules/reorder', data);
};

// ========== Batch User Forward Rule APIs ==========
// Added: 2026-01-10

/**
 * Batch create user forward rules
 * POST /user/forward-rules/batch
 *
 * Creates multiple forward rules for the authenticated user in a single request.
 * Uses partial failure mode: continues processing even if some rules fail.
 * Maximum 100 rules per batch.
 *
 * @param data - Batch create request containing array of rules
 * @returns Batch create response with succeeded and failed items
 *
 * @example
 * ```typescript
 * const result = await batchCreateUserForwardRules({
 *   rules: [
 *     {
 *       agentId: 'fa_xK9mP2vL3nQ',
 *       ruleType: 'direct',
 *       name: 'MySQL Forward',
 *       targetAddress: '192.168.1.100',
 *       targetPort: 3306,
 *       protocol: 'tcp'
 *     },
 *     {
 *       agentId: 'fa_yL8nQ3wM4oR',
 *       ruleType: 'direct',
 *       name: 'Redis Forward',
 *       targetAddress: '192.168.1.101',
 *       targetPort: 6379,
 *       protocol: 'tcp'
 *     }
 *   ]
 * });
 * ```
 *
 * Added: 2026-01-10
 */
export const batchCreateUserForwardRules = async (
  data: BatchCreateForwardRulesRequest
): Promise<BatchCreateResponse> => {
  const response = await apiClient.post<APIResponse<BatchCreateResponse>>(
    '/user/forward-rules/batch',
    data
  );
  return response.data.data;
};

/**
 * Batch delete user forward rules
 * DELETE /user/forward-rules/batch
 *
 * Deletes multiple forward rules owned by the authenticated user.
 * All operations succeed or all fail (rollback on any error).
 * Ownership is validated in the UseCase layer.
 * Maximum 100 rules per batch. Duplicate IDs are automatically deduplicated.
 *
 * @param data - Batch delete request containing array of rule IDs
 * @returns Batch operation result with succeeded and failed items
 *
 * @example
 * ```typescript
 * const result = await batchDeleteUserForwardRules({
 *   ruleIds: ['fr_xK9mP2vL3nQ', 'fr_yL8nQ3wM4oR']
 * });
 * ```
 *
 * Added: 2026-01-10
 */
export const batchDeleteUserForwardRules = async (
  data: BatchDeleteForwardRulesRequest
): Promise<BatchOperationResult> => {
  const response = await apiClient.delete<APIResponse<BatchOperationResult>>(
    '/user/forward-rules/batch',
    { data }
  );
  return response.data.data;
};

/**
 * Batch toggle user forward rules status
 * PATCH /user/forward-rules/batch/status
 *
 * Enables or disables multiple forward rules owned by the authenticated user.
 * All operations succeed or all fail (rollback on any error).
 * Ownership is validated in the UseCase layer.
 * Maximum 100 rules per batch. Duplicate IDs are automatically deduplicated.
 *
 * @param data - Batch toggle status request containing rule IDs and target status
 * @returns Batch operation result with succeeded and failed items
 *
 * @example
 * ```typescript
 * // Enable multiple rules
 * const result = await batchToggleUserForwardRulesStatus({
 *   ruleIds: ['fr_xK9mP2vL3nQ', 'fr_yL8nQ3wM4oR'],
 *   status: 'enabled'
 * });
 * ```
 *
 * Added: 2026-01-10
 */
export const batchToggleUserForwardRulesStatus = async (
  data: BatchToggleForwardRulesStatusRequest
): Promise<BatchOperationResult> => {
  const response = await apiClient.patch<APIResponse<BatchOperationResult>>(
    '/user/forward-rules/batch/status',
    data
  );
  return response.data.data;
};

/**
 * Batch update user forward rules
 * PATCH /user/forward-rules/batch
 *
 * Updates multiple forward rules' basic fields owned by the authenticated user.
 * Only name, remark, and sortOrder can be updated via batch operation.
 * All operations succeed or all fail (rollback on any error).
 * Ownership is validated in the UseCase layer.
 * Maximum 100 rules per batch. Duplicate IDs are deduplicated (last occurrence wins).
 *
 * @param data - Batch update request containing array of updates
 * @returns Batch operation result with succeeded and failed items
 *
 * @example
 * ```typescript
 * const result = await batchUpdateUserForwardRules({
 *   updates: [
 *     { ruleId: 'fr_xK9mP2vL3nQ', name: 'New Name', sortOrder: 100 },
 *     { ruleId: 'fr_yL8nQ3wM4oR', remark: 'Updated', sortOrder: 200 }
 *   ]
 * });
 * ```
 *
 * Added: 2026-01-10
 */
export const batchUpdateUserForwardRules = async (
  data: BatchUpdateForwardRulesRequest
): Promise<BatchOperationResult> => {
  const response = await apiClient.patch<APIResponse<BatchOperationResult>>(
    '/user/forward-rules/batch',
    data
  );
  return response.data.data;
};

// ========== User Forward Agent APIs ==========
// Added: 2025-12-19

/**
 * List user's accessible forward agents with pagination
 * GET /user/forward-agents
 *
 * Returns forward agents that are accessible to the user through their subscriptions.
 * The access is determined by: User → Subscription → Plan → ResourceGroup → ForwardAgent
 *
 * @param params - Pagination and filter parameters
 * @returns Paginated list of user-accessible forward agents
 *
 * @example
 * ```typescript
 * const agents = await listUserForwardAgents({ page: 1, pageSize: 20 });
 * console.log(agents.items); // UserForwardAgent[]
 * ```
 */
export const listUserForwardAgents = async (
  params?: ListUserForwardAgentsParams
): Promise<ListResponse<UserForwardAgent>> => {
  const response = await apiClient.get<APIResponse<ListResponse<UserForwardAgent>>>(
    '/user/forward-agents',
    { params }
  );
  return response.data.data;
};

// ============================================================================
// Forward Agent SSE (Server-Sent Events) APIs
// Added: 2026-01-02
// ============================================================================

/**
 * Build absolute URL for SSE endpoint
 * Handles both absolute and relative baseURL configurations
 */
function buildSSEUrl(path: string, params?: Record<string, string>): string {
  const baseUrl = apiClient.defaults.baseURL || '';

  // Build the full path
  let fullUrl: string;
  if (baseUrl.startsWith('http://') || baseUrl.startsWith('https://')) {
    // Absolute URL
    fullUrl = `${baseUrl}${path}`;
  } else {
    // Relative URL - use current origin
    const origin = typeof window !== 'undefined' ? window.location.origin : '';
    fullUrl = `${origin}${baseUrl}${path}`;
  }

  // Add query params
  if (params && Object.keys(params).length > 0) {
    const searchParams = new URLSearchParams(params);
    fullUrl += `?${searchParams.toString()}`;
  }

  return fullUrl;
}

/**
 * SSE connection options for forward agent events
 */
export interface ForwardAgentEventsOptions {
  /** Callback when connection is established */
  onOpen?: () => void;
  /** Callback for each received event */
  onEvent: (event: ForwardAgentEvent) => void;
  /** Callback on error (connection will be closed on repeated errors) */
  onError?: (error: Event) => void;
  /** Callback when connection is closed */
  onClose?: () => void;
  /** Max consecutive errors before closing connection (default: 3) */
  maxRetries?: number;
}

/**
 * Subscribe to real-time forward agent events via SSE
 * GET /forward-agents/events
 * @param params - Optional filter params (agentIds: comma-separated agent IDs)
 * @param options - Event handlers and configuration
 * @requires Admin role (authentication via cookies)
 * @returns Cleanup function to close the SSE connection
 * Added: 2026-01-02
 *
 * Note: SSE uses cookie-based authentication. Ensure the user is logged in
 * and cookies are properly set before calling this function.
 *
 * The connection will automatically close after maxRetries consecutive errors
 * (e.g., authentication failures) to prevent infinite reconnection loops.
 *
 * @example
 * ```ts
 * const cleanup = subscribeForwardAgentEvents(
 *   { agentIds: 'fa_abc,fa_xyz' },
 *   {
 *     onOpen: () => console.log('Connected'),
 *     onEvent: (event) => {
 *       switch (event.type) {
 *         case 'agent:online':
 *           console.log(`Agent ${event.agentName} is online`);
 *           break;
 *         case 'agent:offline':
 *           console.log(`Agent ${event.agentName} is offline`);
 *           break;
 *         case 'agent:status':
 *           console.log(`Agent ${event.agentId} status:`, event.data);
 *           break;
 *       }
 *     },
 *     onError: (error) => console.error('SSE error:', error),
 *     onClose: () => console.log('Disconnected'),
 *   }
 * );
 *
 * // Later, to close the connection:
 * cleanup();
 * ```
 */
export function subscribeForwardAgentEvents(
  params: ForwardAgentEventsParams | undefined,
  options: ForwardAgentEventsOptions
): () => void {
  const { onOpen, onEvent, onError, onClose, maxRetries = 3 } = options;

  // Build URL with query params
  const queryParams: Record<string, string> = {};
  if (params?.agentIds) {
    queryParams['agent_ids'] = params.agentIds;
  }

  const url = buildSSEUrl('/forward-agents/events', queryParams);

  const eventSource = new EventSource(url, {
    withCredentials: true, // Send cookies for authentication
  });

  let errorCount = 0;
  let isClosed = false;

  // Handle connection open
  eventSource.onopen = () => {
    errorCount = 0; // Reset error count on successful connection
    if (onOpen) {
      onOpen();
    }
  };

  // Handle specific event types
  const eventTypes = ['agent:online', 'agent:offline', 'agent:status', 'agent:updated', 'agents:status'];
  eventTypes.forEach((eventType) => {
    eventSource.addEventListener(eventType, (e: MessageEvent) => {
      errorCount = 0; // Reset error count on successful message
      try {
        const event = JSON.parse(e.data) as ForwardAgentEvent;
        onEvent(event);
      } catch (err) {
        console.error('Failed to parse SSE event:', err);
      }
    });
  });

  // Handle errors with retry limit to prevent infinite reconnection
  eventSource.onerror = (error) => {
    errorCount++;

    if (onError) {
      onError(error);
    }

    // Close connection after max retries to prevent infinite reconnection
    // (e.g., when session expires or user is unauthorized)
    if (errorCount >= maxRetries && !isClosed) {
      console.warn(
        `SSE connection closed after ${maxRetries} consecutive errors. ` +
        'This may indicate an authentication issue.'
      );
      eventSource.close();
      isClosed = true;
      if (onClose) {
        onClose();
      }
    }
  };

  // Return cleanup function
  return () => {
    if (!isClosed) {
      eventSource.close();
      isClosed = true;
      if (onClose) {
        onClose();
      }
    }
  };
}

// ============================================================================
// Subscription Forward Rule APIs
// Added: 2026-01-07
// ============================================================================

/**
 * Create subscription forward rule
 * POST /subscriptions/:sid/forward-rules
 * @param subscriptionId - Subscription's Stripe-style ID (sub_xxx)
 * @param data - Forward rule creation request
 * @returns Created forward rule
 *
 * Note: User must own the subscription. Rules are bound to the subscription
 * and count against the subscription's rule quota.
 *
 * @example
 * ```typescript
 * const rule = await createSubscriptionForwardRule('sub_xK9mP2vL3nQ', {
 *   agentId: 'fa_xK9mP2vL3nQ',
 *   ruleType: 'direct',
 *   name: 'MySQL Forward',
 *   targetAddress: '192.168.1.100',  // Private IPs allowed for LAN forwarding
 *   targetPort: 3306,
 *   protocol: 'tcp'
 * });
 * console.log(`Created rule: ${rule.id}`);
 * ```
 */
export const createSubscriptionForwardRule = async (
  subscriptionId: string,
  data: CreateSubscriptionForwardRuleRequest
): Promise<ForwardRule> => {
  const response = await apiClient.post<APIResponse<ForwardRule>>(
    `/subscriptions/${subscriptionId}/forward-rules`,
    data
  );
  return response.data.data;
};

/**
 * List subscription's forward rules with pagination
 * GET /subscriptions/:sid/forward-rules
 * @param subscriptionId - Subscription's Stripe-style ID (sub_xxx)
 * @param params - Pagination and filter parameters
 * @returns Paginated list of forward rules
 *
 * @example
 * ```typescript
 * const result = await listSubscriptionForwardRules('sub_xK9mP2vL3nQ', {
 *   page: 1,
 *   pageSize: 20,
 *   status: 'enabled'
 * });
 * console.log(`Found ${result.total} rules`);
 * ```
 */
export const listSubscriptionForwardRules = async (
  subscriptionId: string,
  params?: ListSubscriptionForwardRulesParams
): Promise<ListResponse<ForwardRule>> => {
  const response = await apiClient.get<APIResponse<ListResponse<ForwardRule>>>(
    `/subscriptions/${subscriptionId}/forward-rules`,
    { params }
  );
  return response.data.data;
};

/**
 * Get subscription forward usage and quota information
 * GET /subscriptions/:sid/forward-rules/usage
 * @param subscriptionId - Subscription's Stripe-style ID (sub_xxx)
 * @returns Usage statistics including rule count, limits, traffic used, and allowed types
 *
 * @example
 * ```typescript
 * const usage = await getSubscriptionForwardUsage('sub_xK9mP2vL3nQ');
 * console.log(`Rules: ${usage.ruleCount}/${usage.ruleLimit}`);
 * console.log(`Traffic: ${usage.trafficUsed}/${usage.trafficLimit}`);
 * console.log(`Allowed types: ${usage.allowedTypes.join(', ')}`);
 * ```
 */
export const getSubscriptionForwardUsage = async (
  subscriptionId: string
): Promise<SubscriptionForwardUsage> => {
  const response = await apiClient.get<APIResponse<SubscriptionForwardUsage>>(
    `/subscriptions/${subscriptionId}/forward-rules/usage`
  );
  return response.data.data;
};

/**
 * Get subscription forward rule by ID
 * GET /subscriptions/:sid/forward-rules/:rule_id
 * @param subscriptionId - Subscription's Stripe-style ID (sub_xxx)
 * @param ruleId - Rule's Stripe-style ID (fr_xxx)
 * @returns Forward rule details
 *
 * Note: User can only access rules that belong to their subscription.
 */
export const getSubscriptionForwardRule = async (
  subscriptionId: string,
  ruleId: string
): Promise<ForwardRule> => {
  const response = await apiClient.get<APIResponse<ForwardRule>>(
    `/subscriptions/${subscriptionId}/forward-rules/${ruleId}`
  );
  return response.data.data;
};

/**
 * Update subscription forward rule
 * PUT /subscriptions/:sid/forward-rules/:rule_id
 * @param subscriptionId - Subscription's Stripe-style ID (sub_xxx)
 * @param ruleId - Rule's Stripe-style ID (fr_xxx)
 * @param data - Update request
 *
 * Note: User can only update rules that belong to their subscription.
 */
export const updateSubscriptionForwardRule = async (
  subscriptionId: string,
  ruleId: string,
  data: UpdateSubscriptionForwardRuleRequest
): Promise<void> => {
  await apiClient.put(
    `/subscriptions/${subscriptionId}/forward-rules/${ruleId}`,
    data
  );
};

/**
 * Delete subscription forward rule
 * DELETE /subscriptions/:sid/forward-rules/:rule_id
 * @param subscriptionId - Subscription's Stripe-style ID (sub_xxx)
 * @param ruleId - Rule's Stripe-style ID (fr_xxx)
 *
 * Note: User can only delete rules that belong to their subscription.
 */
export const deleteSubscriptionForwardRule = async (
  subscriptionId: string,
  ruleId: string
): Promise<void> => {
  await apiClient.delete(
    `/subscriptions/${subscriptionId}/forward-rules/${ruleId}`
  );
};

/**
 * Enable subscription forward rule
 * POST /subscriptions/:sid/forward-rules/:rule_id/enable
 * @param subscriptionId - Subscription's Stripe-style ID (sub_xxx)
 * @param ruleId - Rule's Stripe-style ID (fr_xxx)
 *
 * Note: User can only enable rules that belong to their subscription.
 */
export const enableSubscriptionForwardRule = async (
  subscriptionId: string,
  ruleId: string
): Promise<void> => {
  await apiClient.post(
    `/subscriptions/${subscriptionId}/forward-rules/${ruleId}/enable`
  );
};

/**
 * Disable subscription forward rule
 * POST /subscriptions/:sid/forward-rules/:rule_id/disable
 * @param subscriptionId - Subscription's Stripe-style ID (sub_xxx)
 * @param ruleId - Rule's Stripe-style ID (fr_xxx)
 *
 * Note: User can only disable rules that belong to their subscription.
 */
export const disableSubscriptionForwardRule = async (
  subscriptionId: string,
  ruleId: string
): Promise<void> => {
  await apiClient.post(
    `/subscriptions/${subscriptionId}/forward-rules/${ruleId}/disable`
  );
};

/**
 * Reorder subscription forward rules
 * PATCH /subscriptions/:sid/forward-rules/reorder
 * @param subscriptionId - Subscription's Stripe-style ID (sub_xxx)
 * @param data - Reorder request containing array of rule orders
 *
 * Batch update sort order for subscription's forward rules.
 * Only rules that belong to this subscription can be reordered.
 *
 * @example
 * ```typescript
 * await reorderSubscriptionForwardRules('sub_xK9mP2vL3nQ', {
 *   ruleOrders: [
 *     { ruleId: 'fr_aaa', sortOrder: 100 },
 *     { ruleId: 'fr_bbb', sortOrder: 200 },
 *     { ruleId: 'fr_ccc', sortOrder: 300 }
 *   ]
 * });
 * ```
 */
export const reorderSubscriptionForwardRules = async (
  subscriptionId: string,
  data: { ruleOrders: Array<{ ruleId: string; sortOrder: number }> }
): Promise<void> => {
  await apiClient.patch(
    `/subscriptions/${subscriptionId}/forward-rules/reorder`,
    data
  );
};

