/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2025-12-31
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 *
 * ID Format: All ID parameters accept Stripe-style prefixed IDs
 * - Forward Agent: "fa_xK9mP2vL3nQ" (prefix: fa_)
 * - Forward Rule: "fr_xK9mP2vL3nQ" (prefix: fr_)
 */

import { apiClient } from '@/shared/lib/axios';
import type { APIResponse, ListResponse } from '@/shared/types/api.types';
import type {
  ForwardRule,
  CreateForwardRuleRequest,
  UpdateForwardRuleRequest,
  UpdateForwardRuleStatusRequest,
  ListForwardRulesParams,
  ReorderForwardRulesRequest,
  ForwardAgent,
  ForwardAgentWithToken,
  CreateForwardAgentRequest,
  UpdateForwardAgentRequest,
  UpdateForwardAgentStatusRequest,
  ListForwardAgentsParams,
  RegenerateTokenResponse,
  GetAgentTokenResponse,
  AgentRuntimeStatus,
  AgentVersionInfo,
  TriggerUpdateResponse,
  AgentBatchUpdateRequest,
  AgentBatchUpdateResponse,
  RuleOverallStatusResponse,
  ExitEndpoint,
  ProbeRuleRequest,
  RuleProbeResponse,
  InstallCommandResponse,
  GetInstallScriptParams,
  UserForwardUsage,
  UserForwardAgent,
  ListUserForwardAgentsParams,
} from './types';

// ========== Forward Rule APIs ==========

/**
 * Create forward rule (Admin only)
 * POST /forward-rules
 */
export const createForwardRule = async (
  data: CreateForwardRuleRequest
): Promise<ForwardRule> => {
  const response = await apiClient.post<APIResponse<ForwardRule>>('/forward-rules', data);
  return response.data.data;
};

/**
 * Get forward rule by ID (Admin only)
 * GET /forward-rules/:id
 */
export const getForwardRule = async (id: number | string): Promise<ForwardRule> => {
  const response = await apiClient.get<APIResponse<ForwardRule>>(`/forward-rules/${id}`);
  return response.data.data;
};

/**
 * Update forward rule (Admin only)
 * PUT /forward-rules/:id
 */
export const updateForwardRule = async (
  id: number | string,
  data: UpdateForwardRuleRequest
): Promise<void> => {
  await apiClient.put(`/forward-rules/${id}`, data);
};

/**
 * Delete forward rule (Admin only)
 * DELETE /forward-rules/:id
 */
export const deleteForwardRule = async (id: number | string): Promise<void> => {
  await apiClient.delete(`/forward-rules/${id}`);
};

/**
 * List forward rules (Admin only)
 * GET /forward-rules
 */
export const listForwardRules = async (
  params?: ListForwardRulesParams
): Promise<ListResponse<ForwardRule>> => {
  const response = await apiClient.get<APIResponse<ListResponse<ForwardRule>>>(
    '/forward-rules',
    { params }
  );
  return response.data.data;
};

/**
 * Update forward rule status (Admin only)
 * PATCH /forward-rules/:id/status
 */
export const updateForwardRuleStatus = async (
  id: number | string,
  data: UpdateForwardRuleStatusRequest
): Promise<void> => {
  await apiClient.patch(`/forward-rules/${id}/status`, data);
};

/**
 * Enable forward rule (Admin only)
 * POST /forward-rules/:id/enable
 */
export const enableForwardRule = async (id: number | string): Promise<void> => {
  await apiClient.post(`/forward-rules/${id}/enable`);
};

/**
 * Disable forward rule (Admin only)
 * POST /forward-rules/:id/disable
 */
export const disableForwardRule = async (id: number | string): Promise<void> => {
  await apiClient.post(`/forward-rules/${id}/disable`);
};

/**
 * Reset forward rule traffic counters (Admin only)
 * POST /forward-rules/:id/reset-traffic
 */
export const resetForwardRuleTraffic = async (id: number | string): Promise<void> => {
  await apiClient.post(`/forward-rules/${id}/reset-traffic`);
};

/**
 * Reorder forward rules (Admin only)
 * PATCH /forward-rules/reorder
 *
 * Batch update sort order for multiple forward rules.
 * This is an admin-only operation that can reorder any rules.
 *
 * @param data - Reorder request containing array of rule orders
 *
 * @example
 * ```typescript
 * // Reorder rules to new positions
 * await reorderForwardRules({
 *   ruleOrders: [
 *     { ruleId: 'fr_xK9mP2vL3nQ', sortOrder: 100 },
 *     { ruleId: 'fr_yL8nQ3wM4oR', sortOrder: 200 },
 *     { ruleId: 'fr_zM7oR4xN5pS', sortOrder: 300 }
 *   ]
 * });
 * ```
 *
 * Added: 2025-12-23
 */
export const reorderForwardRules = async (
  data: ReorderForwardRulesRequest
): Promise<void> => {
  await apiClient.patch('/forward-rules/reorder', data);
};

// ========== Forward Agent APIs ==========

/**
 * Create forward agent (Admin only)
 * POST /forward-agents
 * @returns Agent with token (token is only returned on creation)
 */
export const createForwardAgent = async (
  data: CreateForwardAgentRequest
): Promise<ForwardAgentWithToken> => {
  const response = await apiClient.post<APIResponse<ForwardAgentWithToken>>(
    '/forward-agents',
    data
  );
  return response.data.data;
};

/**
 * Get forward agent by ID (Admin only)
 * GET /forward-agents/:id
 */
export const getForwardAgent = async (id: number | string): Promise<ForwardAgent> => {
  const response = await apiClient.get<APIResponse<ForwardAgent>>(`/forward-agents/${id}`);
  return response.data.data;
};

/**
 * Update forward agent (Admin only)
 * PUT /forward-agents/:id
 */
export const updateForwardAgent = async (
  id: number | string,
  data: UpdateForwardAgentRequest
): Promise<void> => {
  await apiClient.put(`/forward-agents/${id}`, data);
};

/**
 * Delete forward agent (Admin only)
 * DELETE /forward-agents/:id
 */
export const deleteForwardAgent = async (id: number | string): Promise<void> => {
  await apiClient.delete(`/forward-agents/${id}`);
};

/**
 * List forward agents (Admin only)
 * GET /forward-agents
 */
export const listForwardAgents = async (
  params?: ListForwardAgentsParams
): Promise<ListResponse<ForwardAgent>> => {
  const response = await apiClient.get<APIResponse<ListResponse<ForwardAgent>>>(
    '/forward-agents',
    { params }
  );
  return response.data.data;
};

/**
 * Update forward agent status (Admin only)
 * PATCH /forward-agents/:id/status
 */
export const updateForwardAgentStatus = async (
  id: number | string,
  data: UpdateForwardAgentStatusRequest
): Promise<void> => {
  await apiClient.patch(`/forward-agents/${id}/status`, data);
};

/**
 * Enable forward agent (Admin only)
 * POST /forward-agents/:id/enable
 */
export const enableForwardAgent = async (id: number | string): Promise<void> => {
  await apiClient.post(`/forward-agents/${id}/enable`);
};

/**
 * Disable forward agent (Admin only)
 * POST /forward-agents/:id/disable
 */
export const disableForwardAgent = async (id: number | string): Promise<void> => {
  await apiClient.post(`/forward-agents/${id}/disable`);
};

/**
 * Get forward agent token (Admin only)
 * GET /forward-agents/:id/token
 * @returns Current token for the agent (without regenerating)
 */
export const getForwardAgentToken = async (
  id: number | string
): Promise<GetAgentTokenResponse> => {
  const response = await apiClient.get<APIResponse<GetAgentTokenResponse>>(
    `/forward-agents/${id}/token`
  );
  return response.data.data;
};

/**
 * Regenerate forward agent token (Admin only)
 * POST /forward-agents/:id/regenerate-token
 * @returns New token for the agent (generates a new token, invalidating the old one)
 */
export const regenerateForwardAgentToken = async (
  id: number | string
): Promise<RegenerateTokenResponse> => {
  const response = await apiClient.post<APIResponse<RegenerateTokenResponse>>(
    `/forward-agents/${id}/regenerate-token`
  );
  return response.data.data;
};

/**
 * Get forward agent runtime status (Admin only)
 * GET /forward-agents/:id/status
 * @returns Agent runtime status including CPU, memory, disk, connections, etc.
 *
 * Note: This is a dedicated endpoint for high-frequency polling of agent status.
 * For normal use cases, the systemStatus field in getForwardAgent response
 * provides the same information embedded in the agent details.
 */
export const getForwardAgentRuntimeStatus = async (
  id: number | string
): Promise<AgentRuntimeStatus> => {
  const response = await apiClient.get<APIResponse<AgentRuntimeStatus>>(
    `/forward-agents/${id}/status`
  );
  return response.data.data;
};

// ========== Agent Version APIs ==========
// Added: 2025-12-31

/**
 * Get forward agent version information (Admin only)
 * GET /forward-agents/:id/version
 * @returns Version info including current version, latest version, and update availability
 *
 * This endpoint fetches the agent's current version and compares it with the latest
 * available version from GitHub releases using semantic versioning.
 *
 * @example
 * ```typescript
 * const versionInfo = await getAgentVersion('fa_xK9mP2vL3nQ');
 * console.log(`Current: ${versionInfo.currentVersion}`);
 * console.log(`Latest: ${versionInfo.latestVersion}`);
 * if (versionInfo.hasUpdate) {
 *   console.log('Update available!');
 *   console.log(`Download: ${versionInfo.downloadUrl}`);
 * }
 * ```
 */
export const getAgentVersion = async (
  id: number | string
): Promise<AgentVersionInfo> => {
  const response = await apiClient.get<APIResponse<AgentVersionInfo>>(
    `/forward-agents/${id}/version`
  );
  return response.data.data;
};

/**
 * Trigger forward agent update (Admin only)
 * POST /forward-agents/:id/update
 * @returns Update command response with command ID for tracking
 *
 * Sends an update command to the agent via WebSocket to trigger self-update.
 * The agent must be online to receive the command.
 *
 * Prerequisites:
 * - Agent must be online (connected via WebSocket)
 * - Agent platform and architecture must be known
 * - A newer version must be available
 *
 * @example
 * ```typescript
 * try {
 *   const result = await triggerAgentUpdate('fa_xK9mP2vL3nQ');
 *   console.log(`Update triggered: ${result.commandId}`);
 *   console.log(`Target version: ${result.targetVersion}`);
 * } catch (error) {
 *   // Handle: agent offline, already latest, platform unknown, etc.
 * }
 * ```
 */
export const triggerAgentUpdate = async (
  id: number | string
): Promise<TriggerUpdateResponse> => {
  const response = await apiClient.post<APIResponse<TriggerUpdateResponse>>(
    `/forward-agents/${id}/update`
  );
  return response.data.data;
};

/**
 * Batch trigger forward agent updates (Admin only)
 * POST /forward-agents/batch-update
 * @returns Batch update response with succeeded, failed, and skipped agents
 *
 * Sends update commands to multiple agents at once.
 * Must specify exactly one of agentIds or updateAll.
 *
 * Each agent is processed independently:
 * - Succeeded: Update command sent successfully
 * - Failed: Error occurred (agent not found, no download available, etc.)
 * - Skipped: Agent offline, platform unknown, or already up to date
 *
 * @example
 * ```typescript
 * // Update specific agents
 * const result = await batchTriggerAgentUpdate({
 *   agentIds: ['fa_xK9mP2vL3nQ', 'fa_yL8nQ3wM4oR']
 * });
 * console.log(`Succeeded: ${result.succeeded.length}`);
 * console.log(`Failed: ${result.failed.length}`);
 * console.log(`Skipped: ${result.skipped.length}`);
 *
 * // Update all agents with available updates
 * const result = await batchTriggerAgentUpdate({ updateAll: true });
 * if (result.truncated) {
 *   console.log('Results truncated, max 1000 agents per request');
 * }
 * ```
 *
 * Added: 2025-12-31
 */
export const batchTriggerAgentUpdate = async (
  data: AgentBatchUpdateRequest
): Promise<AgentBatchUpdateResponse> => {
  const response = await apiClient.post<APIResponse<AgentBatchUpdateResponse>>(
    '/forward-agents/batch-update',
    data
  );
  return response.data.data;
};

// ========== Forward Agent API (Client APIs) ==========

/**
 * Get exit endpoint information for WS tunnel connection
 * GET /forward-agent-api/exit-endpoint/:agent_id
 * Note: Requires forward agent token authentication
 */
export const getExitEndpoint = async (agentId: number | string): Promise<ExitEndpoint> => {
  const response = await apiClient.get<APIResponse<ExitEndpoint>>(
    `/forward-agent-api/exit-endpoint/${agentId}`
  );
  return response.data.data;
};

// ========== Forward Rule Status APIs ==========

/**
 * Get forward rule overall status (Admin only)
 * GET /forward-rules/:id/status
 * @returns Aggregated status for a forward rule across all agents
 *
 * For multi-hop rules (entry, chain, direct_chain), this aggregates status from all agents:
 * - Overall sync status: failed > pending > synced (worst takes priority)
 * - Overall run status: error > stopped > starting > unknown > running (worst takes priority)
 *
 * @example
 * ```typescript
 * const status = await getRuleOverallStatus('fr_xK9mP2vL3nQ');
 * console.log(status.overallSyncStatus); // 'synced' | 'pending' | 'failed'
 * console.log(status.overallRunStatus);  // 'running' | 'stopped' | 'error' | 'starting' | 'unknown'
 * console.log(status.healthyAgents);     // Number of healthy agents
 * console.log(status.agentStatuses);     // Detailed per-agent status
 * ```
 *
 * Added: 2025-12-25
 */
export const getRuleOverallStatus = async (
  id: number | string
): Promise<RuleOverallStatusResponse> => {
  const response = await apiClient.get<APIResponse<RuleOverallStatusResponse>>(
    `/forward-rules/${id}/status`
  );
  return response.data.data;
};

// ========== Probe APIs ==========

/**
 * Probe a forward rule (Admin only)
 * POST /forward-rules/:id/probe
 * @param id Rule ID
 * @param data Optional probe request with IP version override
 * @returns Probe result with latency information
 *
 * For direct rules: returns targetLatencyMs
 * For entry rules: returns tunnelLatencyMs (entry→exit) + targetLatencyMs (exit→target)
 */
export const probeRule = async (
  id: number | string,
  data?: ProbeRuleRequest
): Promise<RuleProbeResponse> => {
  const response = await apiClient.post<APIResponse<RuleProbeResponse>>(
    `/forward-rules/${id}/probe`,
    data
  );
  return response.data.data;
};

// ========== Install Script APIs ==========

/**
 * Get install command for forward agent (Admin only)
 * GET /forward-agents/:id/install-script
 *
 * @param id Agent ID
 * @param params.token Optional: API token. If not provided, uses agent's stored token
 * @param params.serverUrl Optional: Override default server URL
 * @returns Install command that can be executed on target server
 *
 * Usage:
 * 1. Call getInstallCommand() to get the install command
 * 2. Copy and execute the installCommand on target server
 *
 * Example response:
 * {
 *   installCommand: "curl -fsSL https://...install.sh | sudo bash -s -- --server https://... --token fwd_xxx",
 *   uninstallCommand: "curl -fsSL https://...install.sh | sudo bash -s -- uninstall",
 *   scriptUrl: "https://raw.githubusercontent.com/orris-inc/orris-client/main/scripts/install.sh",
 *   serverUrl: "https://api.example.com",
 *   token: "fwd_xxx"
 * }
 */
export const getInstallCommand = async (
  id: number | string,
  params?: GetInstallScriptParams
): Promise<InstallCommandResponse> => {
  const response = await apiClient.get<APIResponse<InstallCommandResponse>>(
    `/forward-agents/${id}/install-script`,
    { params }
  );
  return response.data.data;
};

// ========== User Forward Rule APIs ==========

/**
 * Create user forward rule
 * POST /user/forward-rules
 * Note: User must have an active subscription with forward feature enabled
 */
export const createUserForwardRule = async (
  data: CreateForwardRuleRequest
): Promise<ForwardRule> => {
  const response = await apiClient.post<APIResponse<ForwardRule>>('/user/forward-rules', data);
  return response.data.data;
};

/**
 * List user's forward rules with pagination
 * GET /user/forward-rules
 */
export const listUserForwardRules = async (
  params?: ListForwardRulesParams
): Promise<ListResponse<ForwardRule>> => {
  const response = await apiClient.get<APIResponse<ListResponse<ForwardRule>>>(
    '/user/forward-rules',
    { params }
  );
  return response.data.data;
};

/**
 * Get user's forward rule usage and quota information
 * GET /user/forward-rules/usage
 * @returns Usage statistics including rule count, limits, traffic used, and allowed types
 */
export const getUserForwardUsage = async (): Promise<UserForwardUsage> => {
  const response = await apiClient.get<APIResponse<UserForwardUsage>>(
    '/user/forward-rules/usage'
  );
  return response.data.data;
};

/**
 * Get user's forward rule by ID
 * GET /user/forward-rules/:id
 * Note: User can only access their own forward rules
 */
export const getUserForwardRule = async (id: string): Promise<ForwardRule> => {
  const response = await apiClient.get<APIResponse<ForwardRule>>(
    `/user/forward-rules/${id}`
  );
  return response.data.data;
};

/**
 * Update user's forward rule
 * PUT /user/forward-rules/:id
 * Note: User can only update their own forward rules
 */
export const updateUserForwardRule = async (
  id: string,
  data: UpdateForwardRuleRequest
): Promise<void> => {
  await apiClient.put(`/user/forward-rules/${id}`, data);
};

/**
 * Delete user's forward rule
 * DELETE /user/forward-rules/:id
 * Note: User can only delete their own forward rules
 */
export const deleteUserForwardRule = async (id: string): Promise<void> => {
  await apiClient.delete(`/user/forward-rules/${id}`);
};

/**
 * Enable user's forward rule
 * POST /user/forward-rules/:id/enable
 * Note: User can only enable their own forward rules
 */
export const enableUserForwardRule = async (id: string): Promise<void> => {
  await apiClient.post(`/user/forward-rules/${id}/enable`);
};

/**
 * Disable user's forward rule
 * POST /user/forward-rules/:id/disable
 * Note: User can only disable their own forward rules
 */
export const disableUserForwardRule = async (id: string): Promise<void> => {
  await apiClient.post(`/user/forward-rules/${id}/disable`);
};

/**
 * Reorder user's forward rules
 * PATCH /user/forward-rules/reorder
 *
 * Batch update sort order for user's own forward rules.
 * Only rules owned by the authenticated user can be reordered.
 *
 * @param data - Reorder request containing array of rule orders
 *
 * @example
 * ```typescript
 * // Reorder user's rules to new positions
 * await reorderUserForwardRules({
 *   ruleOrders: [
 *     { ruleId: 'fr_xK9mP2vL3nQ', sortOrder: 100 },
 *     { ruleId: 'fr_yL8nQ3wM4oR', sortOrder: 200 }
 *   ]
 * });
 * ```
 *
 * Added: 2025-12-23
 */
export const reorderUserForwardRules = async (
  data: ReorderForwardRulesRequest
): Promise<void> => {
  await apiClient.patch('/user/forward-rules/reorder', data);
};

// ========== User Forward Agent APIs ==========
// Added: 2025-12-19

/**
 * List user's accessible forward agents with pagination
 * GET /user/forward-agents
 *
 * Returns forward agents that are accessible to the user through their subscriptions.
 * The access is determined by: User → Subscription → Plan → ResourceGroup → ForwardAgent
 *
 * @param params - Pagination and filter parameters
 * @returns Paginated list of user-accessible forward agents
 *
 * @example
 * ```typescript
 * const agents = await listUserForwardAgents({ page: 1, pageSize: 20 });
 * console.log(agents.items); // UserForwardAgent[]
 * ```
 */
export const listUserForwardAgents = async (
  params?: ListUserForwardAgentsParams
): Promise<ListResponse<UserForwardAgent>> => {
  const response = await apiClient.get<APIResponse<ListResponse<UserForwardAgent>>>(
    '/user/forward-agents',
    { params }
  );
  return response.data.data;
};

