/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2025-12-09
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 *
 * ID Format: All ID parameters accept Stripe-style prefixed IDs
 * - Forward Agent: "fa_xK9mP2vL3nQ" (prefix: fa_)
 * - Forward Rule: "fr_xK9mP2vL3nQ" (prefix: fr_)
 */

import { apiClient } from '@/shared/lib/axios';
import type { APIResponse, ListResponse } from '@/shared/types/api.types';
import type {
  ForwardRule,
  CreateForwardRuleRequest,
  UpdateForwardRuleRequest,
  UpdateForwardRuleStatusRequest,
  ListForwardRulesParams,
  ForwardAgent,
  ForwardAgentWithToken,
  CreateForwardAgentRequest,
  UpdateForwardAgentRequest,
  UpdateForwardAgentStatusRequest,
  ListForwardAgentsParams,
  RegenerateTokenResponse,
  GetAgentTokenResponse,
  AgentRuntimeStatus,
  ExitEndpoint,
  ProbeRuleRequest,
  RuleProbeResponse,
  InstallCommandResponse,
  GetInstallScriptParams,
} from './types';

// ========== Forward Rule APIs ==========

/**
 * Create forward rule (Admin only)
 * POST /forward-rules
 */
export const createForwardRule = async (
  data: CreateForwardRuleRequest
): Promise<ForwardRule> => {
  const response = await apiClient.post<APIResponse<ForwardRule>>('/forward-rules', data);
  return response.data.data;
};

/**
 * Get forward rule by ID (Admin only)
 * GET /forward-rules/:id
 */
export const getForwardRule = async (id: number | string): Promise<ForwardRule> => {
  const response = await apiClient.get<APIResponse<ForwardRule>>(`/forward-rules/${id}`);
  return response.data.data;
};

/**
 * Update forward rule (Admin only)
 * PUT /forward-rules/:id
 */
export const updateForwardRule = async (
  id: number | string,
  data: UpdateForwardRuleRequest
): Promise<void> => {
  await apiClient.put(`/forward-rules/${id}`, data);
};

/**
 * Delete forward rule (Admin only)
 * DELETE /forward-rules/:id
 */
export const deleteForwardRule = async (id: number | string): Promise<void> => {
  await apiClient.delete(`/forward-rules/${id}`);
};

/**
 * List forward rules (Admin only)
 * GET /forward-rules
 */
export const listForwardRules = async (
  params?: ListForwardRulesParams
): Promise<ListResponse<ForwardRule>> => {
  const response = await apiClient.get<APIResponse<ListResponse<ForwardRule>>>(
    '/forward-rules',
    { params }
  );
  return response.data.data;
};

/**
 * Update forward rule status (Admin only)
 * PATCH /forward-rules/:id/status
 */
export const updateForwardRuleStatus = async (
  id: number | string,
  data: UpdateForwardRuleStatusRequest
): Promise<void> => {
  await apiClient.patch(`/forward-rules/${id}/status`, data);
};

/**
 * Enable forward rule (Admin only)
 * POST /forward-rules/:id/enable
 */
export const enableForwardRule = async (id: number | string): Promise<void> => {
  await apiClient.post(`/forward-rules/${id}/enable`);
};

/**
 * Disable forward rule (Admin only)
 * POST /forward-rules/:id/disable
 */
export const disableForwardRule = async (id: number | string): Promise<void> => {
  await apiClient.post(`/forward-rules/${id}/disable`);
};

/**
 * Reset forward rule traffic counters (Admin only)
 * POST /forward-rules/:id/reset-traffic
 */
export const resetForwardRuleTraffic = async (id: number | string): Promise<void> => {
  await apiClient.post(`/forward-rules/${id}/reset-traffic`);
};

// ========== Forward Agent APIs ==========

/**
 * Create forward agent (Admin only)
 * POST /forward-agents
 * @returns Agent with token (token is only returned on creation)
 */
export const createForwardAgent = async (
  data: CreateForwardAgentRequest
): Promise<ForwardAgentWithToken> => {
  const response = await apiClient.post<APIResponse<ForwardAgentWithToken>>(
    '/forward-agents',
    data
  );
  return response.data.data;
};

/**
 * Get forward agent by ID (Admin only)
 * GET /forward-agents/:id
 */
export const getForwardAgent = async (id: number | string): Promise<ForwardAgent> => {
  const response = await apiClient.get<APIResponse<ForwardAgent>>(`/forward-agents/${id}`);
  return response.data.data;
};

/**
 * Update forward agent (Admin only)
 * PUT /forward-agents/:id
 */
export const updateForwardAgent = async (
  id: number | string,
  data: UpdateForwardAgentRequest
): Promise<void> => {
  await apiClient.put(`/forward-agents/${id}`, data);
};

/**
 * Delete forward agent (Admin only)
 * DELETE /forward-agents/:id
 */
export const deleteForwardAgent = async (id: number | string): Promise<void> => {
  await apiClient.delete(`/forward-agents/${id}`);
};

/**
 * List forward agents (Admin only)
 * GET /forward-agents
 */
export const listForwardAgents = async (
  params?: ListForwardAgentsParams
): Promise<ListResponse<ForwardAgent>> => {
  const response = await apiClient.get<APIResponse<ListResponse<ForwardAgent>>>(
    '/forward-agents',
    { params }
  );
  return response.data.data;
};

/**
 * Update forward agent status (Admin only)
 * PATCH /forward-agents/:id/status
 */
export const updateForwardAgentStatus = async (
  id: number | string,
  data: UpdateForwardAgentStatusRequest
): Promise<void> => {
  await apiClient.patch(`/forward-agents/${id}/status`, data);
};

/**
 * Enable forward agent (Admin only)
 * POST /forward-agents/:id/enable
 */
export const enableForwardAgent = async (id: number | string): Promise<void> => {
  await apiClient.post(`/forward-agents/${id}/enable`);
};

/**
 * Disable forward agent (Admin only)
 * POST /forward-agents/:id/disable
 */
export const disableForwardAgent = async (id: number | string): Promise<void> => {
  await apiClient.post(`/forward-agents/${id}/disable`);
};

/**
 * Get forward agent token (Admin only)
 * GET /forward-agents/:id/token
 * @returns Current token for the agent (without regenerating)
 */
export const getForwardAgentToken = async (
  id: number | string
): Promise<GetAgentTokenResponse> => {
  const response = await apiClient.get<APIResponse<GetAgentTokenResponse>>(
    `/forward-agents/${id}/token`
  );
  return response.data.data;
};

/**
 * Regenerate forward agent token (Admin only)
 * POST /forward-agents/:id/regenerate-token
 * @returns New token for the agent (generates a new token, invalidating the old one)
 */
export const regenerateForwardAgentToken = async (
  id: number | string
): Promise<RegenerateTokenResponse> => {
  const response = await apiClient.post<APIResponse<RegenerateTokenResponse>>(
    `/forward-agents/${id}/regenerate-token`
  );
  return response.data.data;
};

/**
 * Get forward agent runtime status (Admin only)
 * GET /forward-agents/:id/runtime-status
 * @returns Agent runtime status including CPU, memory, disk, connections, etc.
 */
export const getForwardAgentRuntimeStatus = async (
  id: number | string
): Promise<AgentRuntimeStatus> => {
  const response = await apiClient.get<APIResponse<AgentRuntimeStatus>>(
    `/forward-agents/${id}/runtime-status`
  );
  return response.data.data;
};

// ========== Forward Agent API (Client APIs) ==========

/**
 * Get exit endpoint information for WS tunnel connection
 * GET /forward-agent-api/exit-endpoint/:agent_id
 * Note: Requires forward agent token authentication
 */
export const getExitEndpoint = async (agentId: number | string): Promise<ExitEndpoint> => {
  const response = await apiClient.get<APIResponse<ExitEndpoint>>(
    `/forward-agent-api/exit-endpoint/${agentId}`
  );
  return response.data.data;
};

// ========== Probe APIs ==========

/**
 * Probe a forward rule (Admin only)
 * POST /forward-rules/:id/probe
 * @param id Rule ID
 * @param data Optional probe request with IP version override
 * @returns Probe result with latency information
 *
 * For direct rules: returns targetLatencyMs
 * For entry rules: returns tunnelLatencyMs (entry→exit) + targetLatencyMs (exit→target)
 */
export const probeRule = async (
  id: number | string,
  data?: ProbeRuleRequest
): Promise<RuleProbeResponse> => {
  const response = await apiClient.post<APIResponse<RuleProbeResponse>>(
    `/forward-rules/${id}/probe`,
    data
  );
  return response.data.data;
};

// ========== Install Script APIs ==========

/**
 * Get install command for forward agent (Admin only)
 * GET /forward-agents/:id/install-script
 *
 * @param id Agent ID
 * @param params.token Optional: API token. If not provided, uses agent's stored token
 * @param params.serverUrl Optional: Override default server URL
 * @returns Install command that can be executed on target server
 *
 * Usage:
 * 1. Call getInstallCommand() to get the install command
 * 2. Copy and execute the installCommand on target server
 *
 * Example response:
 * {
 *   installCommand: "curl -fsSL https://...install.sh | sudo bash -s -- --server https://... --token fwd_xxx",
 *   uninstallCommand: "curl -fsSL https://...install.sh | sudo bash -s -- uninstall",
 *   scriptUrl: "https://raw.githubusercontent.com/orris-inc/orris-client/main/scripts/install.sh",
 *   serverUrl: "https://api.example.com",
 *   token: "fwd_xxx"
 * }
 */
export const getInstallCommand = async (
  id: number | string,
  params?: GetInstallScriptParams
): Promise<InstallCommandResponse> => {
  const response = await apiClient.get<APIResponse<InstallCommandResponse>>(
    `/forward-agents/${id}/install-script`,
    { params }
  );
  return response.data.data;
};
