/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2025-12-26
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 *
 * ID Format: Stripe-style prefixed IDs
 * - Forward Agent: "fa_xK9mP2vL3nQ" (prefix: fa_)
 * - Forward Rule: "fr_xK9mP2vL3nQ" (prefix: fr_)
 */

// ========== Forward Rule Types ==========

/**
 * Forward rule type
 * Note: 'exit' type has been removed. Entry rules now contain target information.
 * 'chain' type is for multi-hop forwarding through multiple agents using WS tunnels.
 * 'direct_chain' type is for multi-hop forwarding using direct TCP/UDP connections.
 */
export type ForwardRuleType = 'direct' | 'entry' | 'chain' | 'direct_chain';

/**
 * Forward protocol type
 */
export type ForwardProtocol = 'tcp' | 'udp' | 'both';

/**
 * Forward status type
 */
export type ForwardStatus = 'enabled' | 'disabled';

/**
 * IP version preference for target address resolution
 */
export type IPVersion = 'auto' | 'ipv4' | 'ipv6';

/**
 * Tunnel type for forwarding traffic
 * Added: 2025-12-24
 */
export type TunnelType = 'ws' | 'tls';

/**
 * Forward rule entity
 * ID format: "fr_xK9mP2vL3nQ" (Stripe-style prefixed ID)
 * Note: ws_listen_port field has been removed (exit type deprecated).
 */
export interface ForwardRule {
  id: string; // Stripe-style prefixed ID (e.g., "fr_xK9mP2vL3nQ")
  agentId: string; // Stripe-style prefixed ID (e.g., "fa_xK9mP2vL3nQ")
  userId?: number; // user ID for user-owned rules (undefined for admin-created rules)
  ruleType: ForwardRuleType;
  exitAgentId?: string; // for entry type (Stripe-style prefixed ID)
  chainAgentIds?: string[]; // for chain and direct_chain types (ordered list of Stripe-style agent IDs)
  chainPortConfig?: Record<string, number>; // for direct_chain type (agent ID -> listen port)
  name: string;
  listenPort: number;
  targetAddress?: string; // for direct, entry, chain, and direct_chain exit types
  targetPort?: number; // for direct, entry, chain, and direct_chain exit types
  targetNodeId?: string; // Stripe-style Node ID (e.g., "node_xK9mP2vL3nQ") for dynamic address resolution
  bindIp?: string; // Bind IP address for outbound connections
  ipVersion: IPVersion; // IP version preference for target address resolution
  protocol: ForwardProtocol;
  status: ForwardStatus;
  remark: string;
  uploadBytes: number; // traffic with multiplier already applied
  downloadBytes: number; // traffic with multiplier already applied
  totalBytes: number; // traffic with multiplier already applied
  createdAt: string;
  updatedAt: string;
  // Traffic multiplier fields
  trafficMultiplier?: number; // custom traffic multiplier (null means auto-calculated)
  effectiveTrafficMultiplier: number; // effective multiplier being used (either custom or auto)
  nodeCount: number; // number of nodes involved in the rule
  isAutoMultiplier: boolean; // true if using auto-calculated multiplier
  // Sort order for custom ordering
  sortOrder: number; // custom sort order (lower values appear first)
  // Target node info (populated when targetNodeId is set)
  targetNodeServerAddress?: string; // node's configured server address
  targetNodePublicIpv4?: string; // node's reported public IPv4
  targetNodePublicIpv6?: string; // node's reported public IPv6
  // Role indicates the requesting agent's role in this rule
  // Values: "entry" (needs to establish tunnel), "exit" (accepts tunnel connections), "relay" (chain middle node)
  role?: string;
  // Tunnel configuration (Added: 2025-12-24)
  tunnelType?: TunnelType; // tunnel type: "ws" or "tls" (default: "ws")
  tunnelHops?: number; // number of hops using tunnel (undefined=full tunnel, N=first N hops use tunnel) (Added: 2025-12-25)
  // Hop mode for hybrid chain (Added: 2025-12-25)
  hopMode?: string; // hop mode: "tunnel", "direct", or "boundary"
  inboundMode?: string; // for boundary nodes: inbound mode ("tunnel" or "direct")
  outboundMode?: string; // for boundary nodes: outbound mode ("tunnel" or "direct")
  // Runtime sync status (populated from agent status cache) (Added: 2025-12-26)
  syncStatus?: RuleSyncStatus; // aggregated sync status: synced, pending, failed
  runStatus?: RuleRunStatus | 'unknown'; // aggregated run status: running, stopped, error, starting, unknown
  totalAgents?: number; // total agents in forwarding chain
  healthyAgents?: number; // number of healthy agents (synced + running)
  statusUpdatedAt?: number; // last status update timestamp (Unix seconds)
  // Chain-specific fields (populated for chain rules based on requesting agent's role)
  chainPosition?: number; // agent's position in chain (0-indexed)
  isLastInChain?: boolean; // true if agent is last in chain
  nextHopAgentId?: string; // next agent in chain (Stripe-style ID)
  nextHopAddress?: string; // next agent's public address
  nextHopWsPort?: number; // next agent's WS port (for chain type)
  nextHopTlsPort?: number; // next agent's TLS port (Added: 2025-12-24)
  nextHopPort?: number; // next agent's listen port (for direct_chain type)
  nextHopConnectionToken?: string; // short-term JWT for next hop authentication
}

/**
 * Create forward rule request
 * Note: All IDs should use Stripe-style prefixed format:
 * - agentId: "fa_xK9mP2vL3nQ"
 * - exitAgentId: "fa_yL8nQ3wM4oR"
 * - chainAgentIds: ["fa_aaa", "fa_bbb", "fa_ccc"]
 * - targetNodeId: "node_xK9mP2vL3nQ"
 *
 * Required fields by rule type:
 * - direct: agentId, listenPort, (targetAddress+targetPort OR targetNodeId)
 * - entry: agentId, exitAgentId, listenPort, (targetAddress+targetPort OR targetNodeId)
 * - chain: agentId, chainAgentIds (at least 1), listenPort, (targetAddress+targetPort OR targetNodeId)
 * - direct_chain: agentId, listenPort, chainAgentIds (at least 1), chainPortConfig, (targetAddress+targetPort OR targetNodeId)
 *
 * Note: Exit rule type has been removed. Entry rules now include target information
 * that is passed to the exit agent.
 */
export interface CreateForwardRuleRequest {
  agentId: string; // Stripe-style prefixed ID (e.g., "fa_xK9mP2vL3nQ")
  ruleType: ForwardRuleType;
  exitAgentId?: string; // required for entry type (Stripe-style prefixed ID)
  chainAgentIds?: string[]; // required for chain and direct_chain types (ordered list of intermediate agents)
  chainPortConfig?: Record<string, number>; // required for direct_chain type (agent ID -> listen port)
  tunnelType?: TunnelType; // tunnel type: ws or tls (default: ws) (Added: 2025-12-24)
  tunnelHops?: number; // number of hops using tunnel (undefined=full tunnel, N=first N hops use tunnel) (Added: 2025-12-25)
  name: string;
  listenPort?: number; // required for direct, entry, chain, and direct_chain types
  targetAddress?: string; // for direct, entry, chain, and direct_chain types (mutually exclusive with targetNodeId)
  targetPort?: number; // for direct, entry, chain, and direct_chain types (mutually exclusive with targetNodeId)
  targetNodeId?: string; // Stripe-style Node ID (e.g., "node_xK9mP2vL3nQ") for dynamic address resolution
  bindIp?: string; // Bind IP address for outbound connections
  ipVersion?: IPVersion; // IP version preference (default: auto)
  protocol: ForwardProtocol;
  trafficMultiplier?: number; // custom traffic multiplier (0 to 1000000, omit for auto-calculated)
  sortOrder?: number; // custom sort order (non-negative, lower values appear first, default: 0)
  remark?: string;
}

/**
 * Update forward rule request
 * Note: All agent IDs should use Stripe-style prefixed format (e.g., "fa_xK9mP2vL3nQ")
 */
export interface UpdateForwardRuleRequest {
  name?: string;
  agentId?: string; // Stripe-style prefixed ID (e.g., "fa_xK9mP2vL3nQ") - update entry agent
  exitAgentId?: string; // Stripe-style prefixed ID - update exit agent (for entry type rules only)
  chainAgentIds?: string[]; // Stripe-style prefixed IDs - update chain agents (for chain and direct_chain type rules)
  chainPortConfig?: Record<string, number>; // update chain port config (for direct_chain type rules)
  tunnelType?: TunnelType; // tunnel type: ws or tls (Added: 2025-12-24)
  listenPort?: number;
  targetAddress?: string; // mutually exclusive with targetNodeId
  targetPort?: number; // mutually exclusive with targetNodeId
  targetNodeId?: string; // Stripe-style Node ID (e.g., "node_xK9mP2vL3nQ"), empty string clears, undefined means no change
  bindIp?: string; // Bind IP address for outbound connections
  ipVersion?: IPVersion; // IP version preference
  protocol?: ForwardProtocol;
  trafficMultiplier?: number; // custom traffic multiplier (0 to 1000000, omit for no change)
  sortOrder?: number; // custom sort order for rule ordering
  remark?: string;
}

/**
 * Update forward rule status request
 */
export interface UpdateForwardRuleStatusRequest {
  status: ForwardStatus;
}

/**
 * List forward rules params
 */
export interface ListForwardRulesParams {
  page?: number;
  pageSize?: number;
  name?: string;
  protocol?: ForwardProtocol;
  status?: ForwardStatus;
  orderBy?: string;
  order?: 'asc' | 'desc';
}

// ========== Forward Rule Reorder Types ==========
// Added: 2025-12-23

/**
 * Forward rule order item for batch reordering
 * @example
 * ```typescript
 * const order: ForwardRuleOrder = {
 *   ruleId: 'fr_xK9mP2vL3nQ',
 *   sortOrder: 100
 * };
 * ```
 */
export interface ForwardRuleOrder {
  /** Stripe-style prefixed rule ID (e.g., "fr_xK9mP2vL3nQ") */
  ruleId: string;
  /** New sort order value (non-negative integer, lower values appear first) */
  sortOrder: number;
}

/**
 * Reorder forward rules request
 * Allows batch updating of sort orders for multiple rules
 *
 * @example
 * ```typescript
 * await reorderForwardRules({
 *   ruleOrders: [
 *     { ruleId: 'fr_aaa', sortOrder: 100 },
 *     { ruleId: 'fr_bbb', sortOrder: 200 },
 *     { ruleId: 'fr_ccc', sortOrder: 300 }
 *   ]
 * });
 * ```
 */
export interface ReorderForwardRulesRequest {
  /** Array of rule orders to update (at least 1 required) */
  ruleOrders: ForwardRuleOrder[];
}

// ========== Forward Agent Types ==========

/**
 * Forward agent entity
 * ID format: "fa_xK9mP2vL3nQ" (Stripe-style prefixed ID)
 * An agent can participate in multiple rules with different roles (entry/relay/exit) simultaneously.
 * Updated: 2025-12-19 - Added groupId field for resource group association
 */
export interface ForwardAgent {
  id: string; // Stripe-style prefixed ID (e.g., "fa_xK9mP2vL3nQ")
  name: string;
  publicAddress: string;
  tunnelAddress?: string; // IP or hostname only (no port), configure if agent may serve as relay/exit in any rule
  status: ForwardStatus;
  remark: string;
  /** Resource group SID this agent belongs to (e.g., "rg_xK9mP2vL3nQ") */
  groupId?: string;
  createdAt: string;
  updatedAt: string;
  systemStatus?: AgentSystemStatus; // Real-time system metrics (optional, from cache)
}

/**
 * Agent system status (embedded in ForwardAgent response)
 * Contains real-time metrics reported by the agent
 */
export interface AgentSystemStatus {
  // System resources
  cpuPercent: number;
  memoryPercent: number;
  memoryUsed: number;
  memoryTotal: number;
  diskPercent: number;
  diskUsed: number;
  diskTotal: number;
  uptimeSeconds: number;

  // Network connections
  tcpConnections: number;
  udpConnections: number;

  // Forward status
  activeRules: number;
  activeConnections: number;
  tunnelStatus?: Record<string, string>; // Key is Stripe-style rule ID (e.g., "fr_xK9mP2vL3nQ")

  // Tunnel configuration (for exit agent)
  wsListenPort?: number; // WebSocket listen port for tunnel connections
  tlsListenPort?: number; // TLS listen port for tunnel connections (Added: 2025-12-24)
}

/**
 * Forward agent with token (returned on creation)
 */
export interface ForwardAgentWithToken extends ForwardAgent {
  token: string;
}

/**
 * Create forward agent request
 * An agent can participate in multiple rules with different roles (entry/relay/exit) simultaneously.
 */
export interface CreateForwardAgentRequest {
  name: string;
  publicAddress?: string;
  tunnelAddress?: string; // IP or hostname only (no port), configure if agent may serve as relay/exit in any rule
  remark?: string;
}

/**
 * Update forward agent request
 * Updated: 2025-12-19 - Added groupSid field for resource group association
 */
export interface UpdateForwardAgentRequest {
  name?: string;
  publicAddress?: string;
  tunnelAddress?: string; // IP or hostname only (no port), configure if agent may serve as relay/exit in any rule
  remark?: string;
  /** Resource group SID to associate with (use empty string to remove association) */
  groupSid?: string;
}

/**
 * Update forward agent status request
 */
export interface UpdateForwardAgentStatusRequest {
  status: ForwardStatus;
}

/**
 * List forward agents params
 */
export interface ListForwardAgentsParams {
  page?: number;
  pageSize?: number;
  name?: string;
  status?: ForwardStatus;
  orderBy?: string;
  order?: 'asc' | 'desc';
}

/**
 * Regenerate token response
 */
export interface RegenerateTokenResponse {
  id: string; // Stripe-style prefixed ID (e.g., "fa_xK9mP2vL3nQ")
  token: string;
}

/**
 * Get agent token response
 */
export interface GetAgentTokenResponse {
  id: string; // Stripe-style prefixed ID (e.g., "fa_xK9mP2vL3nQ")
  token: string;
  hasToken: boolean;
}

// ========== Agent Runtime Status Types ==========

/**
 * Agent runtime status (reported by forward agent)
 */
export interface AgentRuntimeStatus {
  // System resources
  cpuPercent: number;
  memoryPercent: number;
  memoryUsed: number;
  memoryTotal: number;
  diskPercent: number;
  diskUsed: number;
  diskTotal: number;
  uptimeSeconds: number;

  // Network connections
  tcpConnections: number;
  udpConnections: number;

  // Forward status
  activeRules: number;
  activeConnections: number;
  tunnelStatus?: Record<string, string>; // Key is Stripe-style rule ID (e.g., "fr_xK9mP2vL3nQ")

  // Tunnel configuration (for exit agent)
  wsListenPort?: number; // WebSocket listen port for tunnel connections
  tlsListenPort?: number; // TLS listen port for tunnel connections (Added: 2025-12-24)
}

// ========== Exit Endpoint Types ==========

/**
 * Exit endpoint information for WS tunnel connection
 */
export interface ExitEndpoint {
  address: string;
  wsPort: number;
}

// ========== Probe Types ==========

/**
 * Probe rule request - optional parameters for probing
 */
export interface ProbeRuleRequest {
  ipVersion?: IPVersion; // optional: override rule's IP version for this probe
}

/**
 * Chain hop latency - represents latency of a single hop in the chain
 * Used for chain and direct_chain rule types
 */
export interface ChainHopLatency {
  from: string; // Stripe-style prefixed agent ID (e.g., "fa_xK9mP2vL3nQ")
  to: string; // Stripe-style prefixed agent ID or "target"
  latencyMs: number; // latency in milliseconds
  success: boolean; // whether this hop probe succeeded
  error?: string; // error message if failed
  online: boolean; // whether the source agent is online
}

/**
 * Rule probe response - represents probe result for a single forward rule
 * For direct rules: only targetLatencyMs is set
 * For entry rules: both tunnelLatencyMs and targetLatencyMs are set
 * For chain/direct_chain rules: chainLatencies contains per-hop latencies
 */
export interface RuleProbeResponse {
  ruleId: string; // Stripe-style prefixed ID (e.g., "fr_xK9mP2vL3nQ")
  ruleType: 'direct' | 'entry' | 'chain' | 'direct_chain';
  success: boolean;
  tunnelLatencyMs?: number; // entry only: entry→exit latency
  targetLatencyMs?: number; // agent→target latency
  chainLatencies?: ChainHopLatency[]; // chain/direct_chain: per-hop latencies
  totalLatencyMs?: number; // total round-trip latency
  error?: string;
}

// ========== Install Script Types ==========

/**
 * Install command response
 */
export interface InstallCommandResponse {
  installCommand: string;
  uninstallCommand: string;
  scriptUrl: string;
  serverUrl: string;
  token: string;
}

/**
 * Install script params
 */
export interface GetInstallScriptParams {
  token?: string; // Optional: If not provided, uses agent's stored token
  serverUrl?: string; // Optional: Override default server URL
}

// ========== User Forward Usage Types ==========

/**
 * User forward rule usage and quota information
 * Contains current usage statistics and limits from user's subscription plan
 *
 * @example
 * ```typescript
 * const usage = await getUserForwardUsage();
 *
 * // Check if unlimited
 * if (isUnlimitedRules(usage)) {
 *   console.log('Unlimited rules');
 * }
 *
 * // Format for display
 * const display = formatUsageDisplay(usage);
 * console.log(display.rules); // "3/10" or "3/∞"
 * ```
 */
export interface UserForwardUsage {
  /** Current number of forward rules user has created */
  ruleCount: number;
  /** Maximum number of rules allowed (0 means unlimited) */
  ruleLimit: number;
  /** Total forward traffic used in bytes */
  trafficUsed: number;
  /** Total forward traffic limit in bytes (0 means unlimited) */
  trafficLimit: number;
  /** Allowed forward rule types (e.g., ["direct", "entry"]) */
  allowedTypes: string[];
}

/**
 * Check if user has unlimited forward rules
 */
export const isUnlimitedRules = (usage: UserForwardUsage): boolean => {
  return usage.ruleLimit === 0;
};

/**
 * Check if user has unlimited forward traffic
 */
export const isUnlimitedTraffic = (usage: UserForwardUsage): boolean => {
  return usage.trafficLimit === 0;
};

/**
 * Check if user can create more forward rules
 */
export const canCreateMoreRules = (usage: UserForwardUsage): boolean => {
  if (isUnlimitedRules(usage)) return true;
  return usage.ruleCount < usage.ruleLimit;
};

/**
 * Get remaining rule quota
 * @returns remaining count, or -1 if unlimited
 */
export const getRemainingRules = (usage: UserForwardUsage): number => {
  if (isUnlimitedRules(usage)) return -1;
  return Math.max(0, usage.ruleLimit - usage.ruleCount);
};

/**
 * Format bytes to human readable string
 */
export const formatBytes = (bytes: number): string => {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(2))} ${sizes[i]}`;
};

/**
 * Format usage for display
 * @returns formatted strings for rules and traffic usage
 *
 * @example
 * ```typescript
 * const display = formatUsageDisplay(usage);
 * // display.rules = "3/10" or "3/∞"
 * // display.traffic = "1.5 GB/10 GB" or "1.5 GB/∞"
 * ```
 */
export const formatUsageDisplay = (usage: UserForwardUsage): {
  rules: string;
  traffic: string;
  rulesPercent: number | null;
  trafficPercent: number | null;
} => {
  const unlimitedSymbol = '∞';

  const rulesLimit = isUnlimitedRules(usage) ? unlimitedSymbol : usage.ruleLimit.toString();
  const trafficLimit = isUnlimitedTraffic(usage) ? unlimitedSymbol : formatBytes(usage.trafficLimit);

  return {
    rules: `${usage.ruleCount}/${rulesLimit}`,
    traffic: `${formatBytes(usage.trafficUsed)}/${trafficLimit}`,
    rulesPercent: isUnlimitedRules(usage) ? null : Math.round((usage.ruleCount / usage.ruleLimit) * 100),
    trafficPercent: isUnlimitedTraffic(usage) ? null : Math.round((usage.trafficUsed / usage.trafficLimit) * 100),
  };
};

// ========== User Forward Agent Types ==========
// Added: 2025-12-19

/**
 * User-facing forward agent entity
 * This is a simplified view that hides sensitive fields (token, etc.)
 * Users can only see agents accessible through their subscriptions
 *
 * ID format: "fa_xK9mP2vL3nQ" (Stripe-style prefixed ID)
 */
export interface UserForwardAgent {
  /** Stripe-style prefixed ID (e.g., "fa_xK9mP2vL3nQ") */
  id: string;
  /** Agent name */
  name: string;
  /** Public address for client connections */
  publicAddress?: string;
  /** Agent status: enabled or disabled */
  status: ForwardStatus;
  /** Resource group SID this agent belongs to (e.g., "rg_xK9mP2vL3nQ") */
  groupId?: string;
  /** Resource group name for display */
  groupName?: string;
  /** Creation timestamp */
  createdAt: string;
}

/**
 * List user forward agents params
 */
export interface ListUserForwardAgentsParams {
  page?: number;
  pageSize?: number;
  name?: string;
  status?: ForwardStatus;
}

// ========== Rule Sync Status Types ==========
// Added: 2025-12-25

/**
 * Rule sync status - synchronization state reported by agent
 */
export type RuleSyncStatus = 'synced' | 'pending' | 'failed';

/**
 * Rule run status - runtime state reported by agent
 */
export type RuleRunStatus = 'running' | 'stopped' | 'error' | 'starting';

/**
 * Rule sync status item - represents sync and runtime status of a single forward rule
 * Reported by forward agent via POST /forward-agent-api/rule-sync-status
 */
export interface RuleSyncStatusItem {
  /** Stripe-style rule ID (e.g., "fr_xK9mP2vL3nQ") */
  ruleId: string;
  /** Sync status: synced, pending, failed */
  syncStatus: RuleSyncStatus;
  /** Runtime status: running, stopped, error, starting */
  runStatus: RuleRunStatus;
  /** Actual listening port */
  listenPort: number;
  /** Current number of connections */
  connections: number;
  /** Error message if any */
  errorMessage: string;
  /** Last sync timestamp (Unix seconds) */
  syncedAt: number;
}

/**
 * Agent rule sync status - represents the sync status of a single agent for a specific rule
 * Used in rule overall status response to show per-agent status
 * Added: 2025-12-25
 */
export interface AgentRuleSyncStatus {
  /** Stripe-style agent ID (e.g., "fa_xK9mP2vL3nQ") */
  agentId: string;
  /** Agent name */
  agentName: string;
  /** Position in forwarding chain (0=entry) */
  position: number;
  /** Sync status: synced, pending, failed */
  syncStatus: RuleSyncStatus;
  /** Runtime status: running, stopped, error, starting, unknown */
  runStatus: RuleRunStatus | 'unknown';
  /** Actual listening port */
  listenPort: number;
  /** Current number of connections */
  connections: number;
  /** Error message if any */
  errorMessage: string;
  /** Last sync timestamp (Unix seconds) */
  syncedAt: number;
}

/**
 * Rule overall status response - aggregated status for a forward rule across all agents
 * GET /forward-rules/:id/status
 *
 * For multi-hop rules (entry, chain, direct_chain), this aggregates status from all agents:
 * - Overall sync status: failed > pending > synced (worst takes priority)
 * - Overall run status: error > stopped > starting > unknown > running (worst takes priority)
 *
 * Added: 2025-12-25
 */
export interface RuleOverallStatusResponse {
  /** Stripe-style rule ID (e.g., "fr_xK9mP2vL3nQ") */
  ruleId: string;
  /** Aggregated sync status: synced, pending, failed */
  overallSyncStatus: RuleSyncStatus;
  /** Aggregated run status: running, stopped, error, starting, unknown */
  overallRunStatus: RuleRunStatus | 'unknown';
  /** Total number of agents involved in this rule */
  totalAgents: number;
  /** Number of healthy agents (synced + running) */
  healthyAgents: number;
  /** Detailed status for each agent in the chain */
  agentStatuses: AgentRuleSyncStatus[];
  /** Last update timestamp (Unix seconds) */
  updatedAt: number;
}
