/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2025-12-04
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 */

// ========== Forward Rule Types ==========

/**
 * Forward rule type
 */
export type ForwardRuleType = 'direct' | 'entry' | 'exit';

/**
 * Forward protocol type
 */
export type ForwardProtocol = 'tcp' | 'udp' | 'both';

/**
 * Forward status type
 */
export type ForwardStatus = 'enabled' | 'disabled';

/**
 * Forward rule entity
 */
export interface ForwardRule {
  id: number;
  agentId: number;
  ruleType: ForwardRuleType;
  exitAgentId?: number; // for entry type
  wsListenPort?: number; // for exit type
  name: string;
  listenPort: number;
  targetAddress?: string; // for direct and exit types
  targetPort?: number; // for direct and exit types
  targetNodeId?: number; // for dynamic node address resolution (mutually exclusive with targetAddress/targetPort)
  protocol: ForwardProtocol;
  status: ForwardStatus;
  remark: string;
  uploadBytes: number;
  downloadBytes: number;
  totalBytes: number;
  createdAt: string;
  updatedAt: string;
}

/**
 * Create forward rule request
 */
export interface CreateForwardRuleRequest {
  agentId: number;
  ruleType: ForwardRuleType;
  exitAgentId?: number; // required for entry type
  wsListenPort?: number; // required for exit type
  name: string;
  listenPort?: number; // required for direct and entry types
  targetAddress?: string; // for direct and exit types (mutually exclusive with targetNodeId)
  targetPort?: number; // for direct and exit types (mutually exclusive with targetNodeId)
  targetNodeId?: number; // for dynamic node address resolution (mutually exclusive with targetAddress/targetPort)
  protocol: ForwardProtocol;
  remark?: string;
}

/**
 * Update forward rule request
 */
export interface UpdateForwardRuleRequest {
  name?: string;
  listenPort?: number;
  targetAddress?: string; // mutually exclusive with targetNodeId
  targetPort?: number; // mutually exclusive with targetNodeId
  targetNodeId?: number; // for dynamic node address resolution (mutually exclusive with targetAddress/targetPort)
  protocol?: ForwardProtocol;
  remark?: string;
}

/**
 * Update forward rule status request
 */
export interface UpdateForwardRuleStatusRequest {
  status: ForwardStatus;
}

/**
 * List forward rules params
 */
export interface ListForwardRulesParams {
  page?: number;
  pageSize?: number;
  name?: string;
  protocol?: ForwardProtocol;
  status?: ForwardStatus;
  orderBy?: string;
  order?: 'asc' | 'desc';
}

// ========== Forward Agent Types ==========

/**
 * Forward agent entity
 */
export interface ForwardAgent {
  id: number;
  name: string;
  publicAddress: string;
  status: ForwardStatus;
  remark: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * Forward agent with token (returned on creation)
 */
export interface ForwardAgentWithToken extends ForwardAgent {
  token: string;
}

/**
 * Create forward agent request
 */
export interface CreateForwardAgentRequest {
  name: string;
  publicAddress?: string;
  remark?: string;
}

/**
 * Update forward agent request
 */
export interface UpdateForwardAgentRequest {
  name?: string;
  publicAddress?: string;
  remark?: string;
}

/**
 * Update forward agent status request
 */
export interface UpdateForwardAgentStatusRequest {
  status: ForwardStatus;
}

/**
 * List forward agents params
 */
export interface ListForwardAgentsParams {
  page?: number;
  pageSize?: number;
  name?: string;
  status?: ForwardStatus;
  orderBy?: string;
  order?: 'asc' | 'desc';
}

/**
 * Regenerate token response
 */
export interface RegenerateTokenResponse {
  id: number;
  token: string;
}

// ========== Exit Endpoint Types ==========

/**
 * Exit endpoint information for WS tunnel connection
 */
export interface ExitEndpoint {
  address: string;
  wsPort: number;
}
