/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2025-12-08
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 */

// ========== Forward Rule Types ==========

/**
 * Forward rule type
 */
export type ForwardRuleType = 'direct' | 'entry' | 'exit';

/**
 * Forward protocol type
 */
export type ForwardProtocol = 'tcp' | 'udp' | 'both';

/**
 * Forward status type
 */
export type ForwardStatus = 'enabled' | 'disabled';

/**
 * IP version preference for target address resolution
 */
export type IPVersion = 'auto' | 'ipv4' | 'ipv6';

/**
 * Forward rule entity
 */
export interface ForwardRule {
  id: number;
  agentId: number;
  ruleType: ForwardRuleType;
  exitAgentId?: number; // for entry type
  wsListenPort?: number; // for exit type
  name: string;
  listenPort: number;
  targetAddress?: string; // for direct and exit types
  targetPort?: number; // for direct and exit types
  targetNodeId?: number; // for dynamic node address resolution (mutually exclusive with targetAddress/targetPort)
  ipVersion: IPVersion; // IP version preference for target address resolution
  protocol: ForwardProtocol;
  status: ForwardStatus;
  remark: string;
  uploadBytes: number;
  downloadBytes: number;
  totalBytes: number;
  createdAt: string;
  updatedAt: string;
  // Target node info (populated when targetNodeId is set)
  targetNodeServerAddress?: string; // node's configured server address
  targetNodePublicIpv4?: string; // node's reported public IPv4
  targetNodePublicIpv6?: string; // node's reported public IPv6
}

/**
 * Create forward rule request
 */
export interface CreateForwardRuleRequest {
  agentId: number;
  ruleType: ForwardRuleType;
  exitAgentId?: number; // required for entry type
  wsListenPort?: number; // required for exit type
  name: string;
  listenPort?: number; // required for direct and entry types
  targetAddress?: string; // for direct and exit types (mutually exclusive with targetNodeId)
  targetPort?: number; // for direct and exit types (mutually exclusive with targetNodeId)
  targetNodeId?: number; // for dynamic node address resolution (mutually exclusive with targetAddress/targetPort)
  ipVersion?: IPVersion; // IP version preference (default: auto)
  protocol: ForwardProtocol;
  remark?: string;
}

/**
 * Update forward rule request
 */
export interface UpdateForwardRuleRequest {
  name?: string;
  listenPort?: number;
  targetAddress?: string; // mutually exclusive with targetNodeId
  targetPort?: number; // mutually exclusive with targetNodeId
  targetNodeId?: number; // for dynamic node address resolution (mutually exclusive with targetAddress/targetPort)
  ipVersion?: IPVersion; // IP version preference
  protocol?: ForwardProtocol;
  remark?: string;
}

/**
 * Update forward rule status request
 */
export interface UpdateForwardRuleStatusRequest {
  status: ForwardStatus;
}

/**
 * List forward rules params
 */
export interface ListForwardRulesParams {
  page?: number;
  pageSize?: number;
  name?: string;
  protocol?: ForwardProtocol;
  status?: ForwardStatus;
  orderBy?: string;
  order?: 'asc' | 'desc';
}

// ========== Forward Agent Types ==========

/**
 * Forward agent entity
 */
export interface ForwardAgent {
  id: number;
  name: string;
  publicAddress: string;
  status: ForwardStatus;
  remark: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * Forward agent with token (returned on creation)
 */
export interface ForwardAgentWithToken extends ForwardAgent {
  token: string;
}

/**
 * Create forward agent request
 */
export interface CreateForwardAgentRequest {
  name: string;
  publicAddress?: string;
  remark?: string;
}

/**
 * Update forward agent request
 */
export interface UpdateForwardAgentRequest {
  name?: string;
  publicAddress?: string;
  remark?: string;
}

/**
 * Update forward agent status request
 */
export interface UpdateForwardAgentStatusRequest {
  status: ForwardStatus;
}

/**
 * List forward agents params
 */
export interface ListForwardAgentsParams {
  page?: number;
  pageSize?: number;
  name?: string;
  status?: ForwardStatus;
  orderBy?: string;
  order?: 'asc' | 'desc';
}

/**
 * Regenerate token response
 */
export interface RegenerateTokenResponse {
  id: number;
  token: string;
}

/**
 * Get agent token response
 */
export interface GetAgentTokenResponse {
  id: number;
  token: string;
  hasToken: boolean;
}

// ========== Agent Runtime Status Types ==========

/**
 * Agent runtime status (reported by forward agent)
 */
export interface AgentRuntimeStatus {
  // System resources
  cpuPercent: number;
  memoryPercent: number;
  memoryUsed: number;
  memoryTotal: number;
  diskPercent: number;
  diskUsed: number;
  diskTotal: number;
  uptimeSeconds: number;

  // Network connections
  tcpConnections: number;
  udpConnections: number;

  // Forward status
  activeRules: number;
  activeConnections: number;
  tunnelStatus?: Record<number, string>;
}

// ========== Exit Endpoint Types ==========

/**
 * Exit endpoint information for WS tunnel connection
 */
export interface ExitEndpoint {
  address: string;
  wsPort: number;
}

// ========== Probe Types ==========

/**
 * Probe rule request - optional parameters for probing
 */
export interface ProbeRuleRequest {
  ipVersion?: IPVersion; // optional: override rule's IP version for this probe
}

/**
 * Rule probe response - represents probe result for a single forward rule
 * For direct rules: only targetLatencyMs is set
 * For entry rules: both tunnelLatencyMs and targetLatencyMs are set
 */
export interface RuleProbeResponse {
  ruleId: number;
  ruleType: 'direct' | 'entry' | 'exit';
  success: boolean;
  tunnelLatencyMs?: number; // entry only: entry→exit latency
  targetLatencyMs?: number; // agent→target latency
  totalLatencyMs?: number; // total round-trip latency
  error?: string;
}

// ========== Install Script Types ==========

/**
 * Install command response
 */
export interface InstallCommandResponse {
  installCommand: string;
  uninstallCommand: string;
  scriptUrl: string;
  serverUrl: string;
  token: string;
}

/**
 * Install script params
 */
export interface GetInstallScriptParams {
  token?: string; // Optional: If not provided, uses agent's stored token
  serverUrl?: string; // Optional: Override default server URL
}
