/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2025-12-23
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 */

import { apiClient } from '@/shared/lib/axios';
import type { APIResponse } from '@/shared/types/api.types';
import type {
  TelegramBinding,
  BindingStatusResponse,
  UpdatePreferencesRequest,
} from './types';

// ========== Telegram Binding APIs ==========

/**
 * Get current Telegram binding status
 * GET /telegram/binding
 * @requires Authentication
 *
 * Returns the current binding status and either:
 * - The binding details if already bound
 * - A verification code if not bound (for use with /bind command in Telegram)
 *
 * @example
 * ```typescript
 * const status = await getBindingStatus();
 * if (status.isBound) {
 *   console.log('Bound to:', status.binding?.telegramUsername);
 * } else {
 *   console.log('Verification code:', status.verifyCode);
 * }
 * ```
 */
export const getBindingStatus = async (): Promise<BindingStatusResponse> => {
  const response = await apiClient.get<APIResponse<BindingStatusResponse>>(
    '/telegram/binding'
  );
  return response.data.data;
};

/**
 * Unbind Telegram account
 * DELETE /telegram/binding
 * @requires Authentication
 *
 * Removes the Telegram binding for the current user.
 * After unbinding, the user will no longer receive Telegram notifications.
 *
 * @example
 * ```typescript
 * await unbindTelegram();
 * console.log('Telegram unbound successfully');
 * ```
 */
export const unbindTelegram = async (): Promise<void> => {
  await apiClient.delete('/telegram/binding');
};

/**
 * Update Telegram notification preferences
 * PATCH /telegram/preferences
 * @requires Authentication
 *
 * Updates the notification preferences for the user's Telegram binding.
 * All fields are optional - only provided fields will be updated.
 *
 * @param data - Preferences to update
 * @returns Updated binding details
 *
 * @example
 * ```typescript
 * // Enable expiring notifications, set to 7 days before
 * const binding = await updatePreferences({
 *   notifyExpiring: true,
 *   expiringDays: 7
 * });
 * ```
 */
export const updatePreferences = async (
  data: UpdatePreferencesRequest
): Promise<TelegramBinding> => {
  const response = await apiClient.patch<APIResponse<TelegramBinding>>(
    '/telegram/preferences',
    data
  );
  return response.data.data;
};
