/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2025-12-23
 */

// Types
export type {
  TelegramBinding,
  BindingStatusResponse,
  UpdatePreferencesRequest,
} from './types';

// API Client
export {
  getBindingStatus,
  unbindTelegram,
  updatePreferences,
} from './client';
