/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by Claude from backend Go code
 * Source: orris backend
 * Last updated: 2025-12-23
 *
 * Note: All properties use camelCase. The axios-case-converter middleware
 * automatically converts between snake_case (API) and camelCase (frontend).
 */

// ========== Telegram Binding Types ==========

/**
 * Telegram binding entity
 * Represents a user's Telegram account binding
 */
export interface TelegramBinding {
  /** Stripe-style prefixed ID (e.g., "tb_xK9mP2vL3nQ") */
  sid: string;
  /** Telegram user ID */
  telegramUserId: number;
  /** Telegram username (optional) */
  telegramUsername?: string;
  /** Whether to notify about expiring subscriptions */
  notifyExpiring: boolean;
  /** Whether to notify about traffic usage */
  notifyTraffic: boolean;
  /** Days before expiration to send notification (default: 3) */
  expiringDays: number;
  /** Traffic usage threshold percentage to trigger notification (default: 80) */
  trafficThreshold: number;
  /** When the binding was created */
  createdAt: string;
}

/**
 * Binding status response
 * Returns current binding status and verification code if not bound
 */
export interface BindingStatusResponse {
  /** Whether the user has a Telegram binding */
  isBound: boolean;
  /** Binding details (only present if isBound is true) */
  binding?: TelegramBinding;
  /** Verification code for binding (only present if isBound is false) */
  verifyCode?: string;
}

/**
 * Update notification preferences request
 * All fields are optional - only provided fields will be updated
 */
export interface UpdatePreferencesRequest {
  /** Whether to notify about expiring subscriptions */
  notifyExpiring?: boolean;
  /** Whether to notify about traffic usage */
  notifyTraffic?: boolean;
  /** Days before expiration to send notification (1-30) */
  expiringDays?: number;
  /** Traffic usage threshold percentage (1-100) */
  trafficThreshold?: number;
}
